In [1]:
import pandas as pd
import numpy as np

In [2]:
fund = pd.read_csv(r"/home/nivesh/startup_funding_project_streamlit/startup_funding.csv")
fund.head()

,Sr No,Date dd/mm/yyyy,Startup Name,Industry Vertical,SubVertical,City Location,Investors Name,InvestmentnType,Amount in USD,Remarks
0,1,09/01/2020,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,"20,00,00,000",NaN
1,2,13/01/2020,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,"80,48,394",NaN
2,3,09/01/2020,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,"1,83,58,860",NaN
3,4,02/01/2020,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,"30,00,000",NaN
4,5,02/01/2020,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,"18,00,000",NaN

In [3]:
sorted(fund['Startup Name'].unique().tolist())

['"BYJU\\\\\'S"',
 '#Fame',
 '121Policy',
 '19th mile',
 '1Crowd',
 '1mg',
 '1mg (Healthkartplus)',
 '20Dresses',
 '33Coupons',
 '360Ride',
 '3Dexter',
 '3HCare',
 '3rdFlix',
 '48East',
 '4tigo',
 '5th Vital',
 '6Degree',
 '75F',
 '91SpringBoard',
 '99Games',
 '99PerHour',
 '9Stacks',
 'A&R Bon Vivants',
 'ABI Health',
 'AEON Learning',
 'AHA Taxis',
 'AYE Finance',
 'AadharAPI.com',
 'Aadyah',
 'Aahaa',
 'Aahaa Stores',
 'Aarav UAV',
 'Aasaanjobs',
 'Aashiyaan',
 'Aavishkaar-Intellecap Group',
 'AbeRuk',
 'Abhibus',
 'Absentia',
 'Absentia VR',
 'Ace Turtle',
 'Ace2three',
 'Acko',
 'ActOnMagic',
 'Actionable Analytics',
 'Active AI',
 'Active.ai',
 'Actofit',
 'Ad2pro',
 'AdPushUp',
 'AdStringO',
 'AdUrCup',
 'AdWyze',
 'Address Health',
 'AdmitKard',
 'Advanced Structures India',
 'Advantage Club',
 'Advenio',
 'Adytude',
 'Aequm',
 'AerMed',
 'Affimity',
 'Affordplan',
 'Agara Labs',
 'AgentDesks',
 'Agricxlab',
 'Agrostar',
 'Agrowave',
 'AirCTO',
 'AirMed Labs',
 'AirZaar',
 'Airpay',
 'Airwood',
 'Aisle',
 'Aisle.co',
 'Akosha',
 'Alef\\\\nMobitech',
 'AllIzHealth',
 'Allygrow Technologies',
 'AlmaConnect',
 'AlmaMapper',
 'Alpha Capital',
 'Alteria Capital',
 'Alternacare',
 'Altizone',
 'Amagi Media Labs',
 'Ambee',
 'American Vision',
 'Amigobulls',
 'Ampere',
 'Ampere Vehicles',
 'Anakage',
 'Anandakanda',
 'Anchanto',
 'Annapurna Finance',
 'Antuit',
 'AppBrowzer',
 'AppDaily',
 'AppLop',
 'AppVirality',
 'Appario Retail Pvt Ltd.',
 'Appbase',
 'Appedo',
 'Appie',
 'AppilyEver',
 'Appknox',
 'Applicate',
 'Applied Solar Technologies',
 'Applop',
 'AppsDaily',
 'Appsdaily',
 'Appvigil',
 'Arcatron',
 'Arcatron Mobility',
 'Ark Robot',
 'Arkin Net',
 'Arohan Financial Services',
 'Arth DesignBuild',
 'Artoo',
 'Arya.ai',
 'Aryaka',
 'Asia Institute Of Medical Science',
 'AskMyGift',
 'Asocon',
 'Ather Energy',
 'Athletto',
 'Atlan',
 'Atomberg',
 'Atomberg Technology',
 'Attune Technologies',
 'Augrav',
 'AutoGrid',
 'AutoSense',
 'Autobix',
 'Automation Anywhere',
 'Autorox.co',
 'Avagmah',
 'Avail Finance',
 'AvailFinance',
 'Avanti Learning',
 'Avenue Growth',
 'Avishkaar Box',
 'Awaaz De',
 'Awesummly',
 'Awfis',
 'Awign',
 'Axio',
 'Axtria',
 'Aye Finance',
 'AyeFinance',
 'Azah',
 'Azuro',
 'B9 Beverages',
 'BHIVE',
 'BHIVE Workspace',
 'BRIDGEi2I',
 'BYG',
 'BYJU\\\\xe2\\\\x80\\\\x99s',
 'BYJU’S',
 'Babajobs',
 'Baby Berry',
 'BabyChakra',
 'Babychakra',
 'Babygogo',
 'BabyonBoard',
 'Badiyajobs',
 'BaggOut',
 'Balance App',
 'Banihal',
 'Bank Bazaar',
 'BankBazaar',
 'BankerBay',
 'Bats on delivery',
 'Baxi',
 'Be U Salons',
 'BeaconsTalk',
 'Beardo',
 'BeatRoute',
 'BedBathMore',
 'Belita',
 'Belong',
 'Benepik',
 'Bestdealfinance',
 'BetaOut',
 'Betaout',
 'Better Mortgage',
 'BetterButter.in',
 'BetterPlace',
 'Betterplace',
 'Bevy',
 'Bewakoof',
 'Beyond Evolution',
 'Bharat Bazaar',
 'BharatPe',
 'BhiveWorkspace',
 'BiBox',
 'Bidgely',
 'Big Basket',
 'Big Fish Ventures',
 'BigBasket',
 'BigStylist',
 'BigStylist.com',
 'Bikxie',
 'BillDesk',
 'Billion Loans',
 'Bira91',
 'Biryani Blues',
 'Biryani By Kilo',
 'BitGiving',
 'Bite Club',
 'Biteclub',
 'Bitla Software',
 'Biz2Credit',
 'Bizom',
 'Bizongo',
 'Black Soil',
 'Black White Orange',
 'Black White Orange Brands',
 'BlackBuck',
 'Blackbuck',
 'Blinge',
 'BlogBeats',
 'Blood n Care',
 'Blowhorn',
 'Blubox',
 'Blue Box Media',
 'Blue Tokai Coffee',
 'BlueStone',
 'Bluebirch',
 'Bluegape',
 'Bluegape.com',
 'Board Infinity',
 'Bobble',
 'BoiBanit',
 'BolRealty',
 'Bollant Industries',
 'Bolo App',
 'Bombay Shaving Company',
 'Bombay Shirt Company',
 'Bona Vita',
 'Bonhomia',
 'Bonphulapl',
 'Book My Diamond',
 'Book My Show',
 'Book Servicing',
 'BookEventz',
 'BookMeIn',
 'BookMyBai',
 'BookMyShow',
 'Bottr.me',
 'Bounty App',
 'Box My Space',
 'Box8',
 'Boxmyspace',
 'Boxx.ai',
 'Brick2Wall',
 'Brigge',
 'Briston Technomach',
 'Bro4U',
 'BroEx',
 'Broomberg',
 'Browntape',
 'BrowserStack',
 'Bucker',
 'Buddy',
 'Buddy4studdy',
 'Bueno',
 'BuildSupply',
 'BuildTraders',
 'Buildkar',
 'Buildzar',
 'Bumper',
 'Burger Singh',
 'Buttercups',
 'Butterfly Interactive',
 'BuyHatke',
 'Byju\\\\xe2\\\\x80\\\\x99s',
 'CAKART.in',
 'CBREX',
 'CBS',
 'CCAvenue',
 'CCavenue',
 'CREO',
 'CRON Systems',
 'CaRPM',
 'Cabsguru',
 'Call Health',
 'Campus Diaries',
 'CanvasFlip',
 'Canvera',
 'Canvs',
 'Capabiliti',
 'Capillary',
 'Capillary Tech',
 'Capita World',
 'Capital Float',
 'Capricoast',
 'Capzest',
 'CarDekho',
 'CarDekho.com',
 'CarTrade',
 'CarTrade.com',
 'Caratlane.com',
 'Caravan Craft',
 'Caravan Craft Retail',
 'Carcrew.in',
 'Care24',
 'Career Anna',
 'Career360',
 'CareonGO',
 'Careongo',
 'Carl\\\\xe2\\\\x80\\\\x99s Jr',
 'Cars24',
 'Cartisan',
 'Cartrade',
 'CarveNiche',
 'Casa2inns',
 'Cash Suvidha',
 'CashFree',
 'Cashe',
 'Cashflo',
 'Cashify',
 'Cashkaro',
 'Cashkaro.com',
 'Cashkumar',
 'Celerix',
 'Celes Care',
 'Cerebroz',
 'Chaayos',
 'Chai Point',
 'Chai Thela',
 'ChaiPoint',
 'Chakr Innovation',
 'Changer Mints',
 'ChargeBee',
 'Chargebee',
 'Chargein',
 'ChatOnGo',
 'CheersOye!',
 'Chefs Basket',
 'Chevon',
 'Chikoop',
 'Chillr',
 'ChipperSage',
 'Chloroplast Foods',
 'ChqBook',
 'Chrysalis',
 'Chumbak',
 'Chymera VR',
 'CimplyFive',
 'Citrus Payment',
 'CityFlo',
 'CityFurnish',
 'CityShor',
 'Civilsdaily',
 'Clapsnslaps',
 'CleanseCar',
 'ClearTax',
 'Cleartax',
 'Cleartrip',
 'CleverSharks',
 'CleverTap',
 'Click2Clinic',
 'Clip App',
 'Clodura',
 'Clonect Solutions',
 'Cloud Lending',
 'Cloudacar',
 'Cloudcherry Analytics',
 'Cloudrino',
 'Clovia',
 'Clumio',
 'Co Life',
 'Codemojo',
 'CodingLabs',
 'CoinTribe',
 'CollPoll',
 'CollateBox',
 'Collateral Medical',
 'Collectabillia',
 'CollegeDekho',
 'CollegeDunia',
 'Comarete',
 'Commeasure',
 'Commonfloor',
 'Commut',
 'ConfirmTKT',
 'ConfirmtTkt',
 'Connaizen',
 'Connect India',
 'ConnectAbank',
 'Consure Medical',
 'Convegenius',
 'Cooey',
 'Cookaroo',
 'Cookifi',
 'Coolshare',
 'Coppre',
 'Corporate360',
 'Corseco',
 'CouponRaja',
 'CoutLoot',
 'Coutloot',
 'CoveIoT',
 'CoverFox',
 'Coverfox',
 'CraftsVilla',
 'Craftstvilla',
 'Craftsvilla',
 'Crayon Data',
 'Creator\\\\xe2\\\\x80\\\\x99s Gurukul',
 'CredR',
 'CrediHealth',
 'Credifiable',
 'Credihealth',
 'Credit Mate',
 'Credit Sudhaar',
 'Credit Vidya',
 'CreditMantri',
 'CreditMate',
 'CreditSeva',
 'CreditVidya',
 'Credright',
 'Credy',
 'CroFarm',
 'Crofarm',
 'CropIn',
 'Cropin',
 'Crossahead',
 'Crowdera',
 'Crowdfire (formerly Justunfollow)',
 'Crown-it',
 'CrownIt',
 'Crownit',
 'Cube Consumer Services',
 'Cube26',
 'Cuberoot',
 'Cubito',
 'CueMath',
 'Cuelearn',
 'Cult',
 'Cult Fitness',
 'Culture Machine',
 'CultureAlley',
 'Cupick',
 'CupoNation',
 'Curatio',
 'Cure Fit',
 'CureFit',
 'CureInstant',
 'CureJoy',
 'Curefit',
 'Curie Labs',
 'Curiositi',
 'Curofy',
 'CustomFurnish.com',
 'Customer360',
 'CustomerSucessBox',
 'Customfurnish',
 'Cyclops',
 'CyclopsMedtech',
 'Cygnus Hospitals',
 'DAAKI',
 'Daalchini Technologies',
 'Daily Ninja',
 'Daily Rounds',
 'Daily hunt',
 'DailyHunt',
 'DailyNinja',
 'DailyObjects',
 'DailyRounds',
 'DarwinBox',
 'Data Resolve',
 'DataWeave',
 'DawaiLelo',
 'DayBox',
 'Dazo',
 'Deal 4Loans',
 'Deal Street Asia',
 'Deal4Loans / Wishfin',
 'Dealwithus',
 'Dekkho',
 'Delhivery',
 'Delight Foods',
 'Demyto',
 'Derbii',
 'Design Cafe',
 'DesignBids',
 'Devourin',
 'Deyor Camps',
 'Deyor Rooms',
 'Dhruva',
 'Dhruva Space',
 'DiabetOmics',
 'Didi',
 'Digiconectt',
 'Digilend',
 'Digio',
 'Digit',
 'Digital F5',
 'Digital Gorkha',
 'Digital Mall Asia',
 'Dil Mil',
 'Dipper',
 'Direct Create',
 'Diro Labs',
 'DishCo',
 'Disprz',
 'Djubo.com',
 'DoSelect',
 'DocPlexus',
 'DocTalk',
 'DocsApp',
 'Doctor Insta',
 'DoctorInsta',
 'DogSpot',
 'Don\\\\xe2\\\\x80\\\\x99t Scratch Your Head',
 'DoneThing',
 'DoodhWala',
 'Doormint',
 'Doxper',
 'Dream Wallets',
 'Dream11',
 'Drip capital',
 'DriveSkool',
 'DriveU',
 'DriversCart',
 'Drivestream',
 'Drivezy',
 'Drivify',
 'DrivoJoy',
 'Droom',
 'Droom.in',
 'DropKaffe',
 'Dropkaffe',
 'Drums Food',
 'Druva',
 'Duffl',
 'Dunzo',
 'EPS',
 'EPayLater',
 'ERA',
 'Early Salary',
 'EarlySalary',
 'EarlySalary.com',
 'Earth Food',
 'Easy Diner',
 'EasyEcom',
 'EasyFix',
 'EasyGov',
 'EasyKhaana',
 'EasyPolicy',
 'EasyRewardz',
 'EasyRoads',
 'Easypolicy',
 'Eat.Shop.Love',
 'Eatfresh',
 'Eatlo',
 'Eatonomist',
 'Eattreatonline',
 'Eazy Coach',
 'EazyDiner',
 'Eckovation',
 'Ecolibriumenergy',
 'Ecom Express',
 'Ecozen',
 'EdTechReview',
 'Edelweiss',
 'EdgeFx',
 'Edu4Share',
 'EduAce Services',
 'EduBridge',
 'EduKart',
 'EduPristine',
 'EduRev',
 'Edureka',
 'Edurev',
 'Edyoo',
 'Elanic',
 'ElastiRun',
 'ElasticRun',
 'ElderAid Wellness',
 'Elemential',
 'Elucidata',
 'Emflux Motors',
 'Emiza',
 'Emojifi',
 'Enabli',
 'Enakshi',
 'Endless Robotics',
 'Engineer.ai',
 'EngineerBabu',
 'Englishleap.com',
 'Entropik',
 'Entropika',
 'Entropy Innovations',
 'Envoged',
 'Epiq Capital',
 'Eruditus',
 'Ethinos',
 'Ethosh',
 'EureQa',
 'EvenGini',
 'EveningFlavors',
 'Events High',
 'Explara',
 'Explore Life traveling',
 'ExtraCarbon',
 'ExtraaEdge',
 'Eywa Media',
 'EzCred',
 'Ezetap',
 'EzySolare',
 'Ezyhaul',
 'Ezytruk',
 'FPL Technologies',
 'FR8',
 'FTCash',
 'FXMartIndia',
 'FYNE',
 'FYRE',
 'Faaso\\\\xe2\\\\x80\\\\x99s',
 'Faasos',
 'Faaya',
 'Fab Hotels',
 'FabAlley',
 'FabHotels',
 'FabX',
 'FableStreet',
 'Fabogo',
 'Fabulyst',
 'Faircent',
 'Faircent.com',
 'FalconBrick',
 'FarEye',
 'FarMart',
 'Farm Taaza',
 'FarmLink',
 'Farmizen',
 'Fashalot',
 'Fashionablyin',
 'Fashionove',
 'Fashor',
 'FastFox',
 'Fastudent',
 'FeetApart',
 'FiTraQ',
 'Fieldassist',
 'Finance Buddha',
 'Fincash',
 'Find My Stay',
 'FindUrClass',
 'FindYahan',
 'FindmeaShoe',
 'Findow',
 'Findyahan',
 'Fingerlix',
 'Finomena',
 'Finova Capital',
 'Fintellix',
 'Fintobox',
 'Finzy',
 'First Eat',
 'First Moms Club',
 'FirstCry',
 'FirstCry.com',
 'FirstTouch',
 'Fisdom',
 'FitMeIn',
 'Fitcircle',
 'Fitmein',
 'Fitnapp',
 'Fitpass',
 'Fitraq.com',
 'Fitso',
 'Fitternity',
 'Five Star Group',
 'FixNix',
 'Fixy',
 'Flashdoor',
 'FlatFurnish',
 'Flatchat',
 'Flatpebble',
 'FleetRover',
 'FleetX',
 'Flexiloans',
 'Flexing It',
 'FlickBay',
 'Flickstree',
 'FlipClass',
 'Flipkart',
 'Flipkart.com',
 'Flixy Games',
 'Flocareer',
 'Flochat',
 'Flutura',
 'Flyrobe',
 'Flytxt',
 'Focus Digit',
 'FoodAbhi',
 'FoodTalkIndia',
 'Foodmemories',
 'Foodpanda',
 'ForeverShop',
 'Formcept',
 'Fourseven',
 'Fourth Ambit',
 'Fourth Partner Energy',
 'Foyr.com',
 'Fracktal Works',
 'Fractal Analytics',
 'Frankly',
 'Frapperz',
 'FreeCharge',
 'Freedom Smart Labs',
 'Fresh Food Concepts',
 'FreshBoxx',
 'FreshDesk',
 'FreshMenu',
 'FreshVnF',
 'FreshWorld',
 'Freshboxx',
 'Freshdesk',
 'Freshee',
 'Freshmonk',
 'Freshworks',
 'Front Desk AI',
 'FroyoFit',
 'Frsh',
 'Frsh.co.in',
 'Ftcash',
 'Fulfil.IO',
 'FunOnGo',
 'Funcart',
 'Funcastic',
 'Fundamentor',
 'FundsIndia.com',
 'Furdo',
 'Furlenco',
 'Furtados School of Music',
 'Fusion Microfinance',
 'Fxkart.com',
 'Fyle',
 'Fyle Technologies',
 'Fynd',
 'GIBBS',
 'GIBSS',
 'GOQii',
 'Gaana',
 'Gaana.com',
 'Gadgets 360',
 'Gadgetwood',
 'Gajty',
 'Galleri5',
 'GameXS.in',
 'GameZop',
 'Gameezop',
 'Gaming Monk',
 'Gamooz',
 'Gapoon',
 'Garage On Road',
 'GenNext Students',
 'Genextstudents',
 'Genie',
 'Genius Corner',
 'Get My Parking',
 'Get Simpl',
 'GetFocus',
 'GetMyPeon',
 'GetVee',
 'Giftxoxo',
 'GigIndia',
 'Gingercrush',
 'Girnar Software',
 'Glam Studios',
 'GlamStudios',
 'Glamrs',
 'Glassic',
 'GlowRoad',
 'Glowroad',
 'Glowship',
 'GoBumpr',
 'GoChoppers',
 'GoComet',
 'GoDesi',
 'GoFro',
 'GoFynd',
 'GoGo Truck',
 'GoJavas',
 'GoMechanic',
 'GoPigeon',
 'GoQii',
 'GoYaNo',
 'GoZefo',
 'Goalwise',
 'Gobolt',
 'Godof Hospitals',
 'GoldFarm',
 'GolfLAN',
 'Gomalon',
 'Good Methods Global',
 'Goodbox',
 'Goodera',
 'Goodservice',
 'Goomo',
 'Goqii',
 'Gozoomo',
 'Grab',
 'Grab.in',
 'GrabOnRent',
 'Grabhouse',
 'Grabhouse.com',
 'Gradopedia',
 'GramCover',
 'Gramophone',
 'GrandOpinion',
 'Graphene',
 'Graphic India',
 'Gray Routes',
 'Greenlight Planet',
 'Grex',
 'Grey Campus',
 'Grey Orange',
 'GreyAtom',
 'GreytHR',
 'Gridle',
 'Grofers',
 'Groupon India',
 'Grover Zampa',
 'Grow Fit',
 'GrowFitter',
 'Groww',
 'Guarented',
 'Guiddoo',
 'Guidoo',
 'GuruG Learning',
 'Gurukul',
 'Gyaanzone',
 'GyanDhan',
 'GymTrekker',
 'Gympik',
 'Gympik.com',
 'HEAL Institute',
 'HUG Innovations',
 'HWell24',
 'HWell24 Plus',
 'HackerEarth',
 'HackerRank',
 'HalaPlay',
 'HandyHome',
 'HandyTrain',
 'Hansa Customer Equity',
 'Hansel io',
 'Hansel.io',
 'Happily Unmarried',
 'HappilyUnmarried',
 'Happitoo',
 'Happy EMI',
 'Happy2Refer',
 'HappyGoEasy',
 'Happydemic',
 'Haptik',
 'Haqdarshak',
 'Harness Handitouch',
 'HashLearn',
 'HashTaag',
 'Hasura',
 'HeadOut',
 'Heads Up For Tails',
 'Healers At Home',
 'HealthAssure',
 'HealthCare',
 'HealthEminds',
 'HealthEnablr',
 'HealthFin',
 'HealthIntel',
 'HealthKart',
 'HealthKumbh',
 'HealthMir',
 'HealthSutra',
 'Healthbuds',
 'Healthcare at Home',
 'Healthi',
 'Healthians',
 'Healthians.com',
 'HealthifyMe',
 'Healthifyme',
 'Healthsignz',
 'HealthyWorld.in',
 'Heckyl',
 'Hello Curry',
 'Hello Tax',
 'HelpChat',
 'HelpShift',
 'Helpi',
 'Heterogenous',
 'Hevo Data',
 'HeyBiz',
 'HeyPillow',
 'HiJinny',
 'High Radius',
 'HighRadius',
 'Highway Delite',
 'Hike',
 'Hike Messenger',
 'HipBar',
 'HipCouch',
 'Hipcask',
 'Hippily',
 'Hipship',
 'HitGrit',
 'Hitwicket',
 'HolaChef',
 'Holachef',
 'HolidayIQ',
 'Holidify',
 'Holisol Logistics',
 'HomeCapital',
 'HomeLane',
 'HomeStudio',
 'Homelane',
 'Homergize',
 'Homers.in',
 'Hoopy',
 'Hopping Chef',
 'Hoppingo',
 'Hopscotch',
 'Horntell',
 'Hostel Dunia',
 'Hotelogix',
 'Hotify',
 'House of Msasaba',
 'Housejoy',
 'Housing',
 'Housing.com',
 'HousingMan',
 'Houssup',
 'Howdy Ventures',
 'Hubilo',
 'Hugefly',
 'Hungama',
 'HungerBox',
 'Hungry Foal',
 'HyperTrack',
 'HyperVerge',
 'Hypernova Interactive',
 'I Can Stay',
 'IBSFintech',
 'ICHR',
 'ICustomMadeIt',
 'IDG Ventures',
 'IDfy',
 'IFMR Holdings',
 'IGP.com',
 'IIM Jobs',
 'IMAX Program',
 'IMbesharam',
 'INDwealth',
 'ION Energy',
 'IOTrek',
 'IQlect',
 'ISFC',
 'Icertis',
 'Idea Bubbles',
 'IdeaChakki',
 'IdeaForge',
 'Ideal Insurance',
 'Ignis Careers',
 'ImageProVision',
 'Imaginate',
 'Imarticus Learning',
 'Impact Analytics',
 'Impact Guru',
 'ImpactGuru',
 'Impartus',
 'InCred',
 'InCred Finance',
 'Inayo',
 'Inc42',
 'Inclov',
 'Increff',
 'Indee',
 'Indi.com',
 'India Gifts Portal',
 'India Lends',
 'IndiaLends',
 'Indiamart',
 'IndianRoots.com',
 'Indiez',
 'Indifi',
 'IndigoLearn',
 'Indix',
 'Indofash',
 'Indus OS',
 'IndustryBuying',
 'Industrybuying',
 'Infibeam',
 'Infinite Analytics',
 'Infisecure',
 'Infogain',
 'Infoworks',
 ...]

In [4]:
fund.info()

<class 'pandas.DataFrame'>
RangeIndex: 3044 entries, 0 to 3043
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Sr No              3044 non-null   int64
 1   Date dd/mm/yyyy    3044 non-null   str
 2   Startup Name       3044 non-null   str
 3   Industry Vertical  2873 non-null   str
 4   SubVertical        2108 non-null   str
 5   City  Location     2864 non-null   str
 6   Investors Name     3020 non-null   str
 7   InvestmentnType    3040 non-null   str
 8   Amount in USD      2084 non-null   str
 9   Remarks            419 non-null    str
dtypes: int64(1), str(9)
memory usage: 593.3 KB

In [5]:
# there are missing values in investor name
# replace the missing values with undisclosed 
fund['Investors Name'] = fund['Investors Name'].fillna('Undisclosed')
sorted(fund['Investors Name'].unique().tolist())

['"Kedaraa Capital, Ontario Teachers\\\\\'"',
 '021 Capita, Binny Bansal',
 '1Crowd',
 '1Crowd (through crowd funding)',
 '1Crowd (through crowdfunding)',
 '1Crowd, Ankur Capital',
 '1Crowd, Eureka Forbes Ltd, Shapoorji Pallonji & Co. Ltd.',
 '3 undisclosed HNIs',
 '3 undisclosed investors',
 '3One4 Capital',
 '3one4 Capital, Mumbai Angels, Aarin Capital',
 '3one4 Capital, Tracxn Labs, Aaruha Technology Fund, Endiya Partners',
 '3one4 capital',
 '500 Startups',
 '500 Startups, IDG Ventures & Advantedge fund, Neeraj Arora, Leon Seynave',
 '500 Startups, IvyCap Ventures',
 '500 Startups, Littlerock, Singularity Ventures',
 '500 Startups, Mato Peric & Others',
 '500 Startups, Mato Peric, TracxnLabs',
 '500 Startups, Purvi Capital, Rajan Anandan, Abhishek Gupta',
 '500 Startups, Smile Multimedia, Kunal Bahl, Rohit Bansal, Girish Matrubootham',
 '500 Startups, TV Mohandas Pai, Tandem Capital, Vikram Chachra, Aloke Bajpai',
 '50K Ventures',
 '50k Ventures, Munish Jauhar, Pulkit Jain, Rohit Narang',
 '91maker.com',
 'A M Sikander',
 'A91 Partners',
 'AB Kinnevik, Falcon Edge Capital, Coatue Management',
 'ABI-Showatech (India) Ltd',
 'ABM Knowledgeware',
 'ADAG Reliance Private Equity',
 'AJ Ventures and Jain International Trade Organisation (JITO)',
 'ANALEC',
 'ANI Technologies Pvt. Ltd',
 'APIS Partners',
 'ASK Pravi',
 'AV Thomas Group',
 'AVG Group, 500 Startups',
 'Aakrit Vaish, Swapan Rajdev, Sushill Jiwarajka',
 'Aamir Khan',
 'Aarin Capital',
 'Aarin Capital Partners',
 'Aarin Capital Partners,',
 'Aarin Capital Partners, TV Mohandas Pai',
 'Aarin Capital, Michael Herzig, Ashish Lakhanpal',
 'Aarin Capital, Unitus Seed Fund',
 'Aarti Group',
 'Aavishkaar',
 'Aavishkaar Venture Management',
 'Aavya Ventures',
 'Abhijit Avasthi, Karan Chellani, SP Vijay',
 'Abhinav Bindra, Gaurav Marya',
 'Abhinav Gupta,',
 'Abhinav Mathur',
 'Abhishek Agarwal, Krishnakumar Nataraj, Sarath Sura, Shanti Mohan, Sarthak and Nihit Agarwal, Suramya Gupta',
 'Abhishek Bhatewara, Vivek Shah, Haitong Securities, Suraj Saharan, Paras Arora',
 'Abhishek Gupta',
 'Abraaj Group',
 'Accel (formerly known as Accel Partners)',
 'Accel Partner, Jungle Ventures',
 'Accel Partners',
 'Accel Partners India',
 'Accel Partners India, RB Investments',
 'Accel Partners,',
 'Accel Partners, Anupam Mittal & other marquee investors',
 'Accel Partners, Ashish Hemrajani, Parikshit Dar, Rajesh Balpande',
 'Accel Partners, Beenext, Powerhouse Ventures, Akusa Holdings',
 'Accel Partners, Deep Kalra, Rajesh Magow, Mohit Gupta, Shamik Sharma',
 'Accel Partners, Elevar Equity, Pramod Bhasin, Rajan Anandan, Gaurav Dalmia, Abhishek Goyal, Gagan Hasteer , Arun Tadanki',
 'Accel Partners, Exfinity Ventures, Partech Ventures',
 'Accel Partners, Flipkart',
 'Accel Partners, Helion Venture Partners',
 'Accel Partners, IDG Venture, Endiya Partners, pi Ventures, VH Capital, Axilor Ventures and Binny Bansal',
 'Accel Partners, IDG Ventures India',
 'Accel Partners, IDG Ventures, Endiya Partners, pi Ventures, VH Capital, Axilor Partners',
 'Accel Partners, IDG Ventures, Kalaari Capital',
 'Accel Partners, IDG Ventures, Kalaari Capital,\\\\xc2\\\\xa0 UC-RNT fund',
 'Accel Partners, Indian Angel Network, India Innovation Fund India Venture Partners',
 'Accel Partners, International Finance Corporation (IFC), Qualcomm Ventures, Ventureast',
 'Accel Partners, Jungle Ventures, SeedPlus',
 'Accel Partners, Kalaari Capital',
 'Accel Partners, Matrix Partners, Girish Mathrubootham',
 'Accel Partners, Nandan Nilekani,',
 'Accel Partners, Nandan Nilekani\\\\xe2\\\\x80\\\\x99s NRJN Trust, Mistletoe, Qualcomm Ventures, M&S Partners',
 'Accel Partners, Qualcomm Ventures, M&S Partners, Zop Smart',
 'Accel Partners, RB Investments',
 'Accel Partners, SAIF Partners',
 'Accel Partners, Sequoia Capital',
 'Accel Partners, Sequoia Capital, RB Investments',
 'Accel Partners, Sequoia India, Y Combinator and others.',
 'Accel Partners, Shunwei Capital',
 'Accel Partners, Subrata Mitra, Larry Braitman, Venk Krishna',
 'Accel Partners, Tiger Global And Others',
 'Accel Partners, Tiger Global Management',
 'Accel Partners, Traxcn Labs & Others',
 'Accel Partners, Zephyr Peacock',
 'Accel US, Accel India, SAIF Partners.',
 'Accion Venture Lab, Unicorn India Ventures and ISME ACE.',
 'Accion Venture Lab, YourNest Venture Capital And Other Angel Investors',
 'Accion Venture Labs, Rianta Capital',
 'Accion, LeapFrog Investments, Lok Capital',
 'Ackermans & van Haaren, HealthQuad, Rebright Partners, Toppan Printing',
 'Actis, Altimeter Capital',
 'Acumen Fund',
 'Adroitent Pvt. Ltd.',
 'AdvantEdge',
 'Aegon NV',
 'Aequs Group',
 'Agarwal Movers Group',
 'Agnus Capital',
 'Agnus Capital, Khattar Holdings',
 'Ah! Ventures, Calcutta Angels,\\\\xc2\\\\xa0 91SpringBoard',
 'Ajai Chowdhry, Ashvin Chadha, Yogesh Bansal,\\\\nNitin Singhal & Others',
 'Ajay Data & other HNIs',
 'Ajay Data & undisclosed HNIs',
 'Ajay Nanavati, Afsal Salu',
 'Ajay Piramal',
 'Ajay Relan',
 'Ajay Relan and Vinay Mittal',
 'Ajay Relan,',
 'Ajay Relan, LetsVenture',
 'Ajeet Khurana & Others',
 'Ajeet Khurana Jinesh Shah, Vikram Chachra, Dr. Aniruddha Malpani',
 'Ajit Surana, Sanjay Mehta',
 'Ajith Nair',
 'Ajith Nair, Anish K',
 'Ajith Sukumaran, Currae Healthtech Fund',
 'Ajmera Group of Companies',
 'Al Dhaheri family',
 'Alex Chua, Rahul Garg',
 'Alex Kuruvilla, Pradeep Guha, Saket Dhankar, Rajan Pandhare',
 'Alibaba',
 'Alibaba Group, Ant Financial',
 'Alibaba Pictures',
 'Alibaba, Foxconn, Softbank',
 'Alibaba, Helion Venture Partners, Bessemer Venture Partners, Ascent Capital',
 'Allcargo Logistics, Navneet Education and Mahavir Agency',
 'Allen Blue, John Katzman, Naveen Tewari, Kartik Hosanagar, Kashyap Deorah, 500 Startups, Blue Fog Capital',
 'Alok Bajpai, Rajnish Kumar, Amit Dey',
 'Alok Goel',
 'Alok Mittal',
 'Alok Mittal, Amit Gupta, Anuj Srivastava, Himanshu Aggarwal, Raghunandan G, Puneet Agarwal',
 'Alok Mittal, Deepak Jain, Ritesh Malik, Jim Schimdktke',
 'Alok Mittal, Zeeshan Hayat, Niraj Singh, Nikunj Jain, Anirudh Damani, Punit Goyal',
 'Alok Rawat, Grey Orange Robotics',
 'Alpha Capital',
 'Alphard Maritime Group',
 'Alteria Capital',
 'Altimeter Capital, DST Global',
 'Altimeter Capital, Sutter Hill Ventures',
 'Amadeus Capital',
 'Amajit Gupta, Praveen Dubey, J.P. Bhatt',
 'Amazon',
 'Amazon Alexa Fund & Dentsu Ventures',
 'Amazon Inc. and Mastercard',
 'Amazon, Ashish Dhawan, Catamaran Ventures, NR Narayana Murthy.',
 'Amazon, Fidelity Growth Partners, Mousse Partners',
 'Amazon, Vertex Ventures, Qualcomm, Ru-Net Technology Partners, Matrix Partners',
 'Amazon-Patni JV',
 'Ambarish Gupta, Aneesh Reddy, Bold Ventures, Vona Investments',
 'Ambit Pragma',
 'Ameera Shah, Vivek Bhargava',
 'Amen Dhyllon',
 'American Express Ventures, Sequoia Capital',
 'Amicus Capital',
 'Amit Burman, SIDBI Venture Capital',
 'Amit Choudhary',
 'Amit Choudhary, Anuj Puri',
 'Amit Gupta, Sahil Barua, Mukul Singhal, Tracxn Labs',
 'Amit Patni',
 'Amit Patni, Anirudh Damani, Samir Shah',
 'Amit Ranjan, Deepinder Goyal, Zishaan Hayath, Powai Lake Ventures',
 'Amit Ranjan, Vijay Shekhar Sharma, Kunal Bahl, Girish Mathrubootham &\\\\xc2\\\\xa0 Group of other Angel investors',
 'Amit Singhal and Unitus Seed Fund',
 'Amit Singhal, PK Gulati & others',
 'Amit Tyagi, Sandeep Acharya & others',
 'Amod Malviya',
 'Amour Infrastructure',
 'Anand Chandrasekaran',
 'Anand Chandrasekaran & Others',
 'Anand Chandrasekaran, Ananth Narayanan, Mekin Maheshwari, Ravi Garikipati, Divyesh Shah, Swastika Company Ltd',
 'Anand Chandrasekaran, Apurva Chamaria, Ritesh Malik, Ashish Toshniwal, Ajeet Khurana',
 'Anand Chandrasekaran, Kanwaljit Singh, Manoj Varghese',
 'Anand Chandrasekaran, Rajesh Sawhney, Kalpana Tatavarti, Shivanandan Pare',
 'Anand Chandrasekaran, Rajiv Mehta, Ramakant Sharma',
 'Anand Mahindra',
 'Anand Mahindra, Uday Punj, Ashish Hemrajani, Sanjeev Mehra',
 'Anand Rajaraman, Venky Harinarayan',
 'Anand Sankeshwar, Yang Shu',
 'Anand Vijay, Nipun Dureja, Satyajit Heeralal, Keith Rodricks, Gaurav Lochan, Azmul Haque, Nikhil Bagri',
 'Anand Vijay, Shashank Mehrotra & Others',
 'Aneesh Seth, Tushar Mittal',
 'AngelList, Rahul Khanna, Rajeev Arora and Ram Ramsundar.',
 'AngelPrime',
 'Anglian Omega Network',
 'Anicut Capital',
 'Anil Advani, Pramod Jain, Amrendra Reddy and Manish Satnaliwala.',
 'Anil Jain & other HNIs',
 'Anil Kapoor',
 'Anil Matai, Vikram Tandon, Shyam Sundar R & others',
 'Anil Menon',
 'Aniruddha Malpani, Startup Oasis',
 'Anirudh Damani, Daud Ali, Narendra Karnavat, Vikas Kapoor, Vikram Lakhotia, Krishna Jhunjhunwaala, Jayesh Shah',
 'Anirudh Damani, Vikram Lakhotia',
 'Anita Dongre, Yash Dongre, Milind Sarwate',
 'Ankit Gupta, Puneet Motihar',
 'Ankit Maheshwari, Anand Singh',
 'Ankit Nagori',
 'Ankur Capital',
 'Ankur Capital, Hyderabad Angels',
 'Ankur Gupta',
 'Ankush Mehta',
 'Ankush Nijhawan, Manish Dhingra, Gaurav Bhatnagar',
 'Ant Financial',
 'Ant Financial Services (Alipay)',
 'Ant Financials',
 'Anuj Puri, Redcliffe Capital, Artha India Ventures, Siddharth Kothari, Apoorv Ranjan Sharma,',
 'Anupam Mittal, Amit Gupta, Utsav Somani, Neeraj Goenka, Farooq Adam Mukadam',
 'Anupam Mittal, Anand Chandrasekaran, Uday Shankar, Chetan Bhagat',
 'Anupam Mittal, Anuj Srivastava, Ankit Nagori',
 'Anupam Mittal, Manish Vij, Prashant Tandon, Gaurav Agarwal, Akash Agarwal, Himanshu Aggarwal, Kevin Parikh',
 'Anupam Mittal, Sharad Sharma & 14 others',
 'Anurag Chauhan',
 'Aparup Sengupta, Devendra Reddy,',
 'Apis Partner, Eight Roads Ventures, Bamboo Capital Partners',
 'Apoorv Ranjan Sharma, Daud Ali and others',
 'Applyifi',
 'Aprameya Radhakrishna',
 'Aprameya Radhakrishna, Deepak Natraj, Girish Mathrubootham, Mahesh Murthy, Pallav Nadhani, Pavan Ongole, Sandeep Mathur, Vijay Shekhar Sharma & Others',
 'Aprameya Radhakrishna, Naman Sarawagi, Afsal Salu,',
 'Aqeel Ahmed',
 'Aramex Ventures Llc',
 'Arihant Patni, Avnish Mehra, Pranay Adhvaryu, Ravi Sampat',
 'Arihant Patni, RAAY Global Investments',
 'Arihant Patni, Vishal Khare,\\\\xc2\\\\xa0 Viswanath Ramachandran',
 'Arjun Handa, Amit Jindal, Nagendra Chaudhary',
 'Armat Group',
 'Artha India Ventures, Singularity Holdings, Rajan Anandan, Girish Mathrubootham',
 'Artha Venture',
 'Artiman Ventures',
 'Arun Chandra Mohan',
 'Arun Chandra Mohan, Praveen Sinha',
 'Arun Patodia, Bharat Kedia',
 'Arun Seth, T.V. Mohandas Pai, Anand Chandrasekaran, Deepak Ghaisas',
 'Arun Tadanki, Aditya Verma',
 'Ascent Capital, Kalaari Capital',
 'Ash Bhardwaj',
 'Asha Jadeja Motwani & Others',
 'Ashish Gupta',
 'Ashish Gupta and other undisclosed investors',
 'Ashish Jhalani',
 'Ashish Kacholi, S Chand Group',
 'Ashish Mahajan, Sarvesh Sharma',
 'Ashish Todi, Abhinav Patodia, Kumar Shwetabh',
 'Ashok Agarwal',
 'Ashok Goel (promoter)',
 'Ashok Kumar Gajera',
 'Ashutosh Lawania, Alok Goel & others',
 'Ashutosh Lawania, Rajul Jain, Badal Malick, Rishi Gupta & Others',
 'Ashvin Chadha',
 'Ashvin Chadha, Avtar Monga, Udaan Angels, Dheeraj Jain',
 'Asia Pacific Internet Group',
 'AskMe',
 'Aspada Advisors, IDG Ventures,\\\\xc2\\\\xa0 Inventus Capital',
 'Aspada Investment Advisors, Blume Ventures.',
 'Aspada Investment Advisors, Qualcomm Ventures',
 'Aspada Investments',
 'Aspire Logistics LLC',
 'Aspire Systems',
 'Asset Management (Asia) Ltd, Digital Garage Inc',
 'Astarc Ventures',
 'Astarc Ventures & Others',
 'Astarc Ventures, 50K Ventures & others',
 'Astarc Ventures, Anand Chandrasekaran',
 'Asuka Holdings',
 'Asuka Holdings, YouWeCan Ventures, Beenext, Beenos, M&S Partners',
 'Asuka, Pravega Ventures, BEENEXT',
 'Atul Gupta and Saurabh Rastogi',
 'Atul Ingle',
 'Atul Jain, Anil Gelra, Jaikumar Nair',
 'Atul Jalan',
 'Atul Jalan, Shrikanth & Bharath',
 'Atul Nishar',
 'Atulya Mittal',
 'Augment Ventures, Rahul Kayan, Nikhil Golcha, Shubham Gupta, Roy Kwan',
 'August Capital Partners, Michael Blakey',
 'Auxano Deals',
 'Avendus Finance',
 'Avendus Finance Pvt. Ltd',
 'Avtar Monga, chief operating office at IDFC Bank, Aditya Malik & Others',
 'Axiata Digital',
 'Axilor Ventures',
 'Axilor Ventures, E-City VEntures Atul Goel',
 'Axilor Ventures, Kumar Vembu',
 'Axilor Ventures, Newfort Capital',
 'Axilor Ventures, Parampara Early Stage Opportunities Fund & Others',
 'Axilor, Sprout Venture Partners and others',
 'Axilor, undisclosed investors',
 'Axis Capital Partners',
 'Ayesha Takia Azmi, Abu Farhan Azmi',
 'Ayushmann Khurana',
 'Azim Premji, Binny Bansal',
 'B Capital Group, Ignition Partners, Greycroft, e.ventures,\\\\xc2\\\\xa0 Eight Roads Ventures',
 'B Capital, International Finance Corporation (IFC), Accel Partners and IDG Ventures',
 'B M Gupta, Vinod Singhal',
 'B S Nagesh',
 'BAC Acquisitions, Unifi AIF, BRD Securities, Northern R Capital',
 'BCCL',
 'BEENEXT',
 'BLIP Initiatives',
 'Baillie Gifford, Falcon Edge Capital, Tiger Global, SoftBank Group, DST Global, Didi Kuaidi',
 'Balasubramanian Krishnamurthy, Sidhartha Hazarika & Others',
 'Base of Pyramid Asia (BOPA) Pte Ltd',
 'Baskar Subramanian, Saket Kumar, Gaurav Suri and Ankit Kesarwani',
 'Batlivala & Karani Securities, Venture Works',
 'Battery Road Digital Holdings LLC',
 'Bay Capital Investments and Others',
 'BedRock Ventures, Rajesh Sawhney, Shailesh Singh',
 'Bedrock Ventures',
 'BeeNext , WEH Ventures and Sprout Ventures',
 'BeeNext, TV Mohandas Pai, Kunal Shah, Sandeep Tandon',
 'Beenext',
 'Beenext, Digital Garage, Beenos, Qualgro, Mamoru Taniya, SAIF Partners',
 'Beenext, Digital Garage, Lightbox, Beenos',
 'Beerud Sheth and Ravi Mantha',
 'Bennett Coleman and Company Ltd (BCCL)',
 'Bennett, Coleman and Co. Ltd (BCCL)',
 'Bennett, Coleman and Company Ltd',
 'Bennett, Coleman and Company Ltd (BCCL),',
 'Benori Ventures LLP',
 'Bertelsmann India',
 'Bertelsmann India Investments',
 'Bertelsmann India Investments, Mayfield India, Saama Capital, India Quotient',
 'Bertelsmann India Investments, Nirvana Digital India Fund, Nirvana Digital Investment Holding, 500 Startups',
 'Bertelsmann India, Mayfield Capital, Saama Capital, Darrin Capital',
 'Bessemer Venture Partner, Accel, SAIF Partners',
 'Bessemer Venture Partners',
 'Bessemer Venture Partners and Orios Venture Partners, JM Financials and MEMG',
 'Bessemer Venture Partners, Anil Chopra',
 'Bessemer Venture Partners, Jungle Ventures, Helion Ventures',
 'Bessemer Venture Partners, Orios Venture Partners, Trifecta Capital,',
 'Bessemer Venture Partners, SAIF Partners',
 'Bessemer Venture Partners, Stellaris Venture Partners, Axis Capital, Singapore, Jungle Venture Partners',
 'Bessemer Venture Partners, Stellaris Venture Partners, Jungle Venture Partners, Axis Capital',
 'Bessemer Ventures, Blume Ventures',
 'Bessemer Ventures, Kae Capital',
 'Best Foodworks',
 'BetOnIndia Technology Pvt Ltd',
 'Bhairavi Jani, Alok Divatia, Namrata Kaul, Sohail Hashemi, Aijaz Saleem',
 'Bhanu Vikram Parsotam, Rohan Desai and Paras Patel',
 'Bharanidharan Viswanathan, Sanjiv Mittal, Shobhit Shukla, Rahul Agarwal',
 'Bharat Innovation, IDFC-Parampara Capital, Arthavida Ventures, Jitendra Gupta & Others',
 'Bhavdeep Reddy',
 'Bhavesh Manglani, Suraj Saharan, Darshan Upadhyay, Sanjay Notani & Others',
 'Bhavin Turakhia',
 'Bhavish Aggarwal, Ankit Bhati',
 'Bhavish Aggarwal, Binny Bansal,\\\\xc2\\\\xa0 Rajan Anandan, Mekin Maheshwar, Sunil Kalra, Anupam Mittal, Krishna Mehra, Singapore Angel Network',
 'Bhupen Shah, Jayesh Parekh, Sanjay Sathe',
 'Binny Bansal',
 'Binny Bansal, Anupam Mittal, Sachin Bhatia, Darius Pandole, Kunal Khattar, Dheerag Jain',
 'BitChemy Ventures, Maheshwari Investments Pvt Ltd, Anshoo Gaur, Rama Krishna Reddy, Sandeep Seerapu',
 'Bitkemy Ventures',
 'Biz Stone',
 'Biz Stone, Kunal Bahl, Rohit Bansal, Alagu Periyannan and Karthee Madasamy',
 'BlackJag Partners',
 'BlackSoil Capital Pvt Ltd',
 'BlackSoil Capital Pvt. Ltd',
 'BlackSoil Capital Pvt. Ltd.',
 'Blacksoil Capital Pvt. Ltd',
 'Blackstone Valley Group, Raghu Vohra, Aditya Dev Sood, Kamal Bansal',
 'Blinc Advisors, Amit Nanavati, Tashwinder Singh, Taranjit Jaswal, Amit Khanna',
 'Blue Orchard',
 'BlueOrchard Finance Ltd, Hinduja Leyland Finance and IntelleGrow',
 'Blume Ventures',
 'Blume Ventures & Other unnamed Investors',
 'Blume Ventures & Others',
 'Blume Ventures and RTP Global',
 'Blume Ventures, Adil Allana, Aprameya Radhakrishna, Gautam Ivatury, Signal Point Partners',
 'Blume Ventures, BEENEXT, Barkawi Holdings GmbH, TM Service Technology Holdings Gmbh, Sreevathsa Prabhakar',
 'Blume Ventures, Barkawi Holdings GmbH, TM Service Technology Holdings GmbH',
 'Blume Ventures, Contrarian Capital India Partners, Emergent Ventures India, Pallav Nadhani, Ashish Gupta, Sharad Sharma, Sirion Labs',
 'Blume Ventures, Contrarian Capital, 91springboard, Emergent Ventures, Abstract Ventures, Anthill Ventures, Axilor Ventures',
 'Blume Ventures, Flipkart',
 'Blume Ventures, Girish Mathrubootham, Aprameya Radhakrishna',
 'Blume Ventures, Goldbell Group, Anurag Srivastava, Shailesh Rao, Amiya Pathak, Rajesh Yohanan and Rahul Garg',
 'Blume Ventures, HealthQuad and Fireside Ventures',
 'Blume Ventures, IDG Ventures & Indian Angel Network',
 'Blume Ventures, Indian Angel Network',
 'Blume Ventures, Indian Angel Network, Kunal Shah, Sandeep Tandon',
 'Blume Ventures, Mumbai Angels, ah! Ventures, Digital Currency Group, Boost VC, Bank to the Future and Funders Club',
 'Blume Ventures, NB Ventures, Nspira',
 'Blume Ventures, Rajan Anandan, Sumit Jain, Aprameya Radhakrishna, Sujeet Kumar, Phanindra Sama',
 'Blume Ventures, Sachin Bansal, Vijay Shekhar Sharma, Binny Bansal,\\\\xc2\\\\xa0 Kunal Shah, Sandeep Tandon, Ashish Tulsian',
 'Blume Ventures,\\\\xc2\\\\xa0 Tracxn Labs',
 'Blume Ventures. Lenovo Capital and Incubator Group (LCIG)',
 'Blume ventures',
 'Bodhtree Consulting Limited',
 'Boman Irani, Dhruv Chitgopekar, Prantik Dasgupta',
 'BookMyShow',
 'Brand Capital',
 'Brand Capital and Others',
 'Brand Capital, Paragon Trust',
 'Brand Capital, Siddhivinayak Skyscrapers, Dinesh R. Challa',
 'Bravia Capital',
 'Breakthrough Energy Ventures',
 'Bren Corporation',
 'Brian Acton',
 'Brick Eagle',
 'Brigade Innovations LLP, TV Mohandas Pai, Suhail Rahman, Bobby Reddy, M George Oommen',
 'British and Indian Governments',
 'Broadbean Capital services',
 'ByteDance, Arun Sarin, Matrix Partners, Sequoia Capital India, Omidyar Network,\\\\xc2\\\\xa0 Falcon Edge',
 'C4D Partners',
 'CA Media LP,\\\\xc2\\\\xa0 Start Media.',
 'CASHurDRIVE Marketing Pvt Ltd',
 'CBA Capital and others',
 'CCube Angels, Frontline Strategy',
 'CDC Group Plc',
 'CDC Group plc\\\\xc2\\\\xa0',
 'CIO Angel Network',
 'CIO Angel Network (CAN)',
 'CIO Angel Network, Indian Angel Network',
 'CLP Holdings Group, Innogy, \\\\xc3\\\\x98rstead, and Tenaska',
 'CLSA Capital Partners ARIA IV Funds',
 'CMYK Health Boutique Pvt Ltd & Other individual investors',
 'CP Bothra',
 'Calcutta Angel Network, Appliyifi',
 'Calcutta Angels Network',
 'Calcutta Angels Network (CAN), Augment Ventures',
 'Calcutta Angels Network, LetsVenture, Anupam Mittal, Currae Healthtech Fund',
 'Calcutta Angels, Lead Angels & Others',
 'Calcutta Angels, Venture Nursery Angels Mumbai Angels',
 'Cameron Jones',
 'Canaan Partners',
 'Cao Yibin, Huang Wei, Madhusudan E,',
 'Capillary Technologies, Whiteboard Capital, YourNest Angel Fund, Rajul Garg',
 'CapitalG, SAIF Partners and LGT Impact Ventures',
 'CapitalG, Sequoia India',
 'CareerNet Consulting Pvt. Ltd, Ideation Initiative Pvt. Ltd,',
 'Carlyle Group, Tiger Global',
 'Carpediem Capital',
 'Carpediem Capital & Others',
 'Carrick Capital Partners',
 'Catamaran Ventures, New India Investment Corporation',
 'Cataraman Ventures',
 'Centre For Incubation & Business Acceleration (CIBA), Goa',
 'Centre for Innovation Incubation and Entrepreneurship (CIIE)',
 'CerraCap',
 'Chan Zuckerberg Initiative, Times Internet Ltd, Sequoia Capital, Sofina, Lightspeed Ventures',
 'Chandigarh Angel Network (CAN)',
 'Chandigarh Angels Funding',
 'Chandigarh Angels Network',
 'Chandigarh Angels Network (CAN)',

In [6]:
fund.info()

<class 'pandas.DataFrame'>
RangeIndex: 3044 entries, 0 to 3043
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Sr No              3044 non-null   int64
 1   Date dd/mm/yyyy    3044 non-null   str
 2   Startup Name       3044 non-null   str
 3   Industry Vertical  2873 non-null   str
 4   SubVertical        2108 non-null   str
 5   City  Location     2864 non-null   str
 6   Investors Name     3044 non-null   str
 7   InvestmentnType    3040 non-null   str
 8   Amount in USD      2084 non-null   str
 9   Remarks            419 non-null    str
dtypes: int64(1), str(9)
memory usage: 593.2 KB

In [7]:
# remove the remarks column
fund.drop(columns=['Remarks'],inplace=True)

In [8]:
fund.head()

,Sr No,Date dd/mm/yyyy,Startup Name,Industry Vertical,SubVertical,City Location,Investors Name,InvestmentnType,Amount in USD
0,1,09/01/2020,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,"20,00,00,000"
1,2,13/01/2020,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,"80,48,394"
2,3,09/01/2020,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,"1,83,58,860"
3,4,02/01/2020,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,"30,00,000"
4,5,02/01/2020,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,"18,00,000"

In [9]:
# set the Sr No as the row index of fund
fund.set_index('Sr No',inplace=True)

In [10]:
fund.head()

,Date dd/mm/yyyy,Startup Name,Industry Vertical,SubVertical,City Location,Investors Name,InvestmentnType,Amount in USD
Sr No,,,,,,,,
1,09/01/2020,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,"20,00,00,000"
2,13/01/2020,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,"80,48,394"
3,09/01/2020,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,"1,83,58,860"
4,02/01/2020,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,"30,00,000"
5,02/01/2020,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,"18,00,000"

In [11]:
# rename the columns of this dataframe
fund.rename(columns={'Sr No':'sr','Date dd/mm/yyyy':'date','Startup Name':'startup','Industry Vertical':'vertical',
                     'SubVertical':'subvertical','City  Location':'city','Investors Name':'investors',
                     'InvestmentnType':'round','Amount in USD':'amount'},inplace=True)

In [12]:
fund.head()

,date,startup,vertical,subvertical,city,investors,round,amount
Sr No,,,,,,,,
1,09/01/2020,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,"20,00,00,000"
2,13/01/2020,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,"80,48,394"
3,09/01/2020,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,"1,83,58,860"
4,02/01/2020,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,"30,00,000"
5,02/01/2020,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,"18,00,000"

In [13]:
fund.rename(columns={'stratup':'startup'},inplace=True)

In [14]:
fund.head()

,date,startup,vertical,subvertical,city,investors,round,amount
Sr No,,,,,,,,
1,09/01/2020,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,"20,00,00,000"
2,13/01/2020,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,"80,48,394"
3,09/01/2020,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,"1,83,58,860"
4,02/01/2020,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,"30,00,000"
5,02/01/2020,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,"18,00,000"

In [15]:
# now covert the amount column to crore rupees from usd
fund.info()

<class 'pandas.DataFrame'>
RangeIndex: 3044 entries, 1 to 3044
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         3044 non-null   str
 1   startup      3044 non-null   str
 2   vertical     2873 non-null   str
 3   subvertical  2108 non-null   str
 4   city         2864 non-null   str
 5   investors    3044 non-null   str
 6   round        3040 non-null   str
 7   amount       2084 non-null   str
dtypes: str(8)
memory usage: 540.5 KB

In [16]:
fund[fund['amount'].isnull()]

,date,startup,vertical,subvertical,city,investors,round,amount
Sr No,,,,,,,,
145,01/10/2018,Northmist,Fashion,Mens Wear,Delhi,Prashant Jaiswal,Seed/ Angel Funding,NaN
156,04/09/2018,HappyGoEasy,Consumer Internet,Online Travel Agecy,Gurugram,"Korea Investment Partners (KIP), Samsung and C...",Private Equity,NaN
158,05/09/2018,Mad Street Den,Technology,Computer Vision And Artificial Intelligence (A...,Chennai,KDDI\\xc2\\xa0,Private Equity,NaN
166,01/08/2018,HealthFin,Finance,Patient Financing Platform,Pune,"Axilor, Sprout Venture Partners and others",Seed/ Angel Funding,NaN
190,01/07/2018,Leena AI,Technology,HR Virtual Agent For Employees,Gurugram,Y Combinator,Seed/ Angel Funding,NaN
...,...,...,...,...,...,...,...,...
3028,21/05/2015,Knit,NaN,NaN,NaN,"Rohit Jain, Amit Rambhia & Others",Seed Funding,NaN
3031,22/01/2015,Freshmonk,NaN,NaN,NaN,"August Capital Partners, Michael Blakey",Seed Funding,NaN
3032,22/01/2015,Englishleap.com,NaN,NaN,NaN,ANALEC,Private Equity,NaN
3036,24/01/2015,Impartus,NaN,NaN,NaN,Kaizen Private Equity,Private Equity,NaN
3043,30/01/2015,Simplotel,NaN,NaN,NaN,MakeMyTrip,Private Equity,NaN

In [17]:
fund['amount'].value_counts(dropna=False)

amount
NaN            960
10,00,000      165
5,00,000       108
20,00,000       69
30,00,000       66
              ...
1,35,000         1
2,85,000         1
30,768           1
1,47,50,000      1
32,50,000        1
Name: count, Length: 472, dtype: int64

In [18]:
# first in this amount column replace the missing values with 0
fund['amount'] = fund['amount'].fillna('0')

In [19]:
# replace the , with ''
fund['amount'] = fund['amount'].str.replace(',','')

In [20]:
fund[~fund['amount'].str.isdigit()]

,date,startup,vertical,subvertical,city,investors,round,amount
Sr No,,,,,,,,
21,17/11/2019,Burger Singh,Food and Beverage,Indian Burger Brand,Gurgaon,RB Investments,Venture,undisclosed
35,21/10/2019,The Man Company,Consumer Goods,Beauty and Grooming,Gurgaon,Ayushmann Khurana,Corporate Round,unknown
59,19/08/2019,Mishry Reviews,Services,Product Review,Gurgaon,Vir Sanghvi,Series A,Undisclosed
77,03/06/2019,FabHotels,E-Commerce,Hospitality,Gurgaon,"Goldman Sachs, Accel Partners and Qualcomm",NaN,4889975.54
82,06/06/2019,Sistema.bio,Agriculture,Hybrid Reactor Biodigestor,Nairobi,"Shell Foundation, DILA CAPITAL, Engie RDE Fund...",NaN,2739034.68
84,06/06/2019,Pratilipi,Digital Media,E-Books,Bengaluru,Qiming Venture Partners,Series B,15109500.00
90,06/05/2019,Ola Electric,Transport,Cabs,Bengaluru,Tata Sons,Series A,undisclosed
92,05/05/2019,StyleDotMe,E-commerce,Fashion and Shopping,Delhi,Indian Angel Network and other angel investors...,Bridge Round,undisclosed
110,19/04/2019,KrazyBee,E-commerce,Lending Platform,Bengaluru,"BAC Acquisitions, Unifi AIF, BRD Securities, N...",Debt,14342000+
113,01/02/2019,FleetX,AI,Logistics,Gurgaon,India Quotient and LetsVenture\\xe2\\x80\\x99s...,Pre Series A,Undisclosed
140,22/11/2018,Skillbox,Social Network,Art,Gurugram,Individual investors,Seed Funding,Undisclosed
2603,09/07/2015,\\xc2\\xa0News in shorts,\\xc2\\xa0News Aggregator mobile app,NaN,\\xc2\\xa0Noida,\\xc2\\xa0Tiger Global,Private Equity,\\xc2\\xa020000000
2604,09/07/2015,\\xc2\\xa0Bluestone,\\xc2\\xa0Online Jewellery Store,NaN,\\xc2\\xa0Bangalore,"\\xc2\\xa0IvyCap Ventures, Accel Partners, Dra...",Private Equity,\\xc2\\xa016200000
2605,09/07/2015,\\xc2\\xa0Shopsity,\\xc2\\xa0Fashion Info Aggregator App,NaN,\\xc2\\xa0Gurgaon,"\\xc2\\xa0 Sandeep Aggarwal, Teruhide Sato",Seed Funding,\\xc2\\xa0N/A
2606,09/07/2015,\\xc2\\xa0Notesgen,\\xc2\\xa0Online Study Notes Marketplace,NaN,\\xc2\\xa0New Delhi,"\\xc2\\xa0Rajeev Saraf, Arvind Jha, R. Satya N...",Seed Funding,\\xc2\\xa0N/A
2607,\\xc2\\xa010/7/2015,\\xc2\\xa0Infinity Assurance,\\xc2\\xa0Warranty Programs Service Administra...,NaN,\\xc2\\xa0New Delhi,\\xc2\\xa0Indian Angel Network,Seed Funding,\\xc2\\xa0600000
2608,10/07/2015,\\xc2\\xa0Footprints Education,\\xc2\\xa0Pre-School Chain,NaN,\\xc2\\xa0Gurgaon,"\\xc2\\xa0LetsVenture, Kumar Bansal, Kshitij Jain",Seed Funding,\\xc2\\xa0685000
2609,10/07/2015,\\xc2\\xa0Loylty Rewards,\\xc2\\xa0Premium Loyalty Rewards Point Manage...,NaN,\\xc2\\xa0Mumbai,\\xc2\\xa0IndianIdeas.com,Private Equity,\\xc2\\xa019350000
2610,13/07/2015,\\xc2\\xa0Ameyo,\\xc2\\xa0Contact Center Software Platform,NaN,\\xc2\\xa0Gurgaon,\\xc2\\xa0Forum Synergies PE Fund,Private Equity,\\xc2\\xa05000000
2611,13/07/2015,\\xc2\\xa0Mamagoto,\\xc2\\xa0Casual Dining restaurant Chain,NaN,\\xc2\\xa0New Delhi,\\xc2\\xa0Goldman Sachs,Private Equity,\\xc2\\xa010000000
2612,13/07/2015,\\xc2\\xa0Satvacart,\\xc2\\xa0Online Grocery Delivery,NaN,\\xc2\\xa0Gurgaon,\\xc2\\xa0Palaash Ventures,Seed Funding,\\xc2\\xa0N/A
2614,14/07/2015,Zenify,Residential Rental management platform,NaN,Bangalore,Atul Jalan,Seed Funding,\\xc2\\xa0N/A

In [21]:
fund['amount'] = fund['amount'].str.replace({'Undisclosed':'0','undisclosed':'0','unknown':'0'})

In [22]:
fund[~fund['amount'].str.isdigit()]

,date,startup,vertical,subvertical,city,investors,round,amount
Sr No,,,,,,,,
77,03/06/2019,FabHotels,E-Commerce,Hospitality,Gurgaon,"Goldman Sachs, Accel Partners and Qualcomm",NaN,4889975.54
82,06/06/2019,Sistema.bio,Agriculture,Hybrid Reactor Biodigestor,Nairobi,"Shell Foundation, DILA CAPITAL, Engie RDE Fund...",NaN,2739034.68
84,06/06/2019,Pratilipi,Digital Media,E-Books,Bengaluru,Qiming Venture Partners,Series B,15109500.00
110,19/04/2019,KrazyBee,E-commerce,Lending Platform,Bengaluru,"BAC Acquisitions, Unifi AIF, BRD Securities, N...",Debt,14342000+
2603,09/07/2015,\\xc2\\xa0News in shorts,\\xc2\\xa0News Aggregator mobile app,NaN,\\xc2\\xa0Noida,\\xc2\\xa0Tiger Global,Private Equity,\\xc2\\xa020000000
2604,09/07/2015,\\xc2\\xa0Bluestone,\\xc2\\xa0Online Jewellery Store,NaN,\\xc2\\xa0Bangalore,"\\xc2\\xa0IvyCap Ventures, Accel Partners, Dra...",Private Equity,\\xc2\\xa016200000
2605,09/07/2015,\\xc2\\xa0Shopsity,\\xc2\\xa0Fashion Info Aggregator App,NaN,\\xc2\\xa0Gurgaon,"\\xc2\\xa0 Sandeep Aggarwal, Teruhide Sato",Seed Funding,\\xc2\\xa0N/A
2606,09/07/2015,\\xc2\\xa0Notesgen,\\xc2\\xa0Online Study Notes Marketplace,NaN,\\xc2\\xa0New Delhi,"\\xc2\\xa0Rajeev Saraf, Arvind Jha, R. Satya N...",Seed Funding,\\xc2\\xa0N/A
2607,\\xc2\\xa010/7/2015,\\xc2\\xa0Infinity Assurance,\\xc2\\xa0Warranty Programs Service Administra...,NaN,\\xc2\\xa0New Delhi,\\xc2\\xa0Indian Angel Network,Seed Funding,\\xc2\\xa0600000
2608,10/07/2015,\\xc2\\xa0Footprints Education,\\xc2\\xa0Pre-School Chain,NaN,\\xc2\\xa0Gurgaon,"\\xc2\\xa0LetsVenture, Kumar Bansal, Kshitij Jain",Seed Funding,\\xc2\\xa0685000
2609,10/07/2015,\\xc2\\xa0Loylty Rewards,\\xc2\\xa0Premium Loyalty Rewards Point Manage...,NaN,\\xc2\\xa0Mumbai,\\xc2\\xa0IndianIdeas.com,Private Equity,\\xc2\\xa019350000
2610,13/07/2015,\\xc2\\xa0Ameyo,\\xc2\\xa0Contact Center Software Platform,NaN,\\xc2\\xa0Gurgaon,\\xc2\\xa0Forum Synergies PE Fund,Private Equity,\\xc2\\xa05000000
2611,13/07/2015,\\xc2\\xa0Mamagoto,\\xc2\\xa0Casual Dining restaurant Chain,NaN,\\xc2\\xa0New Delhi,\\xc2\\xa0Goldman Sachs,Private Equity,\\xc2\\xa010000000
2612,13/07/2015,\\xc2\\xa0Satvacart,\\xc2\\xa0Online Grocery Delivery,NaN,\\xc2\\xa0Gurgaon,\\xc2\\xa0Palaash Ventures,Seed Funding,\\xc2\\xa0N/A
2614,14/07/2015,Zenify,Residential Rental management platform,NaN,Bangalore,Atul Jalan,Seed Funding,\\xc2\\xa0N/A

In [23]:
fund['amount'] = fund['amount'].str.replace({'14342000+':'14342000'})

In [24]:
fund[~fund['amount'].str.isdigit()]

,date,startup,vertical,subvertical,city,investors,round,amount
Sr No,,,,,,,,
77,03/06/2019,FabHotels,E-Commerce,Hospitality,Gurgaon,"Goldman Sachs, Accel Partners and Qualcomm",NaN,4889975.54
82,06/06/2019,Sistema.bio,Agriculture,Hybrid Reactor Biodigestor,Nairobi,"Shell Foundation, DILA CAPITAL, Engie RDE Fund...",NaN,2739034.68
84,06/06/2019,Pratilipi,Digital Media,E-Books,Bengaluru,Qiming Venture Partners,Series B,15109500.00
2603,09/07/2015,\\xc2\\xa0News in shorts,\\xc2\\xa0News Aggregator mobile app,NaN,\\xc2\\xa0Noida,\\xc2\\xa0Tiger Global,Private Equity,\\xc2\\xa020000000
2604,09/07/2015,\\xc2\\xa0Bluestone,\\xc2\\xa0Online Jewellery Store,NaN,\\xc2\\xa0Bangalore,"\\xc2\\xa0IvyCap Ventures, Accel Partners, Dra...",Private Equity,\\xc2\\xa016200000
2605,09/07/2015,\\xc2\\xa0Shopsity,\\xc2\\xa0Fashion Info Aggregator App,NaN,\\xc2\\xa0Gurgaon,"\\xc2\\xa0 Sandeep Aggarwal, Teruhide Sato",Seed Funding,\\xc2\\xa0N/A
2606,09/07/2015,\\xc2\\xa0Notesgen,\\xc2\\xa0Online Study Notes Marketplace,NaN,\\xc2\\xa0New Delhi,"\\xc2\\xa0Rajeev Saraf, Arvind Jha, R. Satya N...",Seed Funding,\\xc2\\xa0N/A
2607,\\xc2\\xa010/7/2015,\\xc2\\xa0Infinity Assurance,\\xc2\\xa0Warranty Programs Service Administra...,NaN,\\xc2\\xa0New Delhi,\\xc2\\xa0Indian Angel Network,Seed Funding,\\xc2\\xa0600000
2608,10/07/2015,\\xc2\\xa0Footprints Education,\\xc2\\xa0Pre-School Chain,NaN,\\xc2\\xa0Gurgaon,"\\xc2\\xa0LetsVenture, Kumar Bansal, Kshitij Jain",Seed Funding,\\xc2\\xa0685000
2609,10/07/2015,\\xc2\\xa0Loylty Rewards,\\xc2\\xa0Premium Loyalty Rewards Point Manage...,NaN,\\xc2\\xa0Mumbai,\\xc2\\xa0IndianIdeas.com,Private Equity,\\xc2\\xa019350000
2610,13/07/2015,\\xc2\\xa0Ameyo,\\xc2\\xa0Contact Center Software Platform,NaN,\\xc2\\xa0Gurgaon,\\xc2\\xa0Forum Synergies PE Fund,Private Equity,\\xc2\\xa05000000
2611,13/07/2015,\\xc2\\xa0Mamagoto,\\xc2\\xa0Casual Dining restaurant Chain,NaN,\\xc2\\xa0New Delhi,\\xc2\\xa0Goldman Sachs,Private Equity,\\xc2\\xa010000000
2612,13/07/2015,\\xc2\\xa0Satvacart,\\xc2\\xa0Online Grocery Delivery,NaN,\\xc2\\xa0Gurgaon,\\xc2\\xa0Palaash Ventures,Seed Funding,\\xc2\\xa0N/A
2614,14/07/2015,Zenify,Residential Rental management platform,NaN,Bangalore,Atul Jalan,Seed Funding,\\xc2\\xa0N/A

In [25]:
# unit test
fund.loc[2604,'city'].replace('\\\\xc2\\\\xa0','')

'Bangalore'

In [26]:
# column test
fund['test_amount'] = fund['amount'].str.replace('\\\\xc2\\\\xa0','')

In [27]:
# test is successful
fund[~fund['test_amount'].str.isdigit()]

,date,startup,vertical,subvertical,city,investors,round,amount,test_amount
Sr No,,,,,,,,,
77,03/06/2019,FabHotels,E-Commerce,Hospitality,Gurgaon,"Goldman Sachs, Accel Partners and Qualcomm",NaN,4889975.54,4889975.54
82,06/06/2019,Sistema.bio,Agriculture,Hybrid Reactor Biodigestor,Nairobi,"Shell Foundation, DILA CAPITAL, Engie RDE Fund...",NaN,2739034.68,2739034.68
84,06/06/2019,Pratilipi,Digital Media,E-Books,Bengaluru,Qiming Venture Partners,Series B,15109500.00,15109500.00
2605,09/07/2015,\\xc2\\xa0Shopsity,\\xc2\\xa0Fashion Info Aggregator App,NaN,\\xc2\\xa0Gurgaon,"\\xc2\\xa0 Sandeep Aggarwal, Teruhide Sato",Seed Funding,\\xc2\\xa0N/A,N/A
2606,09/07/2015,\\xc2\\xa0Notesgen,\\xc2\\xa0Online Study Notes Marketplace,NaN,\\xc2\\xa0New Delhi,"\\xc2\\xa0Rajeev Saraf, Arvind Jha, R. Satya N...",Seed Funding,\\xc2\\xa0N/A,N/A
2612,13/07/2015,\\xc2\\xa0Satvacart,\\xc2\\xa0Online Grocery Delivery,NaN,\\xc2\\xa0Gurgaon,\\xc2\\xa0Palaash Ventures,Seed Funding,\\xc2\\xa0N/A,N/A
2614,14/07/2015,Zenify,Residential Rental management platform,NaN,Bangalore,Atul Jalan,Seed Funding,\\xc2\\xa0N/A,N/A

In [28]:
fund['amount'] = fund['test_amount']

In [29]:
# now convert the string values to float
fund['amount'] = pd.to_numeric(fund['amount'],errors='coerce')

In [30]:
fund['amount'].fillna(0,inplace=True)

/tmp/ipykernel_12927/979909202.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  fund['amount'].fillna(0,inplace=True)

Sr No
1       200000000.0
2         8048394.0
3        18358860.0
4         3000000.0
5         1800000.0
           ...
3040      4500000.0
3041       825000.0
3042      1500000.0
3043            0.0
3044       140000.0
Name: amount, Length: 3044, dtype: float64

In [34]:
# convert the amount in crore rupees
fund['amount'] = round(fund['amount'].apply(lambda x: ((x*95.67)/10000000)),2)

In [35]:
fund.head()

,date,startup,vertical,subvertical,city,investors,round,amount,test_amount
Sr No,,,,,,,,,
1,09/01/2020,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,1913.40,200000000
2,13/01/2020,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,77.00,8048394
3,09/01/2020,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,175.64,18358860
4,02/01/2020,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,28.70,3000000
5,02/01/2020,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,17.22,1800000

In [ ]:
# now convert the date column to datetime
fund['date'].isnull().sum()

np.int64(0)

In [54]:
fund['date'].sample(20)

Sr No
873     07/04/2017
2916    25/03/2015
982     29/03/2017
2023    07/01/2016
1609    15/06/2016
2098    29/01/2016
2849    22/04/2015
56      22/08/2019
2456    24/09/2015
767     21/06/2017
1841    07/03/2016
2639    23/07/2015
2005    01/01/2016
1570    02/06/2016
3017    19/01/2015
1542    15/07/2016
2930    30/03/2015
1596    11/06/2016
874     07/04/2017
2164    16/12/2015
Name: date, dtype: str

In [56]:
fund['test_date'] = pd.to_datetime(fund['date'],errors='coerce',format='%d/%m/%Y')

In [ ]:
temp_df = fund[fund['test_date'].isnull()]

,date,startup,vertical,subvertical,city,investors,round,amount,test_amount,test_date
Sr No,,,,,,,,,,
193,05/072018,Loan Tap,Consumer Internet,Online Lending Platform For Salaried Professio...,Mumbai,"Shunwei Capital, Tuscan Ventures, Ashish Goenk...",Private Equity,59.79,6250000,NaT
2572,01/07/015,HandyHome,Hyperlocal Electronics repair Service,NaN,Mumbai,"Bessemer Ventures, Kae Capital",Seed Funding,6.03,630000,NaT
2607,\\xc2\\xa010/7/2015,\\xc2\\xa0Infinity Assurance,\\xc2\\xa0Warranty Programs Service Administra...,NaN,\\xc2\\xa0New Delhi,\\xc2\\xa0Indian Angel Network,Seed Funding,5.74,600000,NaT
2776,12/05.2015,Mobiefit,Mobile Fitness App,NaN,Goa,Prototyze,Seed Funding,0.00,0,NaT
2777,12/05.2015,Plancess,Online Education Platform,NaN,Mumbai,"Rajendra Gogri,\\xc2\\xa0 Chandrakant Gogri",Seed Funding,19.13,2000000,NaT
2832,13/04.2015,The Porter,Logistics Tech,NaN,Mumbai,Kae Capital,Seed Funding,4.78,500000,NaT
3012,15/01.2015,Wishberry,NaN,NaN,NaN,"Rajan Anandan, Shankar Mahadevan, Deep Kalra &...",Seed Funding,6.22,650000,NaT
3030,22/01//2015,Corporate360,NaN,NaN,NaN,Group of Angel Investors,Seed Funding,1.91,200000,NaT

In [ ]:
# unit test
fund.loc[2832,'date'].replace('.','/')

'13/04/2015'

In [62]:
fund['date'] = fund['date'].str.replace('.','/')

In [68]:
fund[fund['test_date'].isnull()]

,date,startup,vertical,subvertical,city,investors,round,amount,test_amount,test_date
Sr No,,,,,,,,,,
193,05/07/2018,Loan Tap,Consumer Internet,Online Lending Platform For Salaried Professio...,Mumbai,"Shunwei Capital, Tuscan Ventures, Ashish Goenk...",Private Equity,59.79,6250000,NaT
2572,01/07/2015,HandyHome,Hyperlocal Electronics repair Service,NaN,Mumbai,"Bessemer Ventures, Kae Capital",Seed Funding,6.03,630000,NaT
2607,10/7/2015,\\xc2\\xa0Infinity Assurance,\\xc2\\xa0Warranty Programs Service Administra...,NaN,\\xc2\\xa0New Delhi,\\xc2\\xa0Indian Angel Network,Seed Funding,5.74,600000,NaT
2776,12/05/2015,Mobiefit,Mobile Fitness App,NaN,Goa,Prototyze,Seed Funding,0.00,0,NaT
2777,12/05/2015,Plancess,Online Education Platform,NaN,Mumbai,"Rajendra Gogri,\\xc2\\xa0 Chandrakant Gogri",Seed Funding,19.13,2000000,NaT
2832,13/04/2015,The Porter,Logistics Tech,NaN,Mumbai,Kae Capital,Seed Funding,4.78,500000,NaT
3012,15/01/2015,Wishberry,NaN,NaN,NaN,"Rajan Anandan, Shankar Mahadevan, Deep Kalra &...",Seed Funding,6.22,650000,NaT
3030,22/01/2015,Corporate360,NaN,NaN,NaN,Group of Angel Investors,Seed Funding,1.91,200000,NaT

In [65]:
fund.loc[3030,'date'] = '22/01/2015'
fund.loc[2572,'date'] = '01/07/2015'
fund.loc[193,'date'] = '05/07/2018'

In [67]:
fund['date'] = fund['date'].str.replace('\\\\xc2\\\\xa0','')

In [ ]:
# now convert the date column
fund['date'] = pd.to_datetime(fund['date'],errors='coerce',format='%d/%m/%Y')

In [74]:
fund.head()

,date,startup,vertical,subvertical,city,investors,round,amount
Sr No,,,,,,,,
1,2020-01-09,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,1913.40
2,2020-01-13,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,77.00
3,2020-01-09,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,175.64
4,2020-01-02,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,28.70
5,2020-01-02,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,17.22

In [73]:
fund.drop(columns=['test_amount','test_date'],inplace=True)