In [1]:
import pandas as pd
import numpy as np

In [2]:
fund = pd.read_csv(r"/home/nivesh/startup_funding_project_streamlit/data/startup_funding.csv")
fund.head()

,Sr No,Date dd/mm/yyyy,Startup Name,Industry Vertical,SubVertical,City Location,Investors Name,InvestmentnType,Amount in USD,Remarks
0,1,09/01/2020,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,"20,00,00,000",NaN
1,2,13/01/2020,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,"80,48,394",NaN
2,3,09/01/2020,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,"1,83,58,860",NaN
3,4,02/01/2020,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,"30,00,000",NaN
4,5,02/01/2020,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,"18,00,000",NaN

In [3]:
sorted(fund['Startup Name'].unique().tolist())

['"BYJU\\\\\'S"',
 '#Fame',
 '121Policy',
 '19th mile',
 '1Crowd',
 '1mg',
 '1mg (Healthkartplus)',
 '20Dresses',
 '33Coupons',
 '360Ride',
 '3Dexter',
 '3HCare',
 '3rdFlix',
 '48East',
 '4tigo',
 '5th Vital',
 '6Degree',
 '75F',
 '91SpringBoard',
 '99Games',
 '99PerHour',
 '9Stacks',
 'A&R Bon Vivants',
 'ABI Health',
 'AEON Learning',
 'AHA Taxis',
 'AYE Finance',
 'AadharAPI.com',
 'Aadyah',
 'Aahaa',
 'Aahaa Stores',
 'Aarav UAV',
 'Aasaanjobs',
 'Aashiyaan',
 'Aavishkaar-Intellecap Group',
 'AbeRuk',
 'Abhibus',
 'Absentia',
 'Absentia VR',
 'Ace Turtle',
 'Ace2three',
 'Acko',
 'ActOnMagic',
 'Actionable Analytics',
 'Active AI',
 'Active.ai',
 'Actofit',
 'Ad2pro',
 'AdPushUp',
 'AdStringO',
 'AdUrCup',
 'AdWyze',
 'Address Health',
 'AdmitKard',
 'Advanced Structures India',
 'Advantage Club',
 'Advenio',
 'Adytude',
 'Aequm',
 'AerMed',
 'Affimity',
 'Affordplan',
 'Agara Labs',
 'AgentDesks',
 'Agricxlab',
 'Agrostar',
 'Agrowave',
 'AirCTO',
 'AirMed Labs',
 'AirZaar',
 'Airpay',
 'Airwood',
 'Aisle',
 'Aisle.co',
 'Akosha',
 'Alef\\\\nMobitech',
 'AllIzHealth',
 'Allygrow Technologies',
 'AlmaConnect',
 'AlmaMapper',
 'Alpha Capital',
 'Alteria Capital',
 'Alternacare',
 'Altizone',
 'Amagi Media Labs',
 'Ambee',
 'American Vision',
 'Amigobulls',
 'Ampere',
 'Ampere Vehicles',
 'Anakage',
 'Anandakanda',
 'Anchanto',
 'Annapurna Finance',
 'Antuit',
 'AppBrowzer',
 'AppDaily',
 'AppLop',
 'AppVirality',
 'Appario Retail Pvt Ltd.',
 'Appbase',
 'Appedo',
 'Appie',
 'AppilyEver',
 'Appknox',
 'Applicate',
 'Applied Solar Technologies',
 'Applop',
 'AppsDaily',
 'Appsdaily',
 'Appvigil',
 'Arcatron',
 'Arcatron Mobility',
 'Ark Robot',
 'Arkin Net',
 'Arohan Financial Services',
 'Arth DesignBuild',
 'Artoo',
 'Arya.ai',
 'Aryaka',
 'Asia Institute Of Medical Science',
 'AskMyGift',
 'Asocon',
 'Ather Energy',
 'Athletto',
 'Atlan',
 'Atomberg',
 'Atomberg Technology',
 'Attune Technologies',
 'Augrav',
 'AutoGrid',
 'AutoSense',
 'Autobix',
 'Automation Anywhere',
 'Autorox.co',
 'Avagmah',
 'Avail Finance',
 'AvailFinance',
 'Avanti Learning',
 'Avenue Growth',
 'Avishkaar Box',
 'Awaaz De',
 'Awesummly',
 'Awfis',
 'Awign',
 'Axio',
 'Axtria',
 'Aye Finance',
 'AyeFinance',
 'Azah',
 'Azuro',
 'B9 Beverages',
 'BHIVE',
 'BHIVE Workspace',
 'BRIDGEi2I',
 'BYG',
 'BYJU\\\\xe2\\\\x80\\\\x99s',
 'BYJU’S',
 'Babajobs',
 'Baby Berry',
 'BabyChakra',
 'Babychakra',
 'Babygogo',
 'BabyonBoard',
 'Badiyajobs',
 'BaggOut',
 'Balance App',
 'Banihal',
 'Bank Bazaar',
 'BankBazaar',
 'BankerBay',
 'Bats on delivery',
 'Baxi',
 'Be U Salons',
 'BeaconsTalk',
 'Beardo',
 'BeatRoute',
 'BedBathMore',
 'Belita',
 'Belong',
 'Benepik',
 'Bestdealfinance',
 'BetaOut',
 'Betaout',
 'Better Mortgage',
 'BetterButter.in',
 'BetterPlace',
 'Betterplace',
 'Bevy',
 'Bewakoof',
 'Beyond Evolution',
 'Bharat Bazaar',
 'BharatPe',
 'BhiveWorkspace',
 'BiBox',
 'Bidgely',
 'Big Basket',
 'Big Fish Ventures',
 'BigBasket',
 'BigStylist',
 'BigStylist.com',
 'Bikxie',
 'BillDesk',
 'Billion Loans',
 'Bira91',
 'Biryani Blues',
 'Biryani By Kilo',
 'BitGiving',
 'Bite Club',
 'Biteclub',
 'Bitla Software',
 'Biz2Credit',
 'Bizom',
 'Bizongo',
 'Black Soil',
 'Black White Orange',
 'Black White Orange Brands',
 'BlackBuck',
 'Blackbuck',
 'Blinge',
 'BlogBeats',
 'Blood n Care',
 'Blowhorn',
 'Blubox',
 'Blue Box Media',
 'Blue Tokai Coffee',
 'BlueStone',
 'Bluebirch',
 'Bluegape',
 'Bluegape.com',
 'Board Infinity',
 'Bobble',
 'BoiBanit',
 'BolRealty',
 'Bollant Industries',
 'Bolo App',
 'Bombay Shaving Company',
 'Bombay Shirt Company',
 'Bona Vita',
 'Bonhomia',
 'Bonphulapl',
 'Book My Diamond',
 'Book My Show',
 'Book Servicing',
 'BookEventz',
 'BookMeIn',
 'BookMyBai',
 'BookMyShow',
 'Bottr.me',
 'Bounty App',
 'Box My Space',
 'Box8',
 'Boxmyspace',
 'Boxx.ai',
 'Brick2Wall',
 'Brigge',
 'Briston Technomach',
 'Bro4U',
 'BroEx',
 'Broomberg',
 'Browntape',
 'BrowserStack',
 'Bucker',
 'Buddy',
 'Buddy4studdy',
 'Bueno',
 'BuildSupply',
 'BuildTraders',
 'Buildkar',
 'Buildzar',
 'Bumper',
 'Burger Singh',
 'Buttercups',
 'Butterfly Interactive',
 'BuyHatke',
 'Byju\\\\xe2\\\\x80\\\\x99s',
 'CAKART.in',
 'CBREX',
 'CBS',
 'CCAvenue',
 'CCavenue',
 'CREO',
 'CRON Systems',
 'CaRPM',
 'Cabsguru',
 'Call Health',
 'Campus Diaries',
 'CanvasFlip',
 'Canvera',
 'Canvs',
 'Capabiliti',
 'Capillary',
 'Capillary Tech',
 'Capita World',
 'Capital Float',
 'Capricoast',
 'Capzest',
 'CarDekho',
 'CarDekho.com',
 'CarTrade',
 'CarTrade.com',
 'Caratlane.com',
 'Caravan Craft',
 'Caravan Craft Retail',
 'Carcrew.in',
 'Care24',
 'Career Anna',
 'Career360',
 'CareonGO',
 'Careongo',
 'Carl\\\\xe2\\\\x80\\\\x99s Jr',
 'Cars24',
 'Cartisan',
 'Cartrade',
 'CarveNiche',
 'Casa2inns',
 'Cash Suvidha',
 'CashFree',
 'Cashe',
 'Cashflo',
 'Cashify',
 'Cashkaro',
 'Cashkaro.com',
 'Cashkumar',
 'Celerix',
 'Celes Care',
 'Cerebroz',
 'Chaayos',
 'Chai Point',
 'Chai Thela',
 'ChaiPoint',
 'Chakr Innovation',
 'Changer Mints',
 'ChargeBee',
 'Chargebee',
 'Chargein',
 'ChatOnGo',
 'CheersOye!',
 'Chefs Basket',
 'Chevon',
 'Chikoop',
 'Chillr',
 'ChipperSage',
 'Chloroplast Foods',
 'ChqBook',
 'Chrysalis',
 'Chumbak',
 'Chymera VR',
 'CimplyFive',
 'Citrus Payment',
 'CityFlo',
 'CityFurnish',
 'CityShor',
 'Civilsdaily',
 'Clapsnslaps',
 'CleanseCar',
 'ClearTax',
 'Cleartax',
 'Cleartrip',
 'CleverSharks',
 'CleverTap',
 'Click2Clinic',
 'Clip App',
 'Clodura',
 'Clonect Solutions',
 'Cloud Lending',
 'Cloudacar',
 'Cloudcherry Analytics',
 'Cloudrino',
 'Clovia',
 'Clumio',
 'Co Life',
 'Codemojo',
 'CodingLabs',
 'CoinTribe',
 'CollPoll',
 'CollateBox',
 'Collateral Medical',
 'Collectabillia',
 'CollegeDekho',
 'CollegeDunia',
 'Comarete',
 'Commeasure',
 'Commonfloor',
 'Commut',
 'ConfirmTKT',
 'ConfirmtTkt',
 'Connaizen',
 'Connect India',
 'ConnectAbank',
 'Consure Medical',
 'Convegenius',
 'Cooey',
 'Cookaroo',
 'Cookifi',
 'Coolshare',
 'Coppre',
 'Corporate360',
 'Corseco',
 'CouponRaja',
 'CoutLoot',
 'Coutloot',
 'CoveIoT',
 'CoverFox',
 'Coverfox',
 'CraftsVilla',
 'Craftstvilla',
 'Craftsvilla',
 'Crayon Data',
 'Creator\\\\xe2\\\\x80\\\\x99s Gurukul',
 'CredR',
 'CrediHealth',
 'Credifiable',
 'Credihealth',
 'Credit Mate',
 'Credit Sudhaar',
 'Credit Vidya',
 'CreditMantri',
 'CreditMate',
 'CreditSeva',
 'CreditVidya',
 'Credright',
 'Credy',
 'CroFarm',
 'Crofarm',
 'CropIn',
 'Cropin',
 'Crossahead',
 'Crowdera',
 'Crowdfire (formerly Justunfollow)',
 'Crown-it',
 'CrownIt',
 'Crownit',
 'Cube Consumer Services',
 'Cube26',
 'Cuberoot',
 'Cubito',
 'CueMath',
 'Cuelearn',
 'Cult',
 'Cult Fitness',
 'Culture Machine',
 'CultureAlley',
 'Cupick',
 'CupoNation',
 'Curatio',
 'Cure Fit',
 'CureFit',
 'CureInstant',
 'CureJoy',
 'Curefit',
 'Curie Labs',
 'Curiositi',
 'Curofy',
 'CustomFurnish.com',
 'Customer360',
 'CustomerSucessBox',
 'Customfurnish',
 'Cyclops',
 'CyclopsMedtech',
 'Cygnus Hospitals',
 'DAAKI',
 'Daalchini Technologies',
 'Daily Ninja',
 'Daily Rounds',
 'Daily hunt',
 'DailyHunt',
 'DailyNinja',
 'DailyObjects',
 'DailyRounds',
 'DarwinBox',
 'Data Resolve',
 'DataWeave',
 'DawaiLelo',
 'DayBox',
 'Dazo',
 'Deal 4Loans',
 'Deal Street Asia',
 'Deal4Loans / Wishfin',
 'Dealwithus',
 'Dekkho',
 'Delhivery',
 'Delight Foods',
 'Demyto',
 'Derbii',
 'Design Cafe',
 'DesignBids',
 'Devourin',
 'Deyor Camps',
 'Deyor Rooms',
 'Dhruva',
 'Dhruva Space',
 'DiabetOmics',
 'Didi',
 'Digiconectt',
 'Digilend',
 'Digio',
 'Digit',
 'Digital F5',
 'Digital Gorkha',
 'Digital Mall Asia',
 'Dil Mil',
 'Dipper',
 'Direct Create',
 'Diro Labs',
 'DishCo',
 'Disprz',
 'Djubo.com',
 'DoSelect',
 'DocPlexus',
 'DocTalk',
 'DocsApp',
 'Doctor Insta',
 'DoctorInsta',
 'DogSpot',
 'Don\\\\xe2\\\\x80\\\\x99t Scratch Your Head',
 'DoneThing',
 'DoodhWala',
 'Doormint',
 'Doxper',
 'Dream Wallets',
 'Dream11',
 'Drip capital',
 'DriveSkool',
 'DriveU',
 'DriversCart',
 'Drivestream',
 'Drivezy',
 'Drivify',
 'DrivoJoy',
 'Droom',
 'Droom.in',
 'DropKaffe',
 'Dropkaffe',
 'Drums Food',
 'Druva',
 'Duffl',
 'Dunzo',
 'EPS',
 'EPayLater',
 'ERA',
 'Early Salary',
 'EarlySalary',
 'EarlySalary.com',
 'Earth Food',
 'Easy Diner',
 'EasyEcom',
 'EasyFix',
 'EasyGov',
 'EasyKhaana',
 'EasyPolicy',
 'EasyRewardz',
 'EasyRoads',
 'Easypolicy',
 'Eat.Shop.Love',
 'Eatfresh',
 'Eatlo',
 'Eatonomist',
 'Eattreatonline',
 'Eazy Coach',
 'EazyDiner',
 'Eckovation',
 'Ecolibriumenergy',
 'Ecom Express',
 'Ecozen',
 'EdTechReview',
 'Edelweiss',
 'EdgeFx',
 'Edu4Share',
 'EduAce Services',
 'EduBridge',
 'EduKart',
 'EduPristine',
 'EduRev',
 'Edureka',
 'Edurev',
 'Edyoo',
 'Elanic',
 'ElastiRun',
 'ElasticRun',
 'ElderAid Wellness',
 'Elemential',
 'Elucidata',
 'Emflux Motors',
 'Emiza',
 'Emojifi',
 'Enabli',
 'Enakshi',
 'Endless Robotics',
 'Engineer.ai',
 'EngineerBabu',
 'Englishleap.com',
 'Entropik',
 'Entropika',
 'Entropy Innovations',
 'Envoged',
 'Epiq Capital',
 'Eruditus',
 'Ethinos',
 'Ethosh',
 'EureQa',
 'EvenGini',
 'EveningFlavors',
 'Events High',
 'Explara',
 'Explore Life traveling',
 'ExtraCarbon',
 'ExtraaEdge',
 'Eywa Media',
 'EzCred',
 'Ezetap',
 'EzySolare',
 'Ezyhaul',
 'Ezytruk',
 'FPL Technologies',
 'FR8',
 'FTCash',
 'FXMartIndia',
 'FYNE',
 'FYRE',
 'Faaso\\\\xe2\\\\x80\\\\x99s',
 'Faasos',
 'Faaya',
 'Fab Hotels',
 'FabAlley',
 'FabHotels',
 'FabX',
 'FableStreet',
 'Fabogo',
 'Fabulyst',
 'Faircent',
 'Faircent.com',
 'FalconBrick',
 'FarEye',
 'FarMart',
 'Farm Taaza',
 'FarmLink',
 'Farmizen',
 'Fashalot',
 'Fashionablyin',
 'Fashionove',
 'Fashor',
 'FastFox',
 'Fastudent',
 'FeetApart',
 'FiTraQ',
 'Fieldassist',
 'Finance Buddha',
 'Fincash',
 'Find My Stay',
 'FindUrClass',
 'FindYahan',
 'FindmeaShoe',
 'Findow',
 'Findyahan',
 'Fingerlix',
 'Finomena',
 'Finova Capital',
 'Fintellix',
 'Fintobox',
 'Finzy',
 'First Eat',
 'First Moms Club',
 'FirstCry',
 'FirstCry.com',
 'FirstTouch',
 'Fisdom',
 'FitMeIn',
 'Fitcircle',
 'Fitmein',
 'Fitnapp',
 'Fitpass',
 'Fitraq.com',
 'Fitso',
 'Fitternity',
 'Five Star Group',
 'FixNix',
 'Fixy',
 'Flashdoor',
 'FlatFurnish',
 'Flatchat',
 'Flatpebble',
 'FleetRover',
 'FleetX',
 'Flexiloans',
 'Flexing It',
 'FlickBay',
 'Flickstree',
 'FlipClass',
 'Flipkart',
 'Flipkart.com',
 'Flixy Games',
 'Flocareer',
 'Flochat',
 'Flutura',
 'Flyrobe',
 'Flytxt',
 'Focus Digit',
 'FoodAbhi',
 'FoodTalkIndia',
 'Foodmemories',
 'Foodpanda',
 'ForeverShop',
 'Formcept',
 'Fourseven',
 'Fourth Ambit',
 'Fourth Partner Energy',
 'Foyr.com',
 'Fracktal Works',
 'Fractal Analytics',
 'Frankly',
 'Frapperz',
 'FreeCharge',
 'Freedom Smart Labs',
 'Fresh Food Concepts',
 'FreshBoxx',
 'FreshDesk',
 'FreshMenu',
 'FreshVnF',
 'FreshWorld',
 'Freshboxx',
 'Freshdesk',
 'Freshee',
 'Freshmonk',
 'Freshworks',
 'Front Desk AI',
 'FroyoFit',
 'Frsh',
 'Frsh.co.in',
 'Ftcash',
 'Fulfil.IO',
 'FunOnGo',
 'Funcart',
 'Funcastic',
 'Fundamentor',
 'FundsIndia.com',
 'Furdo',
 'Furlenco',
 'Furtados School of Music',
 'Fusion Microfinance',
 'Fxkart.com',
 'Fyle',
 'Fyle Technologies',
 'Fynd',
 'GIBBS',
 'GIBSS',
 'GOQii',
 'Gaana',
 'Gaana.com',
 'Gadgets 360',
 'Gadgetwood',
 'Gajty',
 'Galleri5',
 'GameXS.in',
 'GameZop',
 'Gameezop',
 'Gaming Monk',
 'Gamooz',
 'Gapoon',
 'Garage On Road',
 'GenNext Students',
 'Genextstudents',
 'Genie',
 'Genius Corner',
 'Get My Parking',
 'Get Simpl',
 'GetFocus',
 'GetMyPeon',
 'GetVee',
 'Giftxoxo',
 'GigIndia',
 'Gingercrush',
 'Girnar Software',
 'Glam Studios',
 'GlamStudios',
 'Glamrs',
 'Glassic',
 'GlowRoad',
 'Glowroad',
 'Glowship',
 'GoBumpr',
 'GoChoppers',
 'GoComet',
 'GoDesi',
 'GoFro',
 'GoFynd',
 'GoGo Truck',
 'GoJavas',
 'GoMechanic',
 'GoPigeon',
 'GoQii',
 'GoYaNo',
 'GoZefo',
 'Goalwise',
 'Gobolt',
 'Godof Hospitals',
 'GoldFarm',
 'GolfLAN',
 'Gomalon',
 'Good Methods Global',
 'Goodbox',
 'Goodera',
 'Goodservice',
 'Goomo',
 'Goqii',
 'Gozoomo',
 'Grab',
 'Grab.in',
 'GrabOnRent',
 'Grabhouse',
 'Grabhouse.com',
 'Gradopedia',
 'GramCover',
 'Gramophone',
 'GrandOpinion',
 'Graphene',
 'Graphic India',
 'Gray Routes',
 'Greenlight Planet',
 'Grex',
 'Grey Campus',
 'Grey Orange',
 'GreyAtom',
 'GreytHR',
 'Gridle',
 'Grofers',
 'Groupon India',
 'Grover Zampa',
 'Grow Fit',
 'GrowFitter',
 'Groww',
 'Guarented',
 'Guiddoo',
 'Guidoo',
 'GuruG Learning',
 'Gurukul',
 'Gyaanzone',
 'GyanDhan',
 'GymTrekker',
 'Gympik',
 'Gympik.com',
 'HEAL Institute',
 'HUG Innovations',
 'HWell24',
 'HWell24 Plus',
 'HackerEarth',
 'HackerRank',
 'HalaPlay',
 'HandyHome',
 'HandyTrain',
 'Hansa Customer Equity',
 'Hansel io',
 'Hansel.io',
 'Happily Unmarried',
 'HappilyUnmarried',
 'Happitoo',
 'Happy EMI',
 'Happy2Refer',
 'HappyGoEasy',
 'Happydemic',
 'Haptik',
 'Haqdarshak',
 'Harness Handitouch',
 'HashLearn',
 'HashTaag',
 'Hasura',
 'HeadOut',
 'Heads Up For Tails',
 'Healers At Home',
 'HealthAssure',
 'HealthCare',
 'HealthEminds',
 'HealthEnablr',
 'HealthFin',
 'HealthIntel',
 'HealthKart',
 'HealthKumbh',
 'HealthMir',
 'HealthSutra',
 'Healthbuds',
 'Healthcare at Home',
 'Healthi',
 'Healthians',
 'Healthians.com',
 'HealthifyMe',
 'Healthifyme',
 'Healthsignz',
 'HealthyWorld.in',
 'Heckyl',
 'Hello Curry',
 'Hello Tax',
 'HelpChat',
 'HelpShift',
 'Helpi',
 'Heterogenous',
 'Hevo Data',
 'HeyBiz',
 'HeyPillow',
 'HiJinny',
 'High Radius',
 'HighRadius',
 'Highway Delite',
 'Hike',
 'Hike Messenger',
 'HipBar',
 'HipCouch',
 'Hipcask',
 'Hippily',
 'Hipship',
 'HitGrit',
 'Hitwicket',
 'HolaChef',
 'Holachef',
 'HolidayIQ',
 'Holidify',
 'Holisol Logistics',
 'HomeCapital',
 'HomeLane',
 'HomeStudio',
 'Homelane',
 'Homergize',
 'Homers.in',
 'Hoopy',
 'Hopping Chef',
 'Hoppingo',
 'Hopscotch',
 'Horntell',
 'Hostel Dunia',
 'Hotelogix',
 'Hotify',
 'House of Msasaba',
 'Housejoy',
 'Housing',
 'Housing.com',
 'HousingMan',
 'Houssup',
 'Howdy Ventures',
 'Hubilo',
 'Hugefly',
 'Hungama',
 'HungerBox',
 'Hungry Foal',
 'HyperTrack',
 'HyperVerge',
 'Hypernova Interactive',
 'I Can Stay',
 'IBSFintech',
 'ICHR',
 'ICustomMadeIt',
 'IDG Ventures',
 'IDfy',
 'IFMR Holdings',
 'IGP.com',
 'IIM Jobs',
 'IMAX Program',
 'IMbesharam',
 'INDwealth',
 'ION Energy',
 'IOTrek',
 'IQlect',
 'ISFC',
 'Icertis',
 'Idea Bubbles',
 'IdeaChakki',
 'IdeaForge',
 'Ideal Insurance',
 'Ignis Careers',
 'ImageProVision',
 'Imaginate',
 'Imarticus Learning',
 'Impact Analytics',
 'Impact Guru',
 'ImpactGuru',
 'Impartus',
 'InCred',
 'InCred Finance',
 'Inayo',
 'Inc42',
 'Inclov',
 'Increff',
 'Indee',
 'Indi.com',
 'India Gifts Portal',
 'India Lends',
 'IndiaLends',
 'Indiamart',
 'IndianRoots.com',
 'Indiez',
 'Indifi',
 'IndigoLearn',
 'Indix',
 'Indofash',
 'Indus OS',
 'IndustryBuying',
 'Industrybuying',
 'Infibeam',
 'Infinite Analytics',
 'Infisecure',
 'Infogain',
 'Infoworks',
 ...]

In [4]:
fund.info()

<class 'pandas.DataFrame'>
RangeIndex: 3044 entries, 0 to 3043
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Sr No              3044 non-null   int64
 1   Date dd/mm/yyyy    3044 non-null   str
 2   Startup Name       3044 non-null   str
 3   Industry Vertical  2873 non-null   str
 4   SubVertical        2108 non-null   str
 5   City  Location     2864 non-null   str
 6   Investors Name     3020 non-null   str
 7   InvestmentnType    3040 non-null   str
 8   Amount in USD      2084 non-null   str
 9   Remarks            419 non-null    str
dtypes: int64(1), str(9)
memory usage: 593.3 KB

In [5]:
# there are missing values in investor name
# replace the missing values with undisclosed 
fund['Investors Name'] = fund['Investors Name'].fillna('Undisclosed')
sorted(fund['Investors Name'].unique().tolist())

['"Kedaraa Capital, Ontario Teachers\\\\\'"',
 '021 Capita, Binny Bansal',
 '1Crowd',
 '1Crowd (through crowd funding)',
 '1Crowd (through crowdfunding)',
 '1Crowd, Ankur Capital',
 '1Crowd, Eureka Forbes Ltd, Shapoorji Pallonji & Co. Ltd.',
 '3 undisclosed HNIs',
 '3 undisclosed investors',
 '3One4 Capital',
 '3one4 Capital, Mumbai Angels, Aarin Capital',
 '3one4 Capital, Tracxn Labs, Aaruha Technology Fund, Endiya Partners',
 '3one4 capital',
 '500 Startups',
 '500 Startups, IDG Ventures & Advantedge fund, Neeraj Arora, Leon Seynave',
 '500 Startups, IvyCap Ventures',
 '500 Startups, Littlerock, Singularity Ventures',
 '500 Startups, Mato Peric & Others',
 '500 Startups, Mato Peric, TracxnLabs',
 '500 Startups, Purvi Capital, Rajan Anandan, Abhishek Gupta',
 '500 Startups, Smile Multimedia, Kunal Bahl, Rohit Bansal, Girish Matrubootham',
 '500 Startups, TV Mohandas Pai, Tandem Capital, Vikram Chachra, Aloke Bajpai',
 '50K Ventures',
 '50k Ventures, Munish Jauhar, Pulkit Jain, Rohit Narang',
 '91maker.com',
 'A M Sikander',
 'A91 Partners',
 'AB Kinnevik, Falcon Edge Capital, Coatue Management',
 'ABI-Showatech (India) Ltd',
 'ABM Knowledgeware',
 'ADAG Reliance Private Equity',
 'AJ Ventures and Jain International Trade Organisation (JITO)',
 'ANALEC',
 'ANI Technologies Pvt. Ltd',
 'APIS Partners',
 'ASK Pravi',
 'AV Thomas Group',
 'AVG Group, 500 Startups',
 'Aakrit Vaish, Swapan Rajdev, Sushill Jiwarajka',
 'Aamir Khan',
 'Aarin Capital',
 'Aarin Capital Partners',
 'Aarin Capital Partners,',
 'Aarin Capital Partners, TV Mohandas Pai',
 'Aarin Capital, Michael Herzig, Ashish Lakhanpal',
 'Aarin Capital, Unitus Seed Fund',
 'Aarti Group',
 'Aavishkaar',
 'Aavishkaar Venture Management',
 'Aavya Ventures',
 'Abhijit Avasthi, Karan Chellani, SP Vijay',
 'Abhinav Bindra, Gaurav Marya',
 'Abhinav Gupta,',
 'Abhinav Mathur',
 'Abhishek Agarwal, Krishnakumar Nataraj, Sarath Sura, Shanti Mohan, Sarthak and Nihit Agarwal, Suramya Gupta',
 'Abhishek Bhatewara, Vivek Shah, Haitong Securities, Suraj Saharan, Paras Arora',
 'Abhishek Gupta',
 'Abraaj Group',
 'Accel (formerly known as Accel Partners)',
 'Accel Partner, Jungle Ventures',
 'Accel Partners',
 'Accel Partners India',
 'Accel Partners India, RB Investments',
 'Accel Partners,',
 'Accel Partners, Anupam Mittal & other marquee investors',
 'Accel Partners, Ashish Hemrajani, Parikshit Dar, Rajesh Balpande',
 'Accel Partners, Beenext, Powerhouse Ventures, Akusa Holdings',
 'Accel Partners, Deep Kalra, Rajesh Magow, Mohit Gupta, Shamik Sharma',
 'Accel Partners, Elevar Equity, Pramod Bhasin, Rajan Anandan, Gaurav Dalmia, Abhishek Goyal, Gagan Hasteer , Arun Tadanki',
 'Accel Partners, Exfinity Ventures, Partech Ventures',
 'Accel Partners, Flipkart',
 'Accel Partners, Helion Venture Partners',
 'Accel Partners, IDG Venture, Endiya Partners, pi Ventures, VH Capital, Axilor Ventures and Binny Bansal',
 'Accel Partners, IDG Ventures India',
 'Accel Partners, IDG Ventures, Endiya Partners, pi Ventures, VH Capital, Axilor Partners',
 'Accel Partners, IDG Ventures, Kalaari Capital',
 'Accel Partners, IDG Ventures, Kalaari Capital,\\\\xc2\\\\xa0 UC-RNT fund',
 'Accel Partners, Indian Angel Network, India Innovation Fund India Venture Partners',
 'Accel Partners, International Finance Corporation (IFC), Qualcomm Ventures, Ventureast',
 'Accel Partners, Jungle Ventures, SeedPlus',
 'Accel Partners, Kalaari Capital',
 'Accel Partners, Matrix Partners, Girish Mathrubootham',
 'Accel Partners, Nandan Nilekani,',
 'Accel Partners, Nandan Nilekani\\\\xe2\\\\x80\\\\x99s NRJN Trust, Mistletoe, Qualcomm Ventures, M&S Partners',
 'Accel Partners, Qualcomm Ventures, M&S Partners, Zop Smart',
 'Accel Partners, RB Investments',
 'Accel Partners, SAIF Partners',
 'Accel Partners, Sequoia Capital',
 'Accel Partners, Sequoia Capital, RB Investments',
 'Accel Partners, Sequoia India, Y Combinator and others.',
 'Accel Partners, Shunwei Capital',
 'Accel Partners, Subrata Mitra, Larry Braitman, Venk Krishna',
 'Accel Partners, Tiger Global And Others',
 'Accel Partners, Tiger Global Management',
 'Accel Partners, Traxcn Labs & Others',
 'Accel Partners, Zephyr Peacock',
 'Accel US, Accel India, SAIF Partners.',
 'Accion Venture Lab, Unicorn India Ventures and ISME ACE.',
 'Accion Venture Lab, YourNest Venture Capital And Other Angel Investors',
 'Accion Venture Labs, Rianta Capital',
 'Accion, LeapFrog Investments, Lok Capital',
 'Ackermans & van Haaren, HealthQuad, Rebright Partners, Toppan Printing',
 'Actis, Altimeter Capital',
 'Acumen Fund',
 'Adroitent Pvt. Ltd.',
 'AdvantEdge',
 'Aegon NV',
 'Aequs Group',
 'Agarwal Movers Group',
 'Agnus Capital',
 'Agnus Capital, Khattar Holdings',
 'Ah! Ventures, Calcutta Angels,\\\\xc2\\\\xa0 91SpringBoard',
 'Ajai Chowdhry, Ashvin Chadha, Yogesh Bansal,\\\\nNitin Singhal & Others',
 'Ajay Data & other HNIs',
 'Ajay Data & undisclosed HNIs',
 'Ajay Nanavati, Afsal Salu',
 'Ajay Piramal',
 'Ajay Relan',
 'Ajay Relan and Vinay Mittal',
 'Ajay Relan,',
 'Ajay Relan, LetsVenture',
 'Ajeet Khurana & Others',
 'Ajeet Khurana Jinesh Shah, Vikram Chachra, Dr. Aniruddha Malpani',
 'Ajit Surana, Sanjay Mehta',
 'Ajith Nair',
 'Ajith Nair, Anish K',
 'Ajith Sukumaran, Currae Healthtech Fund',
 'Ajmera Group of Companies',
 'Al Dhaheri family',
 'Alex Chua, Rahul Garg',
 'Alex Kuruvilla, Pradeep Guha, Saket Dhankar, Rajan Pandhare',
 'Alibaba',
 'Alibaba Group, Ant Financial',
 'Alibaba Pictures',
 'Alibaba, Foxconn, Softbank',
 'Alibaba, Helion Venture Partners, Bessemer Venture Partners, Ascent Capital',
 'Allcargo Logistics, Navneet Education and Mahavir Agency',
 'Allen Blue, John Katzman, Naveen Tewari, Kartik Hosanagar, Kashyap Deorah, 500 Startups, Blue Fog Capital',
 'Alok Bajpai, Rajnish Kumar, Amit Dey',
 'Alok Goel',
 'Alok Mittal',
 'Alok Mittal, Amit Gupta, Anuj Srivastava, Himanshu Aggarwal, Raghunandan G, Puneet Agarwal',
 'Alok Mittal, Deepak Jain, Ritesh Malik, Jim Schimdktke',
 'Alok Mittal, Zeeshan Hayat, Niraj Singh, Nikunj Jain, Anirudh Damani, Punit Goyal',
 'Alok Rawat, Grey Orange Robotics',
 'Alpha Capital',
 'Alphard Maritime Group',
 'Alteria Capital',
 'Altimeter Capital, DST Global',
 'Altimeter Capital, Sutter Hill Ventures',
 'Amadeus Capital',
 'Amajit Gupta, Praveen Dubey, J.P. Bhatt',
 'Amazon',
 'Amazon Alexa Fund & Dentsu Ventures',
 'Amazon Inc. and Mastercard',
 'Amazon, Ashish Dhawan, Catamaran Ventures, NR Narayana Murthy.',
 'Amazon, Fidelity Growth Partners, Mousse Partners',
 'Amazon, Vertex Ventures, Qualcomm, Ru-Net Technology Partners, Matrix Partners',
 'Amazon-Patni JV',
 'Ambarish Gupta, Aneesh Reddy, Bold Ventures, Vona Investments',
 'Ambit Pragma',
 'Ameera Shah, Vivek Bhargava',
 'Amen Dhyllon',
 'American Express Ventures, Sequoia Capital',
 'Amicus Capital',
 'Amit Burman, SIDBI Venture Capital',
 'Amit Choudhary',
 'Amit Choudhary, Anuj Puri',
 'Amit Gupta, Sahil Barua, Mukul Singhal, Tracxn Labs',
 'Amit Patni',
 'Amit Patni, Anirudh Damani, Samir Shah',
 'Amit Ranjan, Deepinder Goyal, Zishaan Hayath, Powai Lake Ventures',
 'Amit Ranjan, Vijay Shekhar Sharma, Kunal Bahl, Girish Mathrubootham &\\\\xc2\\\\xa0 Group of other Angel investors',
 'Amit Singhal and Unitus Seed Fund',
 'Amit Singhal, PK Gulati & others',
 'Amit Tyagi, Sandeep Acharya & others',
 'Amod Malviya',
 'Amour Infrastructure',
 'Anand Chandrasekaran',
 'Anand Chandrasekaran & Others',
 'Anand Chandrasekaran, Ananth Narayanan, Mekin Maheshwari, Ravi Garikipati, Divyesh Shah, Swastika Company Ltd',
 'Anand Chandrasekaran, Apurva Chamaria, Ritesh Malik, Ashish Toshniwal, Ajeet Khurana',
 'Anand Chandrasekaran, Kanwaljit Singh, Manoj Varghese',
 'Anand Chandrasekaran, Rajesh Sawhney, Kalpana Tatavarti, Shivanandan Pare',
 'Anand Chandrasekaran, Rajiv Mehta, Ramakant Sharma',
 'Anand Mahindra',
 'Anand Mahindra, Uday Punj, Ashish Hemrajani, Sanjeev Mehra',
 'Anand Rajaraman, Venky Harinarayan',
 'Anand Sankeshwar, Yang Shu',
 'Anand Vijay, Nipun Dureja, Satyajit Heeralal, Keith Rodricks, Gaurav Lochan, Azmul Haque, Nikhil Bagri',
 'Anand Vijay, Shashank Mehrotra & Others',
 'Aneesh Seth, Tushar Mittal',
 'AngelList, Rahul Khanna, Rajeev Arora and Ram Ramsundar.',
 'AngelPrime',
 'Anglian Omega Network',
 'Anicut Capital',
 'Anil Advani, Pramod Jain, Amrendra Reddy and Manish Satnaliwala.',
 'Anil Jain & other HNIs',
 'Anil Kapoor',
 'Anil Matai, Vikram Tandon, Shyam Sundar R & others',
 'Anil Menon',
 'Aniruddha Malpani, Startup Oasis',
 'Anirudh Damani, Daud Ali, Narendra Karnavat, Vikas Kapoor, Vikram Lakhotia, Krishna Jhunjhunwaala, Jayesh Shah',
 'Anirudh Damani, Vikram Lakhotia',
 'Anita Dongre, Yash Dongre, Milind Sarwate',
 'Ankit Gupta, Puneet Motihar',
 'Ankit Maheshwari, Anand Singh',
 'Ankit Nagori',
 'Ankur Capital',
 'Ankur Capital, Hyderabad Angels',
 'Ankur Gupta',
 'Ankush Mehta',
 'Ankush Nijhawan, Manish Dhingra, Gaurav Bhatnagar',
 'Ant Financial',
 'Ant Financial Services (Alipay)',
 'Ant Financials',
 'Anuj Puri, Redcliffe Capital, Artha India Ventures, Siddharth Kothari, Apoorv Ranjan Sharma,',
 'Anupam Mittal, Amit Gupta, Utsav Somani, Neeraj Goenka, Farooq Adam Mukadam',
 'Anupam Mittal, Anand Chandrasekaran, Uday Shankar, Chetan Bhagat',
 'Anupam Mittal, Anuj Srivastava, Ankit Nagori',
 'Anupam Mittal, Manish Vij, Prashant Tandon, Gaurav Agarwal, Akash Agarwal, Himanshu Aggarwal, Kevin Parikh',
 'Anupam Mittal, Sharad Sharma & 14 others',
 'Anurag Chauhan',
 'Aparup Sengupta, Devendra Reddy,',
 'Apis Partner, Eight Roads Ventures, Bamboo Capital Partners',
 'Apoorv Ranjan Sharma, Daud Ali and others',
 'Applyifi',
 'Aprameya Radhakrishna',
 'Aprameya Radhakrishna, Deepak Natraj, Girish Mathrubootham, Mahesh Murthy, Pallav Nadhani, Pavan Ongole, Sandeep Mathur, Vijay Shekhar Sharma & Others',
 'Aprameya Radhakrishna, Naman Sarawagi, Afsal Salu,',
 'Aqeel Ahmed',
 'Aramex Ventures Llc',
 'Arihant Patni, Avnish Mehra, Pranay Adhvaryu, Ravi Sampat',
 'Arihant Patni, RAAY Global Investments',
 'Arihant Patni, Vishal Khare,\\\\xc2\\\\xa0 Viswanath Ramachandran',
 'Arjun Handa, Amit Jindal, Nagendra Chaudhary',
 'Armat Group',
 'Artha India Ventures, Singularity Holdings, Rajan Anandan, Girish Mathrubootham',
 'Artha Venture',
 'Artiman Ventures',
 'Arun Chandra Mohan',
 'Arun Chandra Mohan, Praveen Sinha',
 'Arun Patodia, Bharat Kedia',
 'Arun Seth, T.V. Mohandas Pai, Anand Chandrasekaran, Deepak Ghaisas',
 'Arun Tadanki, Aditya Verma',
 'Ascent Capital, Kalaari Capital',
 'Ash Bhardwaj',
 'Asha Jadeja Motwani & Others',
 'Ashish Gupta',
 'Ashish Gupta and other undisclosed investors',
 'Ashish Jhalani',
 'Ashish Kacholi, S Chand Group',
 'Ashish Mahajan, Sarvesh Sharma',
 'Ashish Todi, Abhinav Patodia, Kumar Shwetabh',
 'Ashok Agarwal',
 'Ashok Goel (promoter)',
 'Ashok Kumar Gajera',
 'Ashutosh Lawania, Alok Goel & others',
 'Ashutosh Lawania, Rajul Jain, Badal Malick, Rishi Gupta & Others',
 'Ashvin Chadha',
 'Ashvin Chadha, Avtar Monga, Udaan Angels, Dheeraj Jain',
 'Asia Pacific Internet Group',
 'AskMe',
 'Aspada Advisors, IDG Ventures,\\\\xc2\\\\xa0 Inventus Capital',
 'Aspada Investment Advisors, Blume Ventures.',
 'Aspada Investment Advisors, Qualcomm Ventures',
 'Aspada Investments',
 'Aspire Logistics LLC',
 'Aspire Systems',
 'Asset Management (Asia) Ltd, Digital Garage Inc',
 'Astarc Ventures',
 'Astarc Ventures & Others',
 'Astarc Ventures, 50K Ventures & others',
 'Astarc Ventures, Anand Chandrasekaran',
 'Asuka Holdings',
 'Asuka Holdings, YouWeCan Ventures, Beenext, Beenos, M&S Partners',
 'Asuka, Pravega Ventures, BEENEXT',
 'Atul Gupta and Saurabh Rastogi',
 'Atul Ingle',
 'Atul Jain, Anil Gelra, Jaikumar Nair',
 'Atul Jalan',
 'Atul Jalan, Shrikanth & Bharath',
 'Atul Nishar',
 'Atulya Mittal',
 'Augment Ventures, Rahul Kayan, Nikhil Golcha, Shubham Gupta, Roy Kwan',
 'August Capital Partners, Michael Blakey',
 'Auxano Deals',
 'Avendus Finance',
 'Avendus Finance Pvt. Ltd',
 'Avtar Monga, chief operating office at IDFC Bank, Aditya Malik & Others',
 'Axiata Digital',
 'Axilor Ventures',
 'Axilor Ventures, E-City VEntures Atul Goel',
 'Axilor Ventures, Kumar Vembu',
 'Axilor Ventures, Newfort Capital',
 'Axilor Ventures, Parampara Early Stage Opportunities Fund & Others',
 'Axilor, Sprout Venture Partners and others',
 'Axilor, undisclosed investors',
 'Axis Capital Partners',
 'Ayesha Takia Azmi, Abu Farhan Azmi',
 'Ayushmann Khurana',
 'Azim Premji, Binny Bansal',
 'B Capital Group, Ignition Partners, Greycroft, e.ventures,\\\\xc2\\\\xa0 Eight Roads Ventures',
 'B Capital, International Finance Corporation (IFC), Accel Partners and IDG Ventures',
 'B M Gupta, Vinod Singhal',
 'B S Nagesh',
 'BAC Acquisitions, Unifi AIF, BRD Securities, Northern R Capital',
 'BCCL',
 'BEENEXT',
 'BLIP Initiatives',
 'Baillie Gifford, Falcon Edge Capital, Tiger Global, SoftBank Group, DST Global, Didi Kuaidi',
 'Balasubramanian Krishnamurthy, Sidhartha Hazarika & Others',
 'Base of Pyramid Asia (BOPA) Pte Ltd',
 'Baskar Subramanian, Saket Kumar, Gaurav Suri and Ankit Kesarwani',
 'Batlivala & Karani Securities, Venture Works',
 'Battery Road Digital Holdings LLC',
 'Bay Capital Investments and Others',
 'BedRock Ventures, Rajesh Sawhney, Shailesh Singh',
 'Bedrock Ventures',
 'BeeNext , WEH Ventures and Sprout Ventures',
 'BeeNext, TV Mohandas Pai, Kunal Shah, Sandeep Tandon',
 'Beenext',
 'Beenext, Digital Garage, Beenos, Qualgro, Mamoru Taniya, SAIF Partners',
 'Beenext, Digital Garage, Lightbox, Beenos',
 'Beerud Sheth and Ravi Mantha',
 'Bennett Coleman and Company Ltd (BCCL)',
 'Bennett, Coleman and Co. Ltd (BCCL)',
 'Bennett, Coleman and Company Ltd',
 'Bennett, Coleman and Company Ltd (BCCL),',
 'Benori Ventures LLP',
 'Bertelsmann India',
 'Bertelsmann India Investments',
 'Bertelsmann India Investments, Mayfield India, Saama Capital, India Quotient',
 'Bertelsmann India Investments, Nirvana Digital India Fund, Nirvana Digital Investment Holding, 500 Startups',
 'Bertelsmann India, Mayfield Capital, Saama Capital, Darrin Capital',
 'Bessemer Venture Partner, Accel, SAIF Partners',
 'Bessemer Venture Partners',
 'Bessemer Venture Partners and Orios Venture Partners, JM Financials and MEMG',
 'Bessemer Venture Partners, Anil Chopra',
 'Bessemer Venture Partners, Jungle Ventures, Helion Ventures',
 'Bessemer Venture Partners, Orios Venture Partners, Trifecta Capital,',
 'Bessemer Venture Partners, SAIF Partners',
 'Bessemer Venture Partners, Stellaris Venture Partners, Axis Capital, Singapore, Jungle Venture Partners',
 'Bessemer Venture Partners, Stellaris Venture Partners, Jungle Venture Partners, Axis Capital',
 'Bessemer Ventures, Blume Ventures',
 'Bessemer Ventures, Kae Capital',
 'Best Foodworks',
 'BetOnIndia Technology Pvt Ltd',
 'Bhairavi Jani, Alok Divatia, Namrata Kaul, Sohail Hashemi, Aijaz Saleem',
 'Bhanu Vikram Parsotam, Rohan Desai and Paras Patel',
 'Bharanidharan Viswanathan, Sanjiv Mittal, Shobhit Shukla, Rahul Agarwal',
 'Bharat Innovation, IDFC-Parampara Capital, Arthavida Ventures, Jitendra Gupta & Others',
 'Bhavdeep Reddy',
 'Bhavesh Manglani, Suraj Saharan, Darshan Upadhyay, Sanjay Notani & Others',
 'Bhavin Turakhia',
 'Bhavish Aggarwal, Ankit Bhati',
 'Bhavish Aggarwal, Binny Bansal,\\\\xc2\\\\xa0 Rajan Anandan, Mekin Maheshwar, Sunil Kalra, Anupam Mittal, Krishna Mehra, Singapore Angel Network',
 'Bhupen Shah, Jayesh Parekh, Sanjay Sathe',
 'Binny Bansal',
 'Binny Bansal, Anupam Mittal, Sachin Bhatia, Darius Pandole, Kunal Khattar, Dheerag Jain',
 'BitChemy Ventures, Maheshwari Investments Pvt Ltd, Anshoo Gaur, Rama Krishna Reddy, Sandeep Seerapu',
 'Bitkemy Ventures',
 'Biz Stone',
 'Biz Stone, Kunal Bahl, Rohit Bansal, Alagu Periyannan and Karthee Madasamy',
 'BlackJag Partners',
 'BlackSoil Capital Pvt Ltd',
 'BlackSoil Capital Pvt. Ltd',
 'BlackSoil Capital Pvt. Ltd.',
 'Blacksoil Capital Pvt. Ltd',
 'Blackstone Valley Group, Raghu Vohra, Aditya Dev Sood, Kamal Bansal',
 'Blinc Advisors, Amit Nanavati, Tashwinder Singh, Taranjit Jaswal, Amit Khanna',
 'Blue Orchard',
 'BlueOrchard Finance Ltd, Hinduja Leyland Finance and IntelleGrow',
 'Blume Ventures',
 'Blume Ventures & Other unnamed Investors',
 'Blume Ventures & Others',
 'Blume Ventures and RTP Global',
 'Blume Ventures, Adil Allana, Aprameya Radhakrishna, Gautam Ivatury, Signal Point Partners',
 'Blume Ventures, BEENEXT, Barkawi Holdings GmbH, TM Service Technology Holdings Gmbh, Sreevathsa Prabhakar',
 'Blume Ventures, Barkawi Holdings GmbH, TM Service Technology Holdings GmbH',
 'Blume Ventures, Contrarian Capital India Partners, Emergent Ventures India, Pallav Nadhani, Ashish Gupta, Sharad Sharma, Sirion Labs',
 'Blume Ventures, Contrarian Capital, 91springboard, Emergent Ventures, Abstract Ventures, Anthill Ventures, Axilor Ventures',
 'Blume Ventures, Flipkart',
 'Blume Ventures, Girish Mathrubootham, Aprameya Radhakrishna',
 'Blume Ventures, Goldbell Group, Anurag Srivastava, Shailesh Rao, Amiya Pathak, Rajesh Yohanan and Rahul Garg',
 'Blume Ventures, HealthQuad and Fireside Ventures',
 'Blume Ventures, IDG Ventures & Indian Angel Network',
 'Blume Ventures, Indian Angel Network',
 'Blume Ventures, Indian Angel Network, Kunal Shah, Sandeep Tandon',
 'Blume Ventures, Mumbai Angels, ah! Ventures, Digital Currency Group, Boost VC, Bank to the Future and Funders Club',
 'Blume Ventures, NB Ventures, Nspira',
 'Blume Ventures, Rajan Anandan, Sumit Jain, Aprameya Radhakrishna, Sujeet Kumar, Phanindra Sama',
 'Blume Ventures, Sachin Bansal, Vijay Shekhar Sharma, Binny Bansal,\\\\xc2\\\\xa0 Kunal Shah, Sandeep Tandon, Ashish Tulsian',
 'Blume Ventures,\\\\xc2\\\\xa0 Tracxn Labs',
 'Blume Ventures. Lenovo Capital and Incubator Group (LCIG)',
 'Blume ventures',
 'Bodhtree Consulting Limited',
 'Boman Irani, Dhruv Chitgopekar, Prantik Dasgupta',
 'BookMyShow',
 'Brand Capital',
 'Brand Capital and Others',
 'Brand Capital, Paragon Trust',
 'Brand Capital, Siddhivinayak Skyscrapers, Dinesh R. Challa',
 'Bravia Capital',
 'Breakthrough Energy Ventures',
 'Bren Corporation',
 'Brian Acton',
 'Brick Eagle',
 'Brigade Innovations LLP, TV Mohandas Pai, Suhail Rahman, Bobby Reddy, M George Oommen',
 'British and Indian Governments',
 'Broadbean Capital services',
 'ByteDance, Arun Sarin, Matrix Partners, Sequoia Capital India, Omidyar Network,\\\\xc2\\\\xa0 Falcon Edge',
 'C4D Partners',
 'CA Media LP,\\\\xc2\\\\xa0 Start Media.',
 'CASHurDRIVE Marketing Pvt Ltd',
 'CBA Capital and others',
 'CCube Angels, Frontline Strategy',
 'CDC Group Plc',
 'CDC Group plc\\\\xc2\\\\xa0',
 'CIO Angel Network',
 'CIO Angel Network (CAN)',
 'CIO Angel Network, Indian Angel Network',
 'CLP Holdings Group, Innogy, \\\\xc3\\\\x98rstead, and Tenaska',
 'CLSA Capital Partners ARIA IV Funds',
 'CMYK Health Boutique Pvt Ltd & Other individual investors',
 'CP Bothra',
 'Calcutta Angel Network, Appliyifi',
 'Calcutta Angels Network',
 'Calcutta Angels Network (CAN), Augment Ventures',
 'Calcutta Angels Network, LetsVenture, Anupam Mittal, Currae Healthtech Fund',
 'Calcutta Angels, Lead Angels & Others',
 'Calcutta Angels, Venture Nursery Angels Mumbai Angels',
 'Cameron Jones',
 'Canaan Partners',
 'Cao Yibin, Huang Wei, Madhusudan E,',
 'Capillary Technologies, Whiteboard Capital, YourNest Angel Fund, Rajul Garg',
 'CapitalG, SAIF Partners and LGT Impact Ventures',
 'CapitalG, Sequoia India',
 'CareerNet Consulting Pvt. Ltd, Ideation Initiative Pvt. Ltd,',
 'Carlyle Group, Tiger Global',
 'Carpediem Capital',
 'Carpediem Capital & Others',
 'Carrick Capital Partners',
 'Catamaran Ventures, New India Investment Corporation',
 'Cataraman Ventures',
 'Centre For Incubation & Business Acceleration (CIBA), Goa',
 'Centre for Innovation Incubation and Entrepreneurship (CIIE)',
 'CerraCap',
 'Chan Zuckerberg Initiative, Times Internet Ltd, Sequoia Capital, Sofina, Lightspeed Ventures',
 'Chandigarh Angel Network (CAN)',
 'Chandigarh Angels Funding',
 'Chandigarh Angels Network',
 'Chandigarh Angels Network (CAN)',

In [6]:
fund.info()

<class 'pandas.DataFrame'>
RangeIndex: 3044 entries, 0 to 3043
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Sr No              3044 non-null   int64
 1   Date dd/mm/yyyy    3044 non-null   str
 2   Startup Name       3044 non-null   str
 3   Industry Vertical  2873 non-null   str
 4   SubVertical        2108 non-null   str
 5   City  Location     2864 non-null   str
 6   Investors Name     3044 non-null   str
 7   InvestmentnType    3040 non-null   str
 8   Amount in USD      2084 non-null   str
 9   Remarks            419 non-null    str
dtypes: int64(1), str(9)
memory usage: 593.2 KB

In [7]:
# remove the remarks column
fund.drop(columns=['Remarks'],inplace=True)

In [8]:
fund.head()

,Sr No,Date dd/mm/yyyy,Startup Name,Industry Vertical,SubVertical,City Location,Investors Name,InvestmentnType,Amount in USD
0,1,09/01/2020,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,"20,00,00,000"
1,2,13/01/2020,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,"80,48,394"
2,3,09/01/2020,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,"1,83,58,860"
3,4,02/01/2020,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,"30,00,000"
4,5,02/01/2020,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,"18,00,000"

In [9]:
# set the Sr No as the row index of fund
fund.set_index('Sr No',inplace=True)

In [10]:
fund.head()

,Date dd/mm/yyyy,Startup Name,Industry Vertical,SubVertical,City Location,Investors Name,InvestmentnType,Amount in USD
Sr No,,,,,,,,
1,09/01/2020,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,"20,00,00,000"
2,13/01/2020,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,"80,48,394"
3,09/01/2020,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,"1,83,58,860"
4,02/01/2020,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,"30,00,000"
5,02/01/2020,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,"18,00,000"

In [11]:
# rename the columns of this dataframe
fund.rename(columns={'Sr No':'sr','Date dd/mm/yyyy':'date','Startup Name':'startup','Industry Vertical':'vertical',
                     'SubVertical':'subvertical','City  Location':'city','Investors Name':'investors',
                     'InvestmentnType':'round','Amount in USD':'amount'},inplace=True)

In [12]:
fund.head()

,date,startup,vertical,subvertical,city,investors,round,amount
Sr No,,,,,,,,
1,09/01/2020,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,"20,00,00,000"
2,13/01/2020,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,"80,48,394"
3,09/01/2020,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,"1,83,58,860"
4,02/01/2020,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,"30,00,000"
5,02/01/2020,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,"18,00,000"

In [13]:
fund.rename(columns={'stratup':'startup'},inplace=True)

In [14]:
fund.head()

,date,startup,vertical,subvertical,city,investors,round,amount
Sr No,,,,,,,,
1,09/01/2020,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,"20,00,00,000"
2,13/01/2020,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,"80,48,394"
3,09/01/2020,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,"1,83,58,860"
4,02/01/2020,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,"30,00,000"
5,02/01/2020,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,"18,00,000"

In [15]:
# now covert the amount column to crore rupees from usd
fund.info()

<class 'pandas.DataFrame'>
RangeIndex: 3044 entries, 1 to 3044
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         3044 non-null   str
 1   startup      3044 non-null   str
 2   vertical     2873 non-null   str
 3   subvertical  2108 non-null   str
 4   city         2864 non-null   str
 5   investors    3044 non-null   str
 6   round        3040 non-null   str
 7   amount       2084 non-null   str
dtypes: str(8)
memory usage: 540.5 KB

In [16]:
fund[fund['amount'].isnull()]

,date,startup,vertical,subvertical,city,investors,round,amount
Sr No,,,,,,,,
145,01/10/2018,Northmist,Fashion,Mens Wear,Delhi,Prashant Jaiswal,Seed/ Angel Funding,NaN
156,04/09/2018,HappyGoEasy,Consumer Internet,Online Travel Agecy,Gurugram,"Korea Investment Partners (KIP), Samsung and C...",Private Equity,NaN
158,05/09/2018,Mad Street Den,Technology,Computer Vision And Artificial Intelligence (A...,Chennai,KDDI\\xc2\\xa0,Private Equity,NaN
166,01/08/2018,HealthFin,Finance,Patient Financing Platform,Pune,"Axilor, Sprout Venture Partners and others",Seed/ Angel Funding,NaN
190,01/07/2018,Leena AI,Technology,HR Virtual Agent For Employees,Gurugram,Y Combinator,Seed/ Angel Funding,NaN
...,...,...,...,...,...,...,...,...
3028,21/05/2015,Knit,NaN,NaN,NaN,"Rohit Jain, Amit Rambhia & Others",Seed Funding,NaN
3031,22/01/2015,Freshmonk,NaN,NaN,NaN,"August Capital Partners, Michael Blakey",Seed Funding,NaN
3032,22/01/2015,Englishleap.com,NaN,NaN,NaN,ANALEC,Private Equity,NaN
3036,24/01/2015,Impartus,NaN,NaN,NaN,Kaizen Private Equity,Private Equity,NaN
3043,30/01/2015,Simplotel,NaN,NaN,NaN,MakeMyTrip,Private Equity,NaN

In [17]:
fund['amount'].value_counts(dropna=False)

amount
NaN            960
10,00,000      165
5,00,000       108
20,00,000       69
30,00,000       66
              ...
1,35,000         1
2,85,000         1
30,768           1
1,47,50,000      1
32,50,000        1
Name: count, Length: 472, dtype: int64

In [18]:
# first in this amount column replace the missing values with 0
fund['amount'] = fund['amount'].fillna('0')

In [19]:
# replace the , with ''
fund['amount'] = fund['amount'].str.replace(',','')

In [20]:
fund[~fund['amount'].str.isdigit()]

,date,startup,vertical,subvertical,city,investors,round,amount
Sr No,,,,,,,,
21,17/11/2019,Burger Singh,Food and Beverage,Indian Burger Brand,Gurgaon,RB Investments,Venture,undisclosed
35,21/10/2019,The Man Company,Consumer Goods,Beauty and Grooming,Gurgaon,Ayushmann Khurana,Corporate Round,unknown
59,19/08/2019,Mishry Reviews,Services,Product Review,Gurgaon,Vir Sanghvi,Series A,Undisclosed
77,03/06/2019,FabHotels,E-Commerce,Hospitality,Gurgaon,"Goldman Sachs, Accel Partners and Qualcomm",NaN,4889975.54
82,06/06/2019,Sistema.bio,Agriculture,Hybrid Reactor Biodigestor,Nairobi,"Shell Foundation, DILA CAPITAL, Engie RDE Fund...",NaN,2739034.68
84,06/06/2019,Pratilipi,Digital Media,E-Books,Bengaluru,Qiming Venture Partners,Series B,15109500.00
90,06/05/2019,Ola Electric,Transport,Cabs,Bengaluru,Tata Sons,Series A,undisclosed
92,05/05/2019,StyleDotMe,E-commerce,Fashion and Shopping,Delhi,Indian Angel Network and other angel investors...,Bridge Round,undisclosed
110,19/04/2019,KrazyBee,E-commerce,Lending Platform,Bengaluru,"BAC Acquisitions, Unifi AIF, BRD Securities, N...",Debt,14342000+
113,01/02/2019,FleetX,AI,Logistics,Gurgaon,India Quotient and LetsVenture\\xe2\\x80\\x99s...,Pre Series A,Undisclosed
140,22/11/2018,Skillbox,Social Network,Art,Gurugram,Individual investors,Seed Funding,Undisclosed
2603,09/07/2015,\\xc2\\xa0News in shorts,\\xc2\\xa0News Aggregator mobile app,NaN,\\xc2\\xa0Noida,\\xc2\\xa0Tiger Global,Private Equity,\\xc2\\xa020000000
2604,09/07/2015,\\xc2\\xa0Bluestone,\\xc2\\xa0Online Jewellery Store,NaN,\\xc2\\xa0Bangalore,"\\xc2\\xa0IvyCap Ventures, Accel Partners, Dra...",Private Equity,\\xc2\\xa016200000
2605,09/07/2015,\\xc2\\xa0Shopsity,\\xc2\\xa0Fashion Info Aggregator App,NaN,\\xc2\\xa0Gurgaon,"\\xc2\\xa0 Sandeep Aggarwal, Teruhide Sato",Seed Funding,\\xc2\\xa0N/A
2606,09/07/2015,\\xc2\\xa0Notesgen,\\xc2\\xa0Online Study Notes Marketplace,NaN,\\xc2\\xa0New Delhi,"\\xc2\\xa0Rajeev Saraf, Arvind Jha, R. Satya N...",Seed Funding,\\xc2\\xa0N/A
2607,\\xc2\\xa010/7/2015,\\xc2\\xa0Infinity Assurance,\\xc2\\xa0Warranty Programs Service Administra...,NaN,\\xc2\\xa0New Delhi,\\xc2\\xa0Indian Angel Network,Seed Funding,\\xc2\\xa0600000
2608,10/07/2015,\\xc2\\xa0Footprints Education,\\xc2\\xa0Pre-School Chain,NaN,\\xc2\\xa0Gurgaon,"\\xc2\\xa0LetsVenture, Kumar Bansal, Kshitij Jain",Seed Funding,\\xc2\\xa0685000
2609,10/07/2015,\\xc2\\xa0Loylty Rewards,\\xc2\\xa0Premium Loyalty Rewards Point Manage...,NaN,\\xc2\\xa0Mumbai,\\xc2\\xa0IndianIdeas.com,Private Equity,\\xc2\\xa019350000
2610,13/07/2015,\\xc2\\xa0Ameyo,\\xc2\\xa0Contact Center Software Platform,NaN,\\xc2\\xa0Gurgaon,\\xc2\\xa0Forum Synergies PE Fund,Private Equity,\\xc2\\xa05000000
2611,13/07/2015,\\xc2\\xa0Mamagoto,\\xc2\\xa0Casual Dining restaurant Chain,NaN,\\xc2\\xa0New Delhi,\\xc2\\xa0Goldman Sachs,Private Equity,\\xc2\\xa010000000
2612,13/07/2015,\\xc2\\xa0Satvacart,\\xc2\\xa0Online Grocery Delivery,NaN,\\xc2\\xa0Gurgaon,\\xc2\\xa0Palaash Ventures,Seed Funding,\\xc2\\xa0N/A
2614,14/07/2015,Zenify,Residential Rental management platform,NaN,Bangalore,Atul Jalan,Seed Funding,\\xc2\\xa0N/A

In [21]:
fund['amount'] = fund['amount'].str.replace({'Undisclosed':'0','undisclosed':'0','unknown':'0'})

In [22]:
fund[~fund['amount'].str.isdigit()]

,date,startup,vertical,subvertical,city,investors,round,amount
Sr No,,,,,,,,
77,03/06/2019,FabHotels,E-Commerce,Hospitality,Gurgaon,"Goldman Sachs, Accel Partners and Qualcomm",NaN,4889975.54
82,06/06/2019,Sistema.bio,Agriculture,Hybrid Reactor Biodigestor,Nairobi,"Shell Foundation, DILA CAPITAL, Engie RDE Fund...",NaN,2739034.68
84,06/06/2019,Pratilipi,Digital Media,E-Books,Bengaluru,Qiming Venture Partners,Series B,15109500.00
110,19/04/2019,KrazyBee,E-commerce,Lending Platform,Bengaluru,"BAC Acquisitions, Unifi AIF, BRD Securities, N...",Debt,14342000+
2603,09/07/2015,\\xc2\\xa0News in shorts,\\xc2\\xa0News Aggregator mobile app,NaN,\\xc2\\xa0Noida,\\xc2\\xa0Tiger Global,Private Equity,\\xc2\\xa020000000
2604,09/07/2015,\\xc2\\xa0Bluestone,\\xc2\\xa0Online Jewellery Store,NaN,\\xc2\\xa0Bangalore,"\\xc2\\xa0IvyCap Ventures, Accel Partners, Dra...",Private Equity,\\xc2\\xa016200000
2605,09/07/2015,\\xc2\\xa0Shopsity,\\xc2\\xa0Fashion Info Aggregator App,NaN,\\xc2\\xa0Gurgaon,"\\xc2\\xa0 Sandeep Aggarwal, Teruhide Sato",Seed Funding,\\xc2\\xa0N/A
2606,09/07/2015,\\xc2\\xa0Notesgen,\\xc2\\xa0Online Study Notes Marketplace,NaN,\\xc2\\xa0New Delhi,"\\xc2\\xa0Rajeev Saraf, Arvind Jha, R. Satya N...",Seed Funding,\\xc2\\xa0N/A
2607,\\xc2\\xa010/7/2015,\\xc2\\xa0Infinity Assurance,\\xc2\\xa0Warranty Programs Service Administra...,NaN,\\xc2\\xa0New Delhi,\\xc2\\xa0Indian Angel Network,Seed Funding,\\xc2\\xa0600000
2608,10/07/2015,\\xc2\\xa0Footprints Education,\\xc2\\xa0Pre-School Chain,NaN,\\xc2\\xa0Gurgaon,"\\xc2\\xa0LetsVenture, Kumar Bansal, Kshitij Jain",Seed Funding,\\xc2\\xa0685000
2609,10/07/2015,\\xc2\\xa0Loylty Rewards,\\xc2\\xa0Premium Loyalty Rewards Point Manage...,NaN,\\xc2\\xa0Mumbai,\\xc2\\xa0IndianIdeas.com,Private Equity,\\xc2\\xa019350000
2610,13/07/2015,\\xc2\\xa0Ameyo,\\xc2\\xa0Contact Center Software Platform,NaN,\\xc2\\xa0Gurgaon,\\xc2\\xa0Forum Synergies PE Fund,Private Equity,\\xc2\\xa05000000
2611,13/07/2015,\\xc2\\xa0Mamagoto,\\xc2\\xa0Casual Dining restaurant Chain,NaN,\\xc2\\xa0New Delhi,\\xc2\\xa0Goldman Sachs,Private Equity,\\xc2\\xa010000000
2612,13/07/2015,\\xc2\\xa0Satvacart,\\xc2\\xa0Online Grocery Delivery,NaN,\\xc2\\xa0Gurgaon,\\xc2\\xa0Palaash Ventures,Seed Funding,\\xc2\\xa0N/A
2614,14/07/2015,Zenify,Residential Rental management platform,NaN,Bangalore,Atul Jalan,Seed Funding,\\xc2\\xa0N/A

In [23]:
fund['amount'] = fund['amount'].str.replace({'14342000+':'14342000'})

In [24]:
fund[~fund['amount'].str.isdigit()]

,date,startup,vertical,subvertical,city,investors,round,amount
Sr No,,,,,,,,
77,03/06/2019,FabHotels,E-Commerce,Hospitality,Gurgaon,"Goldman Sachs, Accel Partners and Qualcomm",NaN,4889975.54
82,06/06/2019,Sistema.bio,Agriculture,Hybrid Reactor Biodigestor,Nairobi,"Shell Foundation, DILA CAPITAL, Engie RDE Fund...",NaN,2739034.68
84,06/06/2019,Pratilipi,Digital Media,E-Books,Bengaluru,Qiming Venture Partners,Series B,15109500.00
2603,09/07/2015,\\xc2\\xa0News in shorts,\\xc2\\xa0News Aggregator mobile app,NaN,\\xc2\\xa0Noida,\\xc2\\xa0Tiger Global,Private Equity,\\xc2\\xa020000000
2604,09/07/2015,\\xc2\\xa0Bluestone,\\xc2\\xa0Online Jewellery Store,NaN,\\xc2\\xa0Bangalore,"\\xc2\\xa0IvyCap Ventures, Accel Partners, Dra...",Private Equity,\\xc2\\xa016200000
2605,09/07/2015,\\xc2\\xa0Shopsity,\\xc2\\xa0Fashion Info Aggregator App,NaN,\\xc2\\xa0Gurgaon,"\\xc2\\xa0 Sandeep Aggarwal, Teruhide Sato",Seed Funding,\\xc2\\xa0N/A
2606,09/07/2015,\\xc2\\xa0Notesgen,\\xc2\\xa0Online Study Notes Marketplace,NaN,\\xc2\\xa0New Delhi,"\\xc2\\xa0Rajeev Saraf, Arvind Jha, R. Satya N...",Seed Funding,\\xc2\\xa0N/A
2607,\\xc2\\xa010/7/2015,\\xc2\\xa0Infinity Assurance,\\xc2\\xa0Warranty Programs Service Administra...,NaN,\\xc2\\xa0New Delhi,\\xc2\\xa0Indian Angel Network,Seed Funding,\\xc2\\xa0600000
2608,10/07/2015,\\xc2\\xa0Footprints Education,\\xc2\\xa0Pre-School Chain,NaN,\\xc2\\xa0Gurgaon,"\\xc2\\xa0LetsVenture, Kumar Bansal, Kshitij Jain",Seed Funding,\\xc2\\xa0685000
2609,10/07/2015,\\xc2\\xa0Loylty Rewards,\\xc2\\xa0Premium Loyalty Rewards Point Manage...,NaN,\\xc2\\xa0Mumbai,\\xc2\\xa0IndianIdeas.com,Private Equity,\\xc2\\xa019350000
2610,13/07/2015,\\xc2\\xa0Ameyo,\\xc2\\xa0Contact Center Software Platform,NaN,\\xc2\\xa0Gurgaon,\\xc2\\xa0Forum Synergies PE Fund,Private Equity,\\xc2\\xa05000000
2611,13/07/2015,\\xc2\\xa0Mamagoto,\\xc2\\xa0Casual Dining restaurant Chain,NaN,\\xc2\\xa0New Delhi,\\xc2\\xa0Goldman Sachs,Private Equity,\\xc2\\xa010000000
2612,13/07/2015,\\xc2\\xa0Satvacart,\\xc2\\xa0Online Grocery Delivery,NaN,\\xc2\\xa0Gurgaon,\\xc2\\xa0Palaash Ventures,Seed Funding,\\xc2\\xa0N/A
2614,14/07/2015,Zenify,Residential Rental management platform,NaN,Bangalore,Atul Jalan,Seed Funding,\\xc2\\xa0N/A

In [25]:
# unit test
fund.loc[2604,'city'].replace('\\\\xc2\\\\xa0','')

'Bangalore'

In [26]:
# column test
fund['test_amount'] = fund['amount'].str.replace('\\\\xc2\\\\xa0','')

In [27]:
# test is successful
fund[~fund['test_amount'].str.isdigit()]

,date,startup,vertical,subvertical,city,investors,round,amount,test_amount
Sr No,,,,,,,,,
77,03/06/2019,FabHotels,E-Commerce,Hospitality,Gurgaon,"Goldman Sachs, Accel Partners and Qualcomm",NaN,4889975.54,4889975.54
82,06/06/2019,Sistema.bio,Agriculture,Hybrid Reactor Biodigestor,Nairobi,"Shell Foundation, DILA CAPITAL, Engie RDE Fund...",NaN,2739034.68,2739034.68
84,06/06/2019,Pratilipi,Digital Media,E-Books,Bengaluru,Qiming Venture Partners,Series B,15109500.00,15109500.00
2605,09/07/2015,\\xc2\\xa0Shopsity,\\xc2\\xa0Fashion Info Aggregator App,NaN,\\xc2\\xa0Gurgaon,"\\xc2\\xa0 Sandeep Aggarwal, Teruhide Sato",Seed Funding,\\xc2\\xa0N/A,N/A
2606,09/07/2015,\\xc2\\xa0Notesgen,\\xc2\\xa0Online Study Notes Marketplace,NaN,\\xc2\\xa0New Delhi,"\\xc2\\xa0Rajeev Saraf, Arvind Jha, R. Satya N...",Seed Funding,\\xc2\\xa0N/A,N/A
2612,13/07/2015,\\xc2\\xa0Satvacart,\\xc2\\xa0Online Grocery Delivery,NaN,\\xc2\\xa0Gurgaon,\\xc2\\xa0Palaash Ventures,Seed Funding,\\xc2\\xa0N/A,N/A
2614,14/07/2015,Zenify,Residential Rental management platform,NaN,Bangalore,Atul Jalan,Seed Funding,\\xc2\\xa0N/A,N/A

In [28]:
fund['amount'] = fund['test_amount']

In [29]:
# now convert the string values to float
fund['amount'] = pd.to_numeric(fund['amount'],errors='coerce')

In [30]:
fund['amount'].fillna(0,inplace=True)

/tmp/ipykernel_11978/979909202.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  fund['amount'].fillna(0,inplace=True)

Sr No
1       200000000.0
2         8048394.0
3        18358860.0
4         3000000.0
5         1800000.0
           ...
3040      4500000.0
3041       825000.0
3042      1500000.0
3043            0.0
3044       140000.0
Name: amount, Length: 3044, dtype: float64

In [31]:
# convert the amount in crore rupees
fund['amount'] = round(fund['amount'].apply(lambda x: ((x*95.67)/10000000)),2)

In [32]:
fund.head()

,date,startup,vertical,subvertical,city,investors,round,amount,test_amount
Sr No,,,,,,,,,
1,09/01/2020,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,1913.40,200000000
2,13/01/2020,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,77.00,8048394
3,09/01/2020,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,175.64,18358860
4,02/01/2020,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,28.70,3000000
5,02/01/2020,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,17.22,1800000

In [33]:
# now convert the date column to datetime
fund['date'].isnull().sum()

np.int64(0)

In [34]:
fund['date'].sample(20)

Sr No
1550    18/07/2016
2098    29/01/2016
2902    18/03/2015
2863    28/04/2015
452     13/12/2017
964     16/03/2017
2379    30/10/2015
2630    22/07/2015
1310    18/10/2016
2014    05/01/2016
117     03/01/2019
2421    15/09/2015
1549    18/07/2016
1491    29/08/2016
1344    04/09/2016
464     20/12/2017
1586    08/06/2016
968     21/03/2017
186     26/08/2018
2425    16/09/2015
Name: date, dtype: str

In [35]:
fund['test_date'] = pd.to_datetime(fund['date'],errors='coerce',format='%d/%m/%Y')

In [36]:
temp_df = fund[fund['test_date'].isnull()]

In [37]:
# unit test
fund.loc[2832,'date'].replace('.','/')

'13/04/2015'

In [38]:
fund['date'] = fund['date'].str.replace('.','/')

In [39]:
fund[fund['test_date'].isnull()]

,date,startup,vertical,subvertical,city,investors,round,amount,test_amount,test_date
Sr No,,,,,,,,,,
193,05/072018,Loan Tap,Consumer Internet,Online Lending Platform For Salaried Professio...,Mumbai,"Shunwei Capital, Tuscan Ventures, Ashish Goenk...",Private Equity,59.79,6250000,NaT
2572,01/07/015,HandyHome,Hyperlocal Electronics repair Service,NaN,Mumbai,"Bessemer Ventures, Kae Capital",Seed Funding,6.03,630000,NaT
2607,\\xc2\\xa010/7/2015,\\xc2\\xa0Infinity Assurance,\\xc2\\xa0Warranty Programs Service Administra...,NaN,\\xc2\\xa0New Delhi,\\xc2\\xa0Indian Angel Network,Seed Funding,5.74,600000,NaT
2776,12/05/2015,Mobiefit,Mobile Fitness App,NaN,Goa,Prototyze,Seed Funding,0.00,0,NaT
2777,12/05/2015,Plancess,Online Education Platform,NaN,Mumbai,"Rajendra Gogri,\\xc2\\xa0 Chandrakant Gogri",Seed Funding,19.13,2000000,NaT
2832,13/04/2015,The Porter,Logistics Tech,NaN,Mumbai,Kae Capital,Seed Funding,4.78,500000,NaT
3012,15/01/2015,Wishberry,NaN,NaN,NaN,"Rajan Anandan, Shankar Mahadevan, Deep Kalra &...",Seed Funding,6.22,650000,NaT
3030,22/01//2015,Corporate360,NaN,NaN,NaN,Group of Angel Investors,Seed Funding,1.91,200000,NaT

In [40]:
fund.loc[3030,'date'] = '22/01/2015'
fund.loc[2572,'date'] = '01/07/2015'
fund.loc[193,'date'] = '05/07/2018'

In [41]:
fund['date'] = fund['date'].str.replace('\\\\xc2\\\\xa0','')

In [42]:
# now convert the date column
fund['date'] = pd.to_datetime(fund['date'],errors='coerce',format='%d/%m/%Y')

In [43]:
fund.head()

,date,startup,vertical,subvertical,city,investors,round,amount,test_amount,test_date
Sr No,,,,,,,,,,
1,2020-01-09,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,1913.40,200000000,2020-01-09
2,2020-01-13,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,77.00,8048394,2020-01-13
3,2020-01-09,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,175.64,18358860,2020-01-09
4,2020-01-02,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,28.70,3000000,2020-01-02
5,2020-01-02,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,17.22,1800000,2020-01-02

In [44]:
fund.drop(columns=['test_amount','test_date'],inplace=True)

In [45]:
fund.info()

<class 'pandas.DataFrame'>
RangeIndex: 3044 entries, 1 to 3044
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         3044 non-null   datetime64[us]
 1   startup      3044 non-null   str
 2   vertical     2873 non-null   str
 3   subvertical  2108 non-null   str
 4   city         2864 non-null   str
 5   investors    3044 non-null   str
 6   round        3040 non-null   str
 7   amount       3040 non-null   float64
dtypes: datetime64[us](1), float64(1), str(6)
memory usage: 491.8 KB

In [46]:
fund[fund['amount'].isnull()]

,date,startup,vertical,subvertical,city,investors,round,amount
Sr No,,,,,,,,
2605,2015-07-09,\\xc2\\xa0Shopsity,\\xc2\\xa0Fashion Info Aggregator App,NaN,\\xc2\\xa0Gurgaon,"\\xc2\\xa0 Sandeep Aggarwal, Teruhide Sato",Seed Funding,NaN
2606,2015-07-09,\\xc2\\xa0Notesgen,\\xc2\\xa0Online Study Notes Marketplace,NaN,\\xc2\\xa0New Delhi,"\\xc2\\xa0Rajeev Saraf, Arvind Jha, R. Satya N...",Seed Funding,NaN
2612,2015-07-13,\\xc2\\xa0Satvacart,\\xc2\\xa0Online Grocery Delivery,NaN,\\xc2\\xa0Gurgaon,\\xc2\\xa0Palaash Ventures,Seed Funding,NaN
2614,2015-07-14,Zenify,Residential Rental management platform,NaN,Bangalore,Atul Jalan,Seed Funding,NaN

In [47]:
fund['amount'] = fund['amount'].fillna(0)

In [48]:
fund.info()

<class 'pandas.DataFrame'>
RangeIndex: 3044 entries, 1 to 3044
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         3044 non-null   datetime64[us]
 1   startup      3044 non-null   str
 2   vertical     2873 non-null   str
 3   subvertical  2108 non-null   str
 4   city         2864 non-null   str
 5   investors    3044 non-null   str
 6   round        3040 non-null   str
 7   amount       3044 non-null   float64
dtypes: datetime64[us](1), float64(1), str(6)
memory usage: 491.8 KB

In [49]:
# now handle the startup column
fund['startup'].value_counts()

startup
Ola Cabs            8
Swiggy              8
Paytm               7
Meesho              6
NoBroker            6
                   ..
Grabhouse.com       1
Printvenue          1
Graphene            1
Simplotel           1
couponmachine.in    1
Name: count, Length: 2459, dtype: int64

In [50]:
pd.set_option('display.max_rows',100)

In [51]:
fund['startup'] = fund['startup'].str.strip().str.lower()

In [52]:
fund[~fund['startup'].str.isalnum()]

,date,startup,vertical,subvertical,city,investors,round,amount
Sr No,,,,,,,,
1,2020-01-09,byju’s,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,1913.40
4,2020-01-02,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,28.70
10,2019-12-03,dhruva space,Aerospace,Satellite Communication,Bengaluru,"Mumbai Angels, Ravikanth Reddy",Seed,478.35
16,2019-12-11,rein games,Gaming,Real money based gaming startup,Noida,Manipal Education and Medical Group (MEMG),Seed Round,478.35
17,2019-12-20,lenskart.com,E-Commerce,Online Eyewear Shopping Portal,Faridabad,SoftBank Vision Fund,Series G,2209.98
...,...,...,...,...,...,...,...,...
3037,2015-01-25,thrill app,NaN,NaN,NaN,People Group (Shaadi.com),Private Equity,9.57
3038,2015-01-27,cardekho.com,NaN,NaN,NaN,"Hillhouse Capital, Tybourne Capital",Private Equity,478.35
3039,2015-01-28,grabhouse.com,NaN,NaN,NaN,"Kalaari Capital, Sequoia Capital",Private Equity,23.92
3042,2015-01-30,mad street den,NaN,NaN,NaN,"Exfinity Fund, GrowX Ventures.",Private Equity,14.35
3044,2015-01-31,couponmachine.in,NaN,NaN,NaN,UK based Group of Angel Investors,Seed Funding,1.34

In [53]:
unwanted_char = r"[^a-zA-Z0-9\s-&!]"
fund[fund['startup'].str.contains(unwanted_char,regex=True)]

,date,startup,vertical,subvertical,city,investors,round,amount
Sr No,,,,,,,,
1,2020-01-09,byju’s,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,1913.40
4,2020-01-02,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,28.70
17,2019-12-20,lenskart.com,E-Commerce,Online Eyewear Shopping Portal,Faridabad,SoftBank Vision Fund,Series G,2209.98
20,2019-11-13,sunstone eduversity pvt. ltd,Education,Elearning,Gurgaon,"Prime Venture Partners, LetsVenture, PS1 Ventu...",Seed,14.35
68,2019-07-10,"""byju\\'s""",EdTech,Education,Bengaluru,Qatar Investment Authority,Private Equity Round,1435.05
...,...,...,...,...,...,...,...,...
3032,2015-01-22,englishleap.com,NaN,NaN,NaN,ANALEC,Private Equity,0.00
3034,2015-01-22,caratlane.com,NaN,NaN,NaN,Tiger Global,Private Equity,296.58
3038,2015-01-27,cardekho.com,NaN,NaN,NaN,"Hillhouse Capital, Tybourne Capital",Private Equity,478.35
3039,2015-01-28,grabhouse.com,NaN,NaN,NaN,"Kalaari Capital, Sequoia Capital",Private Equity,23.92
3044,2015-01-31,couponmachine.in,NaN,NaN,NaN,UK based Group of Angel Investors,Seed Funding,1.34

In [54]:
# name with unwanted characters
#  .com,.in,.io,.ai, \\xe2\\x80\\x99,\\xc2\\xa0

domain_pattern = r"\.(com|in|io|ai|co|org)\b"
fund['startup'] = fund['startup'].str.replace(domain_pattern,'',regex=True,case=False).str.strip()

In [55]:
fund[fund['startup'].str.contains(unwanted_char,regex=True)]

,date,startup,vertical,subvertical,city,investors,round,amount
Sr No,,,,,,,,
1,2020-01-09,byju’s,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,1913.40
4,2020-01-02,https://www.wealthbucket/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,28.70
20,2019-11-13,sunstone eduversity pvt. ltd,Education,Elearning,Gurgaon,"Prime Venture Partners, LetsVenture, PS1 Ventu...",Seed,14.35
68,2019-07-10,"""byju\\'s""",EdTech,Education,Bengaluru,Qatar Investment Authority,Private Equity Round,1435.05
82,2019-06-06,sistema.bio,Agriculture,Hybrid Reactor Biodigestor,Nairobi,"Shell Foundation, DILA CAPITAL, Engie RDE Fund...",NaN,26.20
88,2019-06-08,vogo automotive pvt. ltd.,Transportation,Dockless Scooter Rental Company,Karnataka,Alteria Capital,Debt Funding,34.29
118,2019-01-04,vyome therapeutics inc.,Health and Wellness,Specialty pharmaceutical,India/US,"Iron Pillar, Perceptive Advisors, Romulus Capi...",Series D,210.47
119,2019-01-04,samunnati financial intermediation & services ...,Finance,Non-banking financial company,Chennai,"MASSIF, a Dutch government fund",Debt-Funding,47.84
121,2018-12-01,urbanclap technologies pvt. ltd,Services Platform,Home services marketplace,New Delhi,Steadview Capital and Vy Capital.,Series D,478.35
128,2018-11-03,veritas finance ltd.,NBFC,MSME Finance,Chennai,"Norwest Venture Partners, CDC Group, the UK\\x...",Series D,265.95
146,2018-10-02,origo commodities india pvt. ltd,Logistics,Supply Chain,Hyderabad,"Cooperative Oikocredit, Caspian and Hivos-Trio...",Seed/ Angel Funding,105.24
240,2018-06-13,what\\xe2\\x80\\x99s up life,Consumer Internet,"A Local Discovery App For Dining-Out, Party, L...",Gurugram,Rannvijay Singha,Seed/ Angel Funding,0.00
399,2018-01-10,appario retail pvt ltd.,E-commerce,Retail,Delhi,Amazon-Patni JV,Private Equity,180.24
489,2017-11-09,tilite technologies pvt. ltd,Technology,Saas based Corporate Travel Management Solution,Bangalore,Matrix Partners,Seed Funding,0.00
493,2017-11-13,universal sportsbiz pvt. ltd,ECommerce,Celebrity fashion accessories and merchandise,Mumbai,Accel Partners,PrivateEquity,143.50
694,2017-07-12,bottr.me,Technology,Chatbot creation tool,Bangalore,"500 Startups, Purvi Capital, Rajan Anandan, Ab...",Seed Funding,0.00
713,2017-07-25,byju\\xe2\\x80\\x99s,Consumer Internet,Mobile Learning App,Bangalore,Tencent Holdings,Private Equity,334.84
714,2017-07-26,creator\\xe2\\x80\\x99s gurukul,Others,Co-Working Space Provider,New Delhi,Yuvraj Singh,Seed Funding,0.00
970,2017-03-22,the mons co.,eCommerce,Pregnancy & Baby Care etailer,New Delhi,"Shripad Nadkarni, Nandu Nandkishore",Seed Funding,0.00
984,2017-03-29,byju\\xe2\\x80\\x99s,Consumer Internet,Online Education Platform,Bangalore,Verlinvest,Private Equity,0.00
1154,2016-12-15,serv\\xe2\\x80\\x99d,Consumer Internet,Financial Services For Unorganized Workforce,Pune,Digital Financial Service Lab,Seed Funding,0.96
1165,2016-12-20,byju\\xe2\\x80\\x99s,Consumer Internet,Online Learning platform,Bangalore,International Financial Corporation,Private Equity,143.50
1357,2016-09-09,byju\\xe2\\x80\\x99s,Education,Online Learning App,Bangalore,"Chan Zuckerberg Initiative, Times Internet Ltd...",Private Equity,478.35
1395,2016-09-23,\\xc2\\xa0cloudcherry,Technology,CRM SAAS Platform,Chennai,"Vertex Ventures, Cisco Ventures, IDG Ventures",Private Equity,57.40
1399,2016-09-26,let\xe2\x80\x99s barter,Consumer Internet,Goods & Services Barter Platform,New Delhi,Scale Ventures Funds,Seed Funding,0.00
1433,2016-08-09,zeolr/respiron,Technology,Healthcare related IoT platform,New Delhi,Centre for Innovation Incubation and Entrepren...,Seed Funding,0.00
1515,2016-07-06,don\\xe2\\x80\\x99t scratch your head,Technology,Full Stack Offline & Online ERP Solution,Ahmedabad,"Gaurav Singhvi, Zaffiro Ventures",Seed Funding,2.39
1541,2016-07-14,transtutors / askiitians,Consumer Internet,Online Education & Tutoring portals,New Delhi,500 Startups,Private Equity,0.00
1554,2016-07-19,deal4loans / wishfin,Consumer Internet,\\nLoans Comparison platform\\n\\n\\n\\n (...,Noida,Franklin Templeton International Services Pvt....,Private Equity,143.50
1608,2016-06-15,oneway.cab,Consumer Internet,Taxi Rental Platform,Vadodara,Indian Angel Network,Seed Funding,4.31
1797,2016-04-21,m.paani,Consumer Internet,Loyalty rewards platform,Mumbai,"Blume Ventures, Adil Allana, Aprameya Radhakri...",Seed Funding,0.00
1838,2016-03-07,n.o.w,Consumer Internet,Bike Taxi Service & Hyperlocal Delivery App,Noida,"Ruchirans Jaipuria, Anuj Sanghi",Seed Funding,4.78
1881,2016-03-22,byju\\xe2\\x80\\x99s,Consumer Internet,Educational Video Content Creator,Bangalore,"Sequoia India, Sofina",Private Equity,717.52
2014,2016-01-05,alef\\nmobitech,Consumer Internet,Cloud Mobility Solutions,Mumbai,Tata Capital Innovation Fund,Private Equity,47.84
2019,2016-01-06,planmy\\nmedicaltrip,Healthcare,Medical Tourism platform,Pune,"Bhanu Vikram Parsotam, Rohan Desai and Paras P...",Seed Funding,1.44
2094,2016-01-28,zebi (yet to launch),Technology,Data Intelligence & Analytics,Hyderabad,Un disclosed investors,Seed Funding,9.57
2100,2016-01-29,n.o.w,Consumer Internet,Rental Bike Aggregator App,Noida,Maple Capital Advisors,Seed Funding,0.00
2406,2015-09-10,the/nudge foundation,Non Profit Organization to alleviate poverty,NaN,Bangalore,"Nanadan Nilekani, InMobi, Paytm",Seed Funding,3.01
2496,2015-08-07,carl\\xe2\\x80\\x99s jr,Fast food Chain Franchisee,NaN,Gurgaon,YouWeCan Ventures,Seed Funding,6.03
2505,2015-08-10,nearbuy (previously\\xc2\\xa0 groupon india),Hyper-Local Ecommerce,NaN,New Delhi,Sequoia Capital,Private Equity,153.07
2538,2015-08-18,zoojoo.be,Corporate Wellness App,NaN,Bangalore,RoundGlass Partners,Private Equity,9.57
2603,2015-07-09,\\xc2\\xa0news in shorts,\\xc2\\xa0News Aggregator mobile app,NaN,\\xc2\\xa0Noida,\\xc2\\xa0Tiger Global,Private Equity,191.34
2604,2015-07-09,\\xc2\\xa0bluestone,\\xc2\\xa0Online Jewellery Store,NaN,\\xc2\\xa0Bangalore,"\\xc2\\xa0IvyCap Ventures, Accel Partners, Dra...",Private Equity,154.99
2605,2015-07-09,\\xc2\\xa0shopsity,\\xc2\\xa0Fashion Info Aggregator App,NaN,\\xc2\\xa0Gurgaon,"\\xc2\\xa0 Sandeep Aggarwal, Teruhide Sato",Seed Funding,0.00
2606,2015-07-09,\\xc2\\xa0notesgen,\\xc2\\xa0Online Study Notes Marketplace,NaN,\\xc2\\xa0New Delhi,"\\xc2\\xa0Rajeev Saraf, Arvind Jha, R. Satya N...",Seed Funding,0.00
2607,2015-07-10,\\xc2\\xa0infinity assurance,\\xc2\\xa0Warranty Programs Service Administra...,NaN,\\xc2\\xa0New Delhi,\\xc2\\xa0Indian Angel Network,Seed Funding,5.74
2608,2015-07-10,\\xc2\\xa0footprints education,\\xc2\\xa0Pre-School Chain,NaN,\\xc2\\xa0Gurgaon,"\\xc2\\xa0LetsVenture, Kumar Bansal, Kshitij Jain",Seed Funding,6.55
2609,2015-07-10,\\xc2\\xa0loylty rewards,\\xc2\\xa0Premium Loyalty Rewards Point Manage...,NaN,\\xc2\\xa0Mumbai,\\xc2\\xa0IndianIdeas.com,Private Equity,185.12
2610,2015-07-13,\\xc2\\xa0ameyo,\\xc2\\xa0Contact Center Software Platform,NaN,\\xc2\\xa0Gurgaon,\\xc2\\xa0Forum Synergies PE Fund,Private Equity,47.84
2611,2015-07-13,\\xc2\\xa0mamagoto,\\xc2\\xa0Casual Dining restaurant Chain,NaN,\\xc2\\xa0New Delhi,\\xc2\\xa0Goldman Sachs,Private Equity,95.67
2612,2015-07-13,\\xc2\\xa0satvacart,\\xc2\\xa0Online Grocery Delivery,NaN,\\xc2\\xa0Gurgaon,\\xc2\\xa0Palaash Ventures,Seed Funding,0.00
2654,2015-07-29,zovi / little app,Hyperlocal Deals Marketplace,NaN,Bangalore,"Paytm, SAIF Partners,\\xc2\\xa0 Tiger Global M...",Private Equity,478.35
2795,2015-05-22,\\xc2\\xa0nudgespot,Customer Engagement Platform,NaN,Bangalore,"Kae Capital, Anoop Goyal, Mike Shah, VA Sastry",Seed Funding,5.98
2845,2015-04-20,1mg (healthkartplus),Online Pharmacy & Drug DB,NaN,Gurgaon,"Deep Kalra, Sequoia Capital, Omidyar Network, ...",Private Equity,57.40
2849,2015-04-22,eat.shop.love,Fashion ECommerce,NaN,Bangalore,Undisclosed Investor,Private Equity,33.48
2881,2015-03-09,crowdfire (formerly justunfollow),NaN,NaN,NaN,Kalaari Capital,Private Equity,23.92
2955,2015-02-09,faaso\\xe2\\x80\\x99s,NaN,NaN,NaN,Lightbox Ventures,Private Equity,191.34
2993,2015-01-05,#fame,NaN,NaN,NaN,TO THE NEW Ventures,Private Equity,95.67

In [56]:
# unit test
fund.loc[1165,'startup'].replace('\\\\xe2\\\\x80\\\\x99','')

'byjus'

In [57]:
# unit test
fund.loc[2610,'startup'].replace('\\\\xc2\\\\xa0','')

'ameyo'

In [58]:
fund['startup'] = fund['startup'].str.replace({'\\\\xe2\\\\x80\\\\x99':'','\\\\xc2\\\\xa0':''})

In [59]:
fund[fund['startup'].str.contains(unwanted_char,regex=True)]

,date,startup,vertical,subvertical,city,investors,round,amount
Sr No,,,,,,,,
1,2020-01-09,byju’s,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,1913.40
4,2020-01-02,https://www.wealthbucket/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,28.70
20,2019-11-13,sunstone eduversity pvt. ltd,Education,Elearning,Gurgaon,"Prime Venture Partners, LetsVenture, PS1 Ventu...",Seed,14.35
68,2019-07-10,"""byju\\'s""",EdTech,Education,Bengaluru,Qatar Investment Authority,Private Equity Round,1435.05
82,2019-06-06,sistema.bio,Agriculture,Hybrid Reactor Biodigestor,Nairobi,"Shell Foundation, DILA CAPITAL, Engie RDE Fund...",NaN,26.20
88,2019-06-08,vogo automotive pvt. ltd.,Transportation,Dockless Scooter Rental Company,Karnataka,Alteria Capital,Debt Funding,34.29
118,2019-01-04,vyome therapeutics inc.,Health and Wellness,Specialty pharmaceutical,India/US,"Iron Pillar, Perceptive Advisors, Romulus Capi...",Series D,210.47
119,2019-01-04,samunnati financial intermediation & services ...,Finance,Non-banking financial company,Chennai,"MASSIF, a Dutch government fund",Debt-Funding,47.84
121,2018-12-01,urbanclap technologies pvt. ltd,Services Platform,Home services marketplace,New Delhi,Steadview Capital and Vy Capital.,Series D,478.35
128,2018-11-03,veritas finance ltd.,NBFC,MSME Finance,Chennai,"Norwest Venture Partners, CDC Group, the UK\\x...",Series D,265.95
146,2018-10-02,origo commodities india pvt. ltd,Logistics,Supply Chain,Hyderabad,"Cooperative Oikocredit, Caspian and Hivos-Trio...",Seed/ Angel Funding,105.24
399,2018-01-10,appario retail pvt ltd.,E-commerce,Retail,Delhi,Amazon-Patni JV,Private Equity,180.24
489,2017-11-09,tilite technologies pvt. ltd,Technology,Saas based Corporate Travel Management Solution,Bangalore,Matrix Partners,Seed Funding,0.00
493,2017-11-13,universal sportsbiz pvt. ltd,ECommerce,Celebrity fashion accessories and merchandise,Mumbai,Accel Partners,PrivateEquity,143.50
694,2017-07-12,bottr.me,Technology,Chatbot creation tool,Bangalore,"500 Startups, Purvi Capital, Rajan Anandan, Ab...",Seed Funding,0.00
970,2017-03-22,the mons co.,eCommerce,Pregnancy & Baby Care etailer,New Delhi,"Shripad Nadkarni, Nandu Nandkishore",Seed Funding,0.00
1399,2016-09-26,let\xe2\x80\x99s barter,Consumer Internet,Goods & Services Barter Platform,New Delhi,Scale Ventures Funds,Seed Funding,0.00
1433,2016-08-09,zeolr/respiron,Technology,Healthcare related IoT platform,New Delhi,Centre for Innovation Incubation and Entrepren...,Seed Funding,0.00
1541,2016-07-14,transtutors / askiitians,Consumer Internet,Online Education & Tutoring portals,New Delhi,500 Startups,Private Equity,0.00
1554,2016-07-19,deal4loans / wishfin,Consumer Internet,\\nLoans Comparison platform\\n\\n\\n\\n (...,Noida,Franklin Templeton International Services Pvt....,Private Equity,143.50
1608,2016-06-15,oneway.cab,Consumer Internet,Taxi Rental Platform,Vadodara,Indian Angel Network,Seed Funding,4.31
1797,2016-04-21,m.paani,Consumer Internet,Loyalty rewards platform,Mumbai,"Blume Ventures, Adil Allana, Aprameya Radhakri...",Seed Funding,0.00
1838,2016-03-07,n.o.w,Consumer Internet,Bike Taxi Service & Hyperlocal Delivery App,Noida,"Ruchirans Jaipuria, Anuj Sanghi",Seed Funding,4.78
2014,2016-01-05,alef\\nmobitech,Consumer Internet,Cloud Mobility Solutions,Mumbai,Tata Capital Innovation Fund,Private Equity,47.84
2019,2016-01-06,planmy\\nmedicaltrip,Healthcare,Medical Tourism platform,Pune,"Bhanu Vikram Parsotam, Rohan Desai and Paras P...",Seed Funding,1.44
2094,2016-01-28,zebi (yet to launch),Technology,Data Intelligence & Analytics,Hyderabad,Un disclosed investors,Seed Funding,9.57
2100,2016-01-29,n.o.w,Consumer Internet,Rental Bike Aggregator App,Noida,Maple Capital Advisors,Seed Funding,0.00
2406,2015-09-10,the/nudge foundation,Non Profit Organization to alleviate poverty,NaN,Bangalore,"Nanadan Nilekani, InMobi, Paytm",Seed Funding,3.01
2505,2015-08-10,nearbuy (previously groupon india),Hyper-Local Ecommerce,NaN,New Delhi,Sequoia Capital,Private Equity,153.07
2538,2015-08-18,zoojoo.be,Corporate Wellness App,NaN,Bangalore,RoundGlass Partners,Private Equity,9.57
2654,2015-07-29,zovi / little app,Hyperlocal Deals Marketplace,NaN,Bangalore,"Paytm, SAIF Partners,\\xc2\\xa0 Tiger Global M...",Private Equity,478.35
2845,2015-04-20,1mg (healthkartplus),Online Pharmacy & Drug DB,NaN,Gurgaon,"Deep Kalra, Sequoia Capital, Omidyar Network, ...",Private Equity,57.40
2849,2015-04-22,eat.shop.love,Fashion ECommerce,NaN,Bangalore,Undisclosed Investor,Private Equity,33.48
2881,2015-03-09,crowdfire (formerly justunfollow),NaN,NaN,NaN,Kalaari Capital,Private Equity,23.92
2993,2015-01-05,#fame,NaN,NaN,NaN,TO THE NEW Ventures,Private Equity,95.67

In [60]:
fund.loc[1399,'startup'] = 'lets barter'

In [61]:
# unwanted characters in startup 
#  pvt. ltd,pvt ltd.,ltd.,inc.,pvt. ltd.,.bio
pattern = r"\s?\b(pvt\.?)?\s?\b(ltd\.?)"
fund['startup'] = fund['startup'].str.replace(pattern,'',regex=True,case=False).str.strip()

In [62]:
unwanted_char = r"[^a-zA-Z0-9\s-&!.]"
fund[fund['startup'].str.contains(unwanted_char,regex=True)]

,date,startup,vertical,subvertical,city,investors,round,amount
Sr No,,,,,,,,
1,2020-01-09,byju’s,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,1913.40
4,2020-01-02,https://www.wealthbucket/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,28.70
68,2019-07-10,"""byju\\'s""",EdTech,Education,Bengaluru,Qatar Investment Authority,Private Equity Round,1435.05
1433,2016-08-09,zeolr/respiron,Technology,Healthcare related IoT platform,New Delhi,Centre for Innovation Incubation and Entrepren...,Seed Funding,0.00
1541,2016-07-14,transtutors / askiitians,Consumer Internet,Online Education & Tutoring portals,New Delhi,500 Startups,Private Equity,0.00
1554,2016-07-19,deal4loans / wishfin,Consumer Internet,\\nLoans Comparison platform\\n\\n\\n\\n (...,Noida,Franklin Templeton International Services Pvt....,Private Equity,143.50
2014,2016-01-05,alef\\nmobitech,Consumer Internet,Cloud Mobility Solutions,Mumbai,Tata Capital Innovation Fund,Private Equity,47.84
2019,2016-01-06,planmy\\nmedicaltrip,Healthcare,Medical Tourism platform,Pune,"Bhanu Vikram Parsotam, Rohan Desai and Paras P...",Seed Funding,1.44
2094,2016-01-28,zebi (yet to launch),Technology,Data Intelligence & Analytics,Hyderabad,Un disclosed investors,Seed Funding,9.57
2406,2015-09-10,the/nudge foundation,Non Profit Organization to alleviate poverty,NaN,Bangalore,"Nanadan Nilekani, InMobi, Paytm",Seed Funding,3.01
2505,2015-08-10,nearbuy (previously groupon india),Hyper-Local Ecommerce,NaN,New Delhi,Sequoia Capital,Private Equity,153.07
2654,2015-07-29,zovi / little app,Hyperlocal Deals Marketplace,NaN,Bangalore,"Paytm, SAIF Partners,\\xc2\\xa0 Tiger Global M...",Private Equity,478.35
2845,2015-04-20,1mg (healthkartplus),Online Pharmacy & Drug DB,NaN,Gurgaon,"Deep Kalra, Sequoia Capital, Omidyar Network, ...",Private Equity,57.40
2881,2015-03-09,crowdfire (formerly justunfollow),NaN,NaN,NaN,Kalaari Capital,Private Equity,23.92
2993,2015-01-05,#fame,NaN,NaN,NaN,TO THE NEW Ventures,Private Equity,95.67

In [63]:
fund.loc[[1,68],'startup'] = 'byjus'

In [64]:
fund.loc[4,'startup'] = 'wealthbucket'

In [65]:
fund.head()

,date,startup,vertical,subvertical,city,investors,round,amount
Sr No,,,,,,,,
1,2020-01-09,byjus,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,1913.40
2,2020-01-13,shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,77.00
3,2020-01-09,mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,175.64
4,2020-01-02,wealthbucket,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,28.70
5,2020-01-02,fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,17.22

In [66]:
# fund.drop(columns=['stratup'],inplace=True)

In [67]:
sorted(fund['startup'].unique().tolist())[::-1]

['zzungry',
 'zwayam',
 'zuver',
 'zuppler',
 'zupermeal',
 'zovi / little app',
 'zopper',
 'zopnow',
 'zophop',
 'zoomcar',
 'zoojoo.be',
 'zomato',
 'zolostays',
 'zolo',
 'zoctr',
 'zocalo',
 'zo rooms',
 'zivame',
 'zippserve',
 'zippserv',
 'ziploan',
 'zipi',
 'zipgrid',
 'zipgo',
 'zinka',
 'zinghr',
 'zimmber',
 'zilingo',
 'zify',
 'ziffyhomes',
 'ziffity',
 'zeta',
 'zestmoney',
 'zest money',
 'zeroinfy',
 'zeppery',
 'zepo',
 'zeolr/respiron',
 'zenradius',
 'zenparent',
 'zenoti',
 'zenify',
 'zendrive',
 'zenatix',
 'zefo',
 'zebroads',
 'zebpay',
 'zebi (yet to launch)',
 'zarget',
 'zapyle',
 'zapty',
 'zapstitch',
 'zapr',
 'zappka',
 'zappfresh',
 'zapluk',
 'zakoopi',
 'yuvi hospitality',
 'yupp tv',
 'yumlane',
 'yumist',
 'yumigo',
 'yulu bikes',
 'yufta',
 'youthkiawaaz',
 'yourstory',
 'yourdost',
 'your quote',
 'yottaasys',
 'yostra',
 'yolo health',
 'yogurt labs',
 'yo grad',
 'yepme',
 'yellowdig',
 'yatragenie',
 'yatra',
 'yana',
 'yaap',
 'yaantra',
 'xstok',
 'xseed education',
 'xpressbees',
 'xprep',
 'xcode',
 'wydr',
 'wwhere',
 'wudstay',
 'wowflux',
 'wowexpress',
 'wow! momo',
 'wow express',
 'wotu',
 'world art community',
 'workindia',
 'workhorse',
 'workapps',
 'wooplr',
 'woodpie',
 'wonobo',
 'wonderchef',
 'wizrocket',
 'wizcounsel',
 'wiwigo',
 'witworks',
 'wittyparot',
 'wittyfeed',
 'withme',
 'wishup',
 'wishberry',
 'wired hub',
 'wimwi foods',
 'wigzo',
 'wickedride',
 'whoop',
 'wholesalebox',
 'whodat',
 'white owl brewery',
 'wheelstreet',
 'whatsonrent',
 'whatsloan',
 'whats up life',
 'whatfix',
 'wetravelsolo',
 'wellthy',
 'welcome cure',
 'wefly indoor skydiving',
 'wedwise',
 'wedosky',
 'wedmegood',
 'weddingz',
 'wedding wishlist',
 'webengage',
 'weballigator',
 'weareholidays',
 'wealthy',
 'wealthtrust',
 'wealthbucket',
 'wealthapp',
 'wayforward',
 'waycool',
 'wassup',
 'wandertrails',
 'vyomo',
 'vyome therapeutics inc.',
 'vyome biosciences',
 'vymo',
 'vyapar app',
 'vtion',
 'vst travels',
 'vserv',
 'vphrase analytics',
 'voylla',
 'voxweb',
 'vow car clinic',
 'voonik',
 'voodoo',
 'volta motors',
 'volt',
 'voler cars',
 'vola',
 'voice friends',
 'vogo automotive',
 'vogo',
 'vlurn',
 'vivocarat',
 'vithi',
 'vistaar finance',
 'vista rooms',
 'visit',
 'virtual logic',
 'violetstreet',
 'vimmune',
 'villgro',
 'villfarm',
 'vidooly',
 'vidgyor',
 'video ken',
 'vertuals',
 'vernacular',
 'veritas finance',
 'verayu',
 'veqta',
 'venturesity',
 'venture catalysts',
 'velvetcase',
 'velmenni',
 'vehico',
 'vegfru',
 'vegetall',
 'veeba foods',
 'vedantu',
 'vebbler',
 'vdeliver',
 'vayana',
 'varthana',
 'vanitycube',
 'vanitycask',
 'vanity cube',
 'vahdam teas',
 'vahdam tea',
 'vahanalytics',
 'vahan',
 'vagupu',
 'v resorts',
 'utoo cabs',
 'urjas',
 'urdoorstep',
 'urbanpro',
 'urbanpiper',
 'urbanladder',
 'urbanclap technologies',
 'urbanclap',
 'urban tailor',
 'urban ladder',
 'urban dhobi',
 'upwards',
 'upwardly',
 'unocoin',
 'unnati helpers',
 'unlaze',
 'universal sportsbiz',
 'uniphore',
 'unilog',
 'uniken',
 'underdogs',
 'uncanny vision',
 'unbxd',
 'unacademy',
 'unaacademy',
 'ue lifesciences',
 'ue life sciences',
 'udaan',
 'uclid',
 'uclean',
 'uber dreams',
 'uactive',
 'tyre express',
 'tynor othontics',
 'tygr',
 'tydy',
 'twyst',
 'twigly',
 'twenty two motors',
 'turtlemint',
 'truxapp',
 'truweight',
 'trupay',
 'trulymadly',
 'truly social',
 'trukky',
 'truelancer',
 'truehb',
 'truebil',
 'true north',
 'true balance',
 'trucksfirst',
 'truckola',
 'truckmandi',
 'truckingcube',
 'truce',
 'tripshelf',
 'tripoto',
 'triphobo',
 'tripfactory',
 'tripeur',
 'trip38',
 'trip tap toe',
 'trip shelf',
 'tring',
 'trilyo',
 'tricog',
 'trendieapp',
 'trell',
 'treebo',
 'travelyaari',
 'traveltriangle',
 'travelspice',
 'travelkhana',
 'travel triangle',
 'transversal technologies',
 'transtutors / askiitians',
 'transerve',
 'transerv',
 'transcell',
 'trak n tell',
 'trading bells',
 'tradelab',
 'tracxn',
 'trackbizz',
 'tpot',
 'townscript',
 'townrush',
 'town essentials',
 'touchkin',
 'torqus',
 'tork motocycles',
 'toprankers',
 'toppr',
 'tooler',
 'tookitaki',
 'tonetag',
 'tone tag',
 'tonbo imaging',
 'tokri',
 'toko innovations',
 'toko innovation studios',
 'toflo',
 'toffee',
 'tiyo',
 'tinystep',
 'tinyowl',
 'tinmen',
 'timesaverz',
 'timemytask',
 'tilite technologies',
 'ticketnew',
 'thrill app',
 'thirdwatch',
 'thinkphi',
 'thinkerbell',
 'thesmartq',
 'theranosis',
 'thekarrier',
 'thecapitalnet',
 'thebetterindia',
 'the/nudge foundation',
 'the wedding brigade',
 'the viral fever',
 'the uolo',
 'the print',
 'the postbox',
 'the porter',
 'the office pass',
 'the news minute',
 'the mons co.',
 'the moms co',
 'the man company',
 'the label life',
 'the kettlery',
 'the ken',
 'the indian iris',
 'the home salon',
 'the healthy billions',
 'the gourmet jar',
 'the good life',
 'the bluebook',
 'the better india',
 'thb',
 'testbook',
 'termsheet',
 'teritree',
 'ten3t health',
 'tempogo',
 'tempgo',
 'telr',
 'teewe',
 'team indus',
 'teabox',
 'tea trails',
 'tea box',
 'tazzo bikes',
 'taxsutra',
 'taxivaxi',
 'tax2win',
 'tavaga',
 'tata housing',
 'taskbucks',
 'taskbob',
 'tarusa world',
 'tapzo',
 'tapcibo',
 'tapchief',
 'talkoot',
 'talentrack',
 'talentedge',
 'talent next',
 'tala',
 'tailslife',
 'tails life',
 'tagos design',
 'tagbox',
 'tac security',
 'tablehero',
 'systemantics',
 'syona cosmetics',
 'synup',
 'synctag',
 'switchme',
 'swiggy',
 'swajal',
 'supr daily',
 'supplified',
 'superhero brands',
 'supergaming',
 'sunterrace',
 'sunstone eduversity',
 'sunday realty solutions',
 'summerlabel',
 'sumeru',
 'sulekha',
 'stylofie',
 'stylflip',
 'styletag',
 'styledotme',
 'stylecracker',
 'stumagz',
 'stuffed',
 'strike',
 'stridalyzer',
 'streo',
 'streamoid',
 'streak',
 'stratfit',
 'strata enviro',
 'storemore',
 'storeking',
 'stockroom',
 'stockal',
 'stitchwood',
 'stellaps',
 'stelae',
 'stayzilla',
 'stayology',
 'stayglad',
 'staydobe',
 'stayabode',
 'stay simple resorts',
 'stasis labs',
 'stashfin',
 'startup buddy',
 'staqu',
 'stanza living',
 'stanplus',
 'stalkbuylove',
 'stalk buy love',
 'stage 3',
 'square yards',
 'squadrun',
 'sqqrl',
 'springleap',
 'springboard',
 'spotdraft',
 'sportzvillage',
 'sportybeans',
 'sports flashes',
 'sportobuddy',
 'sportido',
 'sport flashes',
 'spoonjoy',
 'splitkart',
 'spinny',
 'spiderg',
 'speedbox',
 'spectravr',
 'specsmakers',
 'spareshub',
 'spares hub',
 'spandana sphoorty',
 'sp robotics',
 'soundsurround',
 'soothe healthcare',
 'soopermo',
 'solartown',
 'sokrati',
 'social quotient',
 'snapshopr',
 'snapdeal',
 'snapbizz',
 'snackible',
 'smytten',
 'sminq',
 'smecorner',
 'smartvizx',
 'smartron',
 'smartpocket',
 'smartivity',
 'smarthi',
 'smartcooky',
 'smartcoin',
 'smartairtrip',
 'smart karma',
 'smaaash',
 'slide app',
 'slice pay',
 'slang labs',
 'skycandle',
 'sky met weather',
 'skoov',
 'skillenza',
 'skillbox',
 'skillate',
 'skillangels',
 'skill connect',
 'skedool',
 'sistema.bio',
 'sirionlabs',
 'simulanis',
 'simplotel',
 'simplilend',
 'simplilearn',
 'simpli5d',
 'simility',
 'silverpush',
 'silvan innovation labs',
 'silvan',
 'sillymonks',
 'sigtuple',
 'sigrid education',
 'signzy',
 'siftr labs',
 'sidqam',
 'sibia analytics',
 'shuttl',
 'shubhloans',
 'shubh loans',
 'shouut',
 'shotang',
 'shopx',
 'shopwati',
 'shopsup',
 'shopsity',
 'shopsense',
 'shoppinpal',
 'shopkirana',
 'shopholix',
 'shopclues',
 'shopatplaces',
 'shopalyst',
 'shop 101',
 'shoekonnect',
 'shirsa labs',
 'shipsy',
 'shippr',
 'shilpmis',
 'shethepeople',
 'sheroes',
 'sharechat',
 'shape',
 'shadowfox',
 'shadowfax',
 'shabdnagari',
 'shabdanagari',
 'shaadisaga',
 'setu',
 'sesame software',
 'servx',
 'servify',
 'servd',
 'sequretek',
 'sepalika',
 'sensegiz',
 'sensara',
 'seniority',
 'selectjobs',
 'seenit',
 'seedoc',
 'seed schools',
 'secururax',
 'securens',
 'seclore',
 'scripbox',
 'scoutmytrip',
 'scootsy',
 'scoopwhoop',
 'scienaptic',
 'schoolwear',
 'schoolkart',
 'schoolguru',
 'schedulers logistics',
 'scapic',
 'scandid',
 'sayfix',
 'savvymob',
 'savebc',
 'satvakart',
 'satvacart',
 'sattviko',
 'sastasundar',
 'saral designs',
 'samunnati financial intermediation & services',
 'samunnati',
 'sampurnearth',
 'samosa labs',
 'samco',
 'sambandh',
 'salebhai',
 'sahayog dairy',
 'sahajanand medical technologies',
 'sagacito',
 'safetykart',
 'sabse',
 'saavn',
 'saama',
 'saahas zero waste',
 's-cube futuretech',
 's chand',
 'rupeek',
 'rupaiya exchange',
 'runnr',
 'rubix',
 'rubique',
 'rozgar mela',
 'routofy',
 'round one',
 'roposo',
 'rooter',
 'rootefy',
 'roomstonite',
 'roomcentral',
 'room on call',
 'rollmafia',
 'roll mafia',
 'roder',
 'rocketium',
 'rock n shop',
 'robovac',
 'robosoft',
 'roast',
 'roambee',
 'roadrunnr',
 'roadgods',
 'roadcast',
 'rml agtech',
 'rksv',
 'rivigo',
 'ridlr',
 'revx',
 'revv',
 'reverie',
 'retigence technologies',
 'retention',
 'restate',
 'ressy',
 'repup',
 'reportbee',
 'repaireasy',
 'rentsher',
 'rentongo',
 'rentomojo',
 'rentomo',
 'rentmojo',
 'rentickle',
 'rentalpha',
 'renowala',
 'renomania',
 'reniso',
 'renewbuy',
 'renew buy',
 'renderlogy',
 'remitr',
 'remit guru',
 'remidio',
 'rein games',
 'reglobe',
 'register my marriage',
 'refiral',
 'redsun telematics',
 'redpolka',
 'redesyn',
 'reddoorz',
 'redbook',
 'red carpet',
 'recykal',
 'realbox',
 'reach',
 'rbus',
 'razorpay',
 'rayiot',
 'rawpressery',
 'raw pressery',
 'rategain',
 'rare media',
 'rapido bike taxi',
 'rapido',
 'rao iit academy',
 'raincan',
 'railyatri',
 'qyk app',
 'qyk',
 'qwikspec',
 'quizizz',
 'quintype',
 'quinto',
 'quikwallet',
 'quikr',
 'quifers',
 'quickli',
 'qubole',
 'qriyo',
 'qorqi',
 'qonfuse',
 'qlivery',
 'qikship',
 'qikpod',
 'qik stay',
 'qdesq',
 'qacco',
 'purplle',
 'purplehealth',
 'purpledocs',
 'purple style labs',
 'purple squirrel',
 'puro wellness',
 'pumpkart',
 'pulse',
 'prozo',
 'proximit',
 'proviera',
 'prothom',
 'propstory',
 'propstack',
 'prophesee',
 'propertyshare',
 'promon',
 'project mudra',
 'progcap',
 'procmart',
 'process 9',
 'printvenue',
 'printland',
 'prime focus technologies',
 'primaseller',
 'primaryio',
 'priceraja',
 'pricejugaad',
 'prettysecrets',
 'prest loans',
 'pressplay tv',
 'pressplay',
 'prescribez',
 'prepathon',
 'pregbuddy',
 'predible health',
 'pratilipi',
 'pramati',
 'pragmatix',
 'practo',
 'pparke',
 'powerstores',
 'power2sme',
 'postman',
 'postergully',
 'poshtic',
 'portea medical',
 'portea',
 'portdesk',
 'popxo',
 'policybazaar',
 'policy bazaar',
 'pokkt',
 'pocketin',
 'pocket aces',
 'pluss',
 'plix',
 'plick',
 'plexusmd',
 'playsimple',
 'playment',
 'playablo',
 'play your sport',
 'planys technologies',
 'planmy\\\\nmedicaltrip',
 'planetgogo',
 'plancess',
 'placeoforigin',
 'plabro',
 'pitstop',
 'piqube',
 'pipecandy',
 'pipabella',
 'pipa bella',
 'pinkblue',
 'ping digital',
 'pinelabs',
 'pine labs',
 'pindropmusic',
 'pinclick',
 'pikkol',
 'pictor imaging',
 'picsdream',
 'pickrr',
 'pickmylaundry',
 'pickme',
 'pickingo',
 'pianta',
 'pi ventures',
 'pi data centers',
 'phonepe',
 'phone warrior',
 'phone pe',
 'pharmeasy',
 'pharmarack',
 'petsutra',
 'petoo',
 'perspectico',
 'perpule',
 'perfumery',
 'perfios',
 'peppertap',
 'pepperfry',
 'peesafe',
 'peel works',
 'peebuddy',
 'paytunes',
 'paytm marketplace',
 'paytm',
 'paysense',
 'paynear',
 'paymango',
 'patel logistics',
 'pastiwala',
 'park easy',
 'parentune',
 'parentlane',
 'parcelled',
 'parallel dots',
 'parablu',
 'paperflite',
 'paper boat',
 'pandorum technologies',
 'pando',
 'paisawapas',
 'paisadukan',
 'paintcollar',
 'padhopadhao',
 'paalak',
 'oyorooms',
 'oyofit',
 'oyo rooms',
 'oyo',
 'oybob',
 'overcart',
 'ouwt',
 'oust app',
 'orobind',
 'origo commodities india',
 'origa leasing',
 'oriano solar',
 'organicshop',
 'orangetwig',
 'orahi',
 'optacredit',
 'opinio',
 'opentap',
 'openapp',
 'oorjan',
 'onspoon',
 'onn bikes',
 'onlinetyari',
 'onlinerti',
 'oneway.cab',
 'onestepup',
 'oneclickwash',
 'oneassist',
 'one labs',
 'oncostem',
 'omnikart',
 'omnify',
 'omnia information',
 'olly credit',
 'oliveboard',
 'olacabs',
 'ola electric',
 'ola cabs',
 'ola',
 'okcredit',
 'oibanit',
 'oi media',
 'oho shop',
 'oglas',
 'ofbusiness',
 'octo',
 'observe ai',
 'obino',
 'nykaa',
 'nxtgen',
 'nuvepro',
 'nurturey',
 'numeroseven',
 'numberz',
 'numbermall',
 'nukkad shops',
 'nudgespot',
 'nowfloats',
 'notion press',
 'noticeboard',
 'notesgen',
 'notary mama',
 'northmist',
 'nopaperforms',
 'noodle play',
 'noddapp',
 'nobroker',
 'niyo solutions',
 'nivesh',
 'nirogstreet',
 'niramai',
 'ninjacart',
 'nimble wireless',
 'niki',
 'nightstay',
 'niffler',
 'nextgen',
 'newspatrolling',
 'newslaundry',
 'newsinshorts',
 'newshunt',
 'newsdistill',
 'news in shorts',
 'newgen software',
 'newgen payments',
 'new castle technologies',
 'neurosynaptic',
 'neuroequilibrium',
 'network intelligence',
 'netree',
 'netmeds',
 'netlinx',
 'nestaway',
 'nest education',
 'neotrade analytics',
 'neostencil',
 'neogrowth credit',
 'neogrowth',
 'nearu',
 'nearfox',
 'nearbuy (previously groupon india)',
 'nearbuy',
 'near',
 'ndtv wedding portal',
 'ndtv ecommerce venture',
 'nazara technologies',
 'nayi disha',
 'navia life care',
 'naturenama',
 'naturally yours',
 'native special',
 'narvar',
 'nanoclean global',
 'nagpur wholesale',
 'nactus',
 'naaptol',
 'n.o.w',
 'myupchar',
 'mytaxiindia',
 'mysuperbrain',
 'mysun',
 'mystifly',
 'mysmartprice',
 'myseniordoctor',
 'myra',
 'mypoolin',
 'mypetrolpump',
 'myonsto',
 'mynoticeperiod',
 'myly',
 'myloancare',
 'mykindofjob',
 'myindianstay',
 'mygubbi',
 'mygreens',
 'myglamm',
 'myelin foundry',
 'myeglu',
 'mydreamstore',
 'mydidi',
 'mydermacy',
 'mydentistchoice',
 'mydentist',
 'mycuteoffice',
 'mycity4kids',
 'mychild app',
 'mycfo',
 'myadvo',
 'my omnamo',
 'my healthcare',
 'my forex eye',
 'muvizz',
 'murgency',
 'multiplier solutions',
 'multibhashi',
 'muhurtmaza',
 'mubble',
 'mswipe',
 'msm box',
 'mshipper',
 'mse',
 'mrneeds',
 'mr hot foods',
 'mpaani',
 'motomojo',
 'mosambee',
 'moovo',
 'moong labs',
 'moonfrog labs',
 'moodoo',
 'monsoon fintech',
 'monkeybox',
 'moneytap',
 ...]

In [68]:
fund['startup_clean'] = fund['startup'].astype(str).str.lower().str.strip()

In [69]:
len(fund['startup_clean'].unique())

2307

In [70]:
import difflib
unique_names = fund['startup_clean'].unique().tolist()
auto_corrections = {}
false_corrections = {
    "mengage": "Health-tech platform (doctor-patient apps)",
    "moengage": "AI-powered customer engagement & marketing SaaS",

    "91springboard": "Co-working space provider network in India",
    "springboard": "Online mentor-led Ed-tech platform for tech careers",

    "fpl technologies": "Fintech company behind OneCard & OneScore",
    "fyle technologies": "Expense management automation SaaS platform",

    "transerv": "Fintech company providing digital payment APIs",
    "transerve": "Location intelligence & urban geospatial SaaS software",

    "dhruva": "Dhruva Interactive (Legendary Indian gaming studio)",
    "druva": "Silicon Valley-based cloud data protection unicorn",

    "uactive": "Social networking app for sports & fitness enthusiasts",
    "active": "Active.ai (Conversational AI banking platform)"
}
for name in unique_names:
    # if name in false positive skip processing
    if name in false_corrections:
        continue
    matches = difflib.get_close_matches(name,unique_names,n=2,cutoff=0.90)
    
    if len(matches)>1:
        twin=matches[1]
        # to ensure twin is not in false positive
        if twin in false_corrections:
            continue
        if len(name) < len(twin):
            auto_corrections[twin]=name
        else:
            auto_corrections[name]=twin
fund['startup_clean'] = fund['startup_clean'].replace(auto_corrections)

In [71]:
len(fund['startup_clean'].unique())

2224

In [72]:
fund.sample(30)

,date,startup,vertical,subvertical,city,investors,round,amount,startup_clean
Sr No,,,,,,,,,
2580,2015-07-03,goqii,Mobile Fitness Marketplace,NaN,Mumbai,Vijay Shekhar Sharma,Private Equity,0.00,goqii
703,2017-07-18,hypernova interactive,Technology,Mobile games creator,Bangalore,Kae Capital,Seed Funding,0.00,hypernova interactive
1110,2017-01-30,cloudrino,Technology,Cloud based Virtual Servers,New Delhi,The Ten Minute Million,Seed Funding,0.22,cloudrino
2850,2015-04-22,avanti learning,Private Coaching Centers,NaN,New Delhi,"Michael & Susan Dell Foundation, Pearson Learn...",Private Equity,14.35,avanti learning
3008,2015-01-12,verayu,NaN,NaN,NaN,"GWB Group, Blume Ventures",Private Equity,0.00,verayu
1962,2016-02-16,tring,Consumer Internet,Instant Messaging App,Pune,Vishwadeep Bajaj & Others,Seed Funding,0.00,tring
338,2018-03-19,customersucessbox,Technology,Customer Success Software for B2B SaaS,Gurugram,"Pi Ventures, Axilor Ventures",Seed / Angel Funding,9.57,customersucessbox
1419,2016-08-02,daily ninja,Consumer Internet,Hyperlocal daily needs Products delivery platform,Bangalore,"Venk Krishnan, Aprameya Radhakrishna, Anupam M...",Seed Funding,0.00,dailyninja
1877,2016-03-19,gosporto,Consumer Internet,Online Sports discovery and booking platform,New Delhi,Naveen Gupta,Seed Funding,0.29,gosporto
2236,2015-11-16,absentia,Virtual Reality Headset creator,NaN,Bangalore,"Astarc Ventures, 50K Ventures & others",Seed Funding,1.72,absentia
3039,2015-01-28,grabhouse,NaN,NaN,NaN,"Kalaari Capital, Sequoia Capital",Private Equity,23.92,grabhouse
2058,2016-01-18,kartrocket,Consumer Internet,SAAS DIY\\xc2\\xa0 ECommerce Platform,New Delhi,"Bertelsmann India Investments, Nirvana Digital...",Private Equity,57.40,kartrocket
1437,2016-08-11,91springboard,Consumer Internet,Co-Working Spaces Discovery & Booking platform,Mumbai,"Khattar Holdings, ThirtyThree Investments, Sou...",Private Equity,0.00,91springboard
2608,2015-07-10,footprints education,\\xc2\\xa0Pre-School Chain,NaN,\\xc2\\xa0Gurgaon,"\\xc2\\xa0LetsVenture, Kumar Bansal, Kshitij Jain",Seed Funding,6.55,footprints education
1262,2016-10-03,helpchat,Consumer Internet,AI Powered Content & Commerce platform,Bangalore,"American Express Ventures, Sequoia Capital",Private Equity,0.00,helpchat
376,2018-02-15,infibeam,E-Commerce,Online Retailing,Ahemadabad,Network 18,Private Equity,59.60,infibeam
2094,2016-01-28,zebi (yet to launch),Technology,Data Intelligence & Analytics,Hyderabad,Un disclosed investors,Seed Funding,9.57,zebi (yet to launch)
2030,2016-01-08,flatfurnish,Consumer Internet,Online Furnishing Rental Platform,Gurgaon,Arun Chandra Mohan,Seed Funding,0.00,flatfurnish
714,2017-07-26,creators gurukul,Others,Co-Working Space Provider,New Delhi,Yuvraj Singh,Seed Funding,0.00,creators gurukul
1670,2016-05-03,zuver,Consumer Internet,Car driver Discovery App,Mumbai,"Shruth & Smith Group, Hermes Group",Seed Funding,1.72,zuver
233,2018-06-10,ayefinance,Finance,Online Lending Platform,Gurugram,"CapitalG, SAIF Partners and LGT Impact Ventures",Private Equity,205.69,ayefinance
2839,2015-04-16,urbanclap,Hyperlocal Mobile Services Marketplace,NaN,New Delhi,"SAIF Partners, Accel Partners, Kunal Bahl, Roh...",Seed Funding,15.31,urbanclap
3024,2015-01-20,amagi media labs,NaN,NaN,NaN,Premji Invest & Mayfield Fund,Private Equity,0.00,amagi media labs
317,2018-03-01,buddy4studdy,Consumer Internet,Online Scholarship Portal,Noida,CBA Capital and others,Private Equity,28.70,buddy4studdy
1420,2016-08-02,yumlane,Food & Beverage,Retail Food & Snack Offline centres,Mumbai,"Binny Bansal, Anupam Mittal, Sachin Bhatia, Da...",Seed Funding,9.57,yumlane
1650,2016-06-28,lendingkart,Consumer Internet,Online Working Capital Business Loans Platform,Ahmedabad,"Bertelsmann India Investments, Mayfield India,...",Private Equity,306.14,lendingkart
824,2017-05-16,niki,Technology,AI-based chatbot,Bangalore,SAP,Private Equity,0.00,niki
1273,2016-10-04,innerchef,Consumer Internet,Online food ordering platform,Gurgaon,"Mistletoe, M&S Partners",Private Equity,23.92,innerchef
2810,2015-05-30,ather energy,Electric Scooter Manufacturer,NaN,Bangalore,Tiger Global,Private Equity,114.80,ather energy
2038,2016-01-12,hike messenger,Consumer Internet,P2P Messaging Service,New Delhi,"Matt Mullenweg, Adam D\\xe2\\x80\\x99Angelo, A...",Private Equity,0.00,hike messenger

In [73]:
unwanted_char = r"[^a-zA-Z0-9\s-&!.]"
fund[fund['startup_clean'].str.contains(unwanted_char,regex=True)]

,date,startup,vertical,subvertical,city,investors,round,amount,startup_clean
Sr No,,,,,,,,,
1433,2016-08-09,zeolr/respiron,Technology,Healthcare related IoT platform,New Delhi,Centre for Innovation Incubation and Entrepren...,Seed Funding,0.00,zeolr/respiron
1541,2016-07-14,transtutors / askiitians,Consumer Internet,Online Education & Tutoring portals,New Delhi,500 Startups,Private Equity,0.00,transtutors / askiitians
1554,2016-07-19,deal4loans / wishfin,Consumer Internet,\\nLoans Comparison platform\\n\\n\\n\\n (...,Noida,Franklin Templeton International Services Pvt....,Private Equity,143.50,deal4loans / wishfin
2014,2016-01-05,alef\\nmobitech,Consumer Internet,Cloud Mobility Solutions,Mumbai,Tata Capital Innovation Fund,Private Equity,47.84,alef\\nmobitech
2019,2016-01-06,planmy\\nmedicaltrip,Healthcare,Medical Tourism platform,Pune,"Bhanu Vikram Parsotam, Rohan Desai and Paras P...",Seed Funding,1.44,planmy\\nmedicaltrip
2094,2016-01-28,zebi (yet to launch),Technology,Data Intelligence & Analytics,Hyderabad,Un disclosed investors,Seed Funding,9.57,zebi (yet to launch)
2406,2015-09-10,the/nudge foundation,Non Profit Organization to alleviate poverty,NaN,Bangalore,"Nanadan Nilekani, InMobi, Paytm",Seed Funding,3.01,the/nudge foundation
2505,2015-08-10,nearbuy (previously groupon india),Hyper-Local Ecommerce,NaN,New Delhi,Sequoia Capital,Private Equity,153.07,nearbuy (previously groupon india)
2654,2015-07-29,zovi / little app,Hyperlocal Deals Marketplace,NaN,Bangalore,"Paytm, SAIF Partners,\\xc2\\xa0 Tiger Global M...",Private Equity,478.35,zovi / little app
2845,2015-04-20,1mg (healthkartplus),Online Pharmacy & Drug DB,NaN,Gurgaon,"Deep Kalra, Sequoia Capital, Omidyar Network, ...",Private Equity,57.40,1mg (healthkartplus)
2881,2015-03-09,crowdfire (formerly justunfollow),NaN,NaN,NaN,Kalaari Capital,Private Equity,23.92,crowdfire (formerly justunfollow)
2993,2015-01-05,#fame,NaN,NaN,NaN,TO THE NEW Ventures,Private Equity,95.67,#fame

In [74]:
# now focus on the investor column
fund['investor_clean'] = fund['investors'].str.lower().str.strip()

In [75]:
unwanted_char = r"[^a-z0-9\s-&!.,()]"
fund[fund['investor_clean'].str.contains(unwanted_char,regex=True)]['investor_clean']

Sr No
113     india quotient and letsventure\\xe2\\x80\\x99s...
117     sequoia india, hillhouse capital, alphabet\\xe...
128     norwest venture partners, cdc group, the uk\\x...
142     lakestar and jungle ventures, softbank\\xe2\\x...
153     dst global and lightspeed venture partners\\xe...
158                                        kddi\\xc2\\xa0
161     clp holdings group, innogy, \\xc3\\x98rstead, ...
164     vertex ventures southeast asia (sea) and india...
183                               cdc group plc\\xc2\\xa0
405     sunil kant munjal, hero electronix\\xe2\\x80\\...
465                "kedaraa capital, ontario teachers\\'"
483     titan co ltd, tata group\\xe2\\x80\\x99s watch...
649                                    factor[e] ventures
661                       undisclosed hni\\xe2\\x80\\x99s
673     accel partners, idg ventures, kalaari capital,...
792       falcon edge capital,\\xc2\\xa0 capital advisers
810     vellayan subbiah, jonathan boutelle, rajan ana...
843            lahiri music\\xe2\\x80\\x99s family office
875                             labruyere eberl\\xc3\\xa9
879     accel partners, nandan nilekani\\xe2\\x80\\x99...
969                              l\\xe2\\x80\\x99occitane
995     b capital group, ignition partners, greycroft,...
1074    tencent,\\xc2\\xa0 ru-net, rsi fund, thrive ca...
1100    sharad sharma, rajan anandan,\\xc2\\xa0 amit r...
1132    venk krishnan, mj aravind, vikram kotak, jayan...
1167    indian angel network, let\\xe2\\x80\\x99s venture
1187           rb investments,\\xc2\\xa0 kaleden holdings
1233    delta partners, sequoia india,\\xc2\\xa0 mayfi...
1272    vijay shekhar sharma, pravin gandhi,\\xc2\\xa0...
1290    growx ventures, sunil kalra, arun venkatachala...
1301    bytedance, arun sarin, matrix partners, sequoi...
1351    venturra capital, sequoia india, susquehanna i...
1374    dheeraj jain, palash jain, anupam mittal, amee...
1470    blume ventures, sachin bansal, vijay shekhar s...
1481    globevestor angel fund, devendra rane, ravi ja...
1511               yournest angel fund\\xc2\\xa0 & others
1513    sequoia capital, rohit bansal, kunal bahl, san...
1528              mumbai angels,\\xc2\\xa0 times internet
1753                             l\\xe2\\x80\\x99occitane
1825    kludein llc\\nphanindra sama, narayan ramachan...
1892    bhavish aggarwal, binny bansal,\\xc2\\xa0 raja...
1906             wipro ventures,\\xc2\\xa0 lumis partners
1907            t v mohandas pai,\\xc2\\xa0 aarin capital
1950    aspada advisors, idg ventures,\\xc2\\xa0 inven...
1951    ontario teachers\\xe2\\x80\\x99 pension plan &...
1956                blume ventures,\\xc2\\xa0 tracxn labs
1987    omidyar network,\\xc2\\xa0 vikram lal, abhijit...
2017    lalitesh katragadda,\\xc2\\xa0 ganayantrika sy...
2022                             myntra/livspace founders
2038    matt mullenweg, adam d\\xe2\\x80\\x99angelo, a...
2053    hyderabad angels, lalit mangal,\\xc2\\xa0 vika...
2063    unilazer fund,\\xc2\\xa0 phanindra sama, peyus...
2071             sa\\xc3\\xafd business school seed fund.
2116    lashit sanghvi, nikhil vora, venkat vardhan,mo...
2129    ru-net, sequoia capital,\\xc2\\xa0 lightbox ve...
2154    extreme venture partners\\xc2\\xa0 william bis...
2202    segnel venture, shinji kimura, sundar chanrai,...
2221    rajan anandan, mike galgon, ravi gururaj, ashi...
2228        tv mohandas pai\\xe2\\x80\\x99s family office
2254    s.d. shibulal, kris gopalakrishnan, srinath ba...
2264    idg ventures india,\\xc2\\xa0 accel partners i...
2284    manish kheterpal, alok mittal,\\xc2\\xa0 punee...
2313       sanjeev kapoor,\\xc2\\xa0 ravi saxena & others
2325               sean o\\xe2\\x80\\x99sullivan & others
2392    westbridge capital, omidyar network, elevar eq...
2477    softbank group, greenoaks capital, sequoia cap...
2494    horizons ventures, capricorn investment group,...
2518    amit ranjan, vijay shekhar sharma, kunal bahl,...
2603                               \\xc2\\xa0tiger global
2604    \\xc2\\xa0ivycap ventures, accel partners, dra...
2605           \\xc2\\xa0 sandeep aggarwal, teruhide sato
2606    \\xc2\\xa0rajeev saraf, arvind jha, r. satya n...
2607                       \\xc2\\xa0indian angel network
2608    \\xc2\\xa0letsventure, kumar bansal, kshitij jain
2609                            \\xc2\\xa0indianideas.com
2610                    \\xc2\\xa0forum synergies pe fund
2611                              \\xc2\\xa0goldman sachs
2612                           \\xc2\\xa0palaash ventures
2646             growx ventures,\\xc2\\xa0 manish singhal
2652    idg ventures india, omidyar network, sherpalo ...
2654    paytm, saif partners,\\xc2\\xa0 tiger global m...
2662    youwecan ventures,\\xc2\\xa0 aprameya radhakri...
2684    sharad sharma, rajan anandan, sunil kalra, ami...
2689    tiger global,\\xc2\\xa0 nirvana ventures advisors
2694    natarajan iyer,rajesh sawhney,\\xc2\\xa0 & oth...
2703    arihant patni, vishal khare,\\xc2\\xa0 viswana...
2722               group of angel investors from us/india
2744              saif partners,\\xc2\\xa0 accel partners
2767    fidelity growth partners india, saif partners,...
2777          rajendra gogri,\\xc2\\xa0 chandrakant gogri
2819    silicon valley ventures, nea ventures, valiant...
2822    ajai chowdhry, ashvin chadha, yogesh bansal,\\...
2861    ah! ventures, calcutta angels,\\xc2\\xa0 91spr...
2892              ventureeast,\\xc2\\xa0 varaprasad reddy
2906                  ca media lp,\\xc2\\xa0 start media.
2933    zodius capital, ru-net, kalaari capital,\\xc2\...
2979    unitus seed fund\\nnarayan ramachandran, bijou...
Name: investor_clean, dtype: str

In [76]:
# unit test
fund.loc[113,'investor_clean'].replace('\\\\xe2\\\\x80\\\\x99','')

'india quotient and letsventures angel fund'

In [77]:

encoding_fixes = {
    r'\\\\xe2\\\\x80\\\\x99': "'",   # Fixes apostrophes
    r'\\\\xc2\\\\xa0': ' ',         # Fixes non-breaking spaces
    r'\\\\xc3\\\\xa9': 'é',         # Fixes accented é
    r'\\\\xc3\\\\x98': 'Ø'          # Fixes Scandinavian Ø
}

In [78]:
fund['investor_clean'] = fund['investor_clean'].replace(encoding_fixes,regex=True)

In [79]:
unwanted_char = r"[^a-z0-9\s-&!.,()'Øé]"
fund[fund['investor_clean'].str.contains(unwanted_char,regex=True)]['investor_clean']

Sr No
164     vertex ventures southeast asia (sea) and india...
465                "kedaraa capital, ontario teachers\\'"
649                                    factor[e] ventures
1272    vijay shekhar sharma, pravin gandhi,  smart st...
1825    kludein llc\\nphanindra sama, narayan ramachan...
2022                             myntra/livspace founders
2071             sa\\xc3\\xafd business school seed fund.
2494    horizons ventures, capricorn investment group,...
2722               group of angel investors from us/india
2822    ajai chowdhry, ashvin chadha, yogesh bansal,\\...
2979    unitus seed fund\\nnarayan ramachandran, bijou...
Name: investor_clean, dtype: str

In [80]:
fund['investor_clean'] = fund['investor_clean'].astype(str).str.replace(r'\\\\+n', ', ', regex=True)

In [81]:
fund.loc[465,'investor_clean'] = 'kedaraa capital, ontario teachers'

In [82]:
fund.loc[1272,'investor_clean'] = 'vijay shekhar sharma, pravin gandhi,  smart start fund, kunal shah,  sandeep tandon, vishal gondal, others'

In [83]:
fund.loc[2071,'investor_clean'] = 'saïd business school seed fund'

In [84]:
fund.loc[2022,'investor_clean'] = 'Mukesh Bansal, Anuj Srivastava, Ramakant Sharma'

In [85]:
fund.loc[2494,'investor_clean'] ='horizons ventures, capricorn investment group, social capital, helion advisors, berggruen holdings'

In [86]:
fund.loc[2722,'investor_clean'] = 'JKN Partners, JK Patel, Sushil Agarwal, Kalpesh Shethia, Rajeev Mudumba, Dinesh Tadepalli, Sudheshna Vuppala'

In [87]:
fund[fund['investor_clean'].str.contains('and',case=False)]

,date,startup,vertical,subvertical,city,investors,round,amount,startup_clean,investor_clean
Sr No,,,,,,,,,,
12,2019-12-17,healthians,B2B-focused foodtech startup,Food Solutions For Corporate,Bengaluru,"Paytm, NPTK, Sabre Partners and Neoplux",Series C,114.80,healthians,"paytm, nptk, sabre partners and neoplux"
16,2019-12-11,rein games,Gaming,Real money based gaming startup,Noida,Manipal Education and Medical Group (MEMG),Seed Round,478.35,rein games,manipal education and medical group (memg)
20,2019-11-13,sunstone eduversity,Education,Elearning,Gurgaon,"Prime Venture Partners, LetsVenture, PS1 Ventu...",Seed,14.35,sunstone eduversity,"prime venture partners, letsventure, ps1 ventu..."
31,2019-11-19,furtados school of music,Education,Music Education,Tulangan,IAN Fund and DSG Consumer Partners,NaN,1913.40,furtados school of music,ian fund and dsg consumer partners
43,2019-09-04,goqii,Health and Wellness,Wearable Fitness Bands,Menlo Park,Bennett Coleman and Company Ltd (BCCL),Series C,4305.15,goqii,bennett coleman and company ltd (bccl)
...,...,...,...,...,...,...,...,...,...,...
2982,2015-02-25,taxsutra,NaN,NaN,NaN,"V Balakrishnan, T V Mohandas Pai",Seed\\nFunding,1.53,taxsutra,"v balakrishnan, t v mohandas pai"
2992,2015-01-05,lookup,NaN,NaN,NaN,"DeNA Co., Japan & Teruhide Sato (in Addition t...",Seed\\nFunding,3.64,lookup,"dena co., japan & teruhide sato (in addition t..."
2995,2015-01-06,near,NaN,NaN,NaN,"Anupam Mittal, Manish Vij, Prashant Tandon, Ga...",Seed Funding,2.73,near,"anupam mittal, manish vij, prashant tandon, ga..."
3010,2015-01-13,appvirality,NaN,NaN,NaN,"Rajan Anandan, Mike Galgon, Ashim Mehra, Mohit...",Seed Funding,0.00,appvirality,"rajan anandan, mike galgon, ashim mehra, mohit..."
3012,2015-01-15,wishberry,NaN,NaN,NaN,"Rajan Anandan, Shankar Mahadevan, Deep Kalra &...",Seed Funding,6.22,wishberry,"rajan anandan, shankar mahadevan, deep kalra &..."

In [88]:
set(fund['investor_clean'].str.split(r',\s*|\s+\band\b\s+').sum())

{'',
 'vinod singhal',
 'hr technology fund',
 'sanjiv mittal',
 'manish kheterpal',
 'kanpur angels & others',
 'multiple investors',
 'lion ventures',
 'satish vasudeva',
 '3one4 capital advisors llp',
 'and endiya partners.',
 'alto partners',
 'responsability investments',
 'tamarind family private trust',
 'investment ab kinnevik',
 'mumbai angels & other angel investors',
 'dr. ritesh malik',
 'rahul agarwal',
 'alpha capital',
 'idg ventures & indian angel network',
 'tiger global & other investors',
 'milind sarwate',
 'makemytrip',
 'sateesh andara & others',
 'janak jain',
 'evc ventures',
 'bhavesh manglani',
 'govind rajan & others',
 'korea investment partners',
 'Ørstead',
 'purvi capital',
 'zop smart',
 'dmg information',
 'singularity holdings',
 'nasper',
 'beenextan investment fund',
 'yogesh misra',
 'deepak shahdadpuri',
 'undisclosed investors',
 'orbimed',
 'tennenbaum capital partners & others',
 'm&s partners',
 'axis capital',
 'prototyze',
 'harvard angels',
 'rvcf',
 'atul agarwal',
 'shailesh singh',
 'rakesh mathur',
 'barkawi holdings gmbh',
 'allcargo logistics',
 'shashank bhagat',
 'ruizheng investment',
 'tvs automobile solutions ltd',
 'thomas assessments',
 'sidharth rozario',
 'amit rathore',
 'sandeep tandon',
 'anubhav verma',
 'ruchi sanghvi & others',
 'group of undisclosed angel investors & hnis',
 'unnamed media house',
 'swastika company ltd.',
 'cerracap',
 'wealth first',
 'intelli reboot digital pvt. ltd',
 'yang shu',
 'anoop hingorani',
 'rajesh bhatia',
 'dr mushtaq shah',
 'sarbvir singh',
 'equanimity venture fund',
 'factor[e] ventures',
 'sumit jain',
 'girnar software',
 'dr paresh doshi',
 'oliphans capital',
 'nirmal singh',
 'bharat kedia',
 'ashvin chadha',
 'professor tarun khanna',
 'ctrip.com international ltd',
 'rishi khiani',
 'sunrise capital gmbh',
 'vikram mehta',
 'pioneering ventures',
 'sanjay bakshi',
 'great oaks ventures',
 'incofin investment management.',
 'real time ventures',
 'impact investment holding',
 'google capital',
 'manish satnaliwala.',
 'shopclues',
 'abhinav patodia',
 '500 startups & other hnis',
 'apis partners',
 'milliways ventures',
 'madhusudan e',
 'mamoru taniya',
 'amit dey',
 'gwb group',
 'saumya tandon',
 'malvinder',
 'ashish mahajan',
 'robin utthappa',
 'ca media lp',
 'capillary technologies',
 'subramanian ramadorai',
 'cio angel network (can)',
 'cogent e services',
 'jsw ventures',
 'vani kola',
 'lightbridge partners & kairos',
 'unnamed angel investors',
 'rajesh yohanan',
 'horseferry',
 'jain international trade organisation (jito)',
 'deepak ghaisas',
 'e.ventures',
 'mayfield ventures',
 'pablo van den bosch & others',
 'manish amin',
 'r.s sharma',
 'actis',
 'vineet nalla',
 'mustafa wajid',
 'amrish kumar',
 'blume ventures. lenovo capital',
 'horizons ventures',
 'manipal education',
 'ian fund',
 'sprout angels',
 'ranjit singh',
 'amit sinha',
 'deobrat singh',
 'jayant humbarwadi',
 'dr ramesh ayyala',
 'gujarat venture finance limited (gvfl)',
 'moksh sports ventures',
 'milind chaudhary',
 'ameera shah',
 'indian governments',
 'kalpavriksh',
 'songhyun investment',
 'lightspeed & yuri milner',
 'ribbit capital',
 'deepak kulkarni',
 'composite capital management',
 'currae healthtech fund',
 'rakesh jhunjhunwala',
 'undisclosed multiple investors',
 'rajesh ranavat',
 'tracxn labs',
 'bytedance',
 'innoven capital india',
 'ganapathy venugopal.',
 'larry braitman',
 'tano capital',
 'hyderabad angels (at startup heroes event)',
 'sanjay notani & others',
 'plug',
 'sucseed venture partners',
 'karthee madasamay',
 'hillhouse capital',
 'ravi gururaj',
 'nitin singhal & others',
 'imm investment',
 'soma capital',
 'mahindra univeg',
 'pullela gopichand',
 'siddharth agarwal',
 'apurva salarpuria',
 'girish mathrubootham &  group of other angel investors',
 'didi kuaidi',
 'ravi dhariwal',
 'and mas financial services ltd',
 's chand & co',
 'chandigarh angels',
 'ashish tulsian',
 'florintree advisors',
 'new enterprise associates (nea)',
 'ecoenterprise fund',
 'big data investments b.v',
 'hunch ventures',
 'exfinity venture partners',
 'hack vc',
 'rajiv c mody',
 'mayfield',
 'ventureast',
 'idg venture',
 'now capital',
 'ravikanth reddy',
 'fosun international',
 'xiaomi singapore',
 'sanjeev singhal',
 'idfc-parampara fund',
 'ashish goenka & others',
 'reliance capital venture',
 '1crowd (through crowd funding)',
 'incubate fund from japan',
 'lg chandrasekhar',
 'vipul gautam',
 'm george oommen',
 'konglo ventures',
 'triodos',
 'hcs venture capital fund',
 'one97 communication ltd',
 'ravi iyer',
 'sven hensen',
 'aavishkaar',
 'chip perry',
 'piyush jain',
 'kiran shetty',
 'india alternatives',
 'iifl seed ventures fund',
 'ankush mehta',
 'nikunj jain',
 'dr. abhishek pandey',
 'kartik hosanagar',
 'calcutta angels',
 'ajay piramal',
 'vijay ghadge',
 'kk mehra',
 'mdi ventures & telkom indonesia',
 'm&y partners',
 'raghav bahl',
 'anbu pandian',
 'grex',
 'rahul agarwalla',
 'hemang sahani',
 'carrick capital partners',
 'nazara technologies pvt ltd',
 'krishnakumar nataraj',
 'p39 capital & others',
 'devesh sachdev',
 'china lodging group',
 'deepak natraj',
 'vcommission',
 'rahul gautam & others',
 'silo holdings',
 'sequoia capital india advisors',
 'his co. ltd',
 'sar group',
 'saurabh rastogi',
 'company ltd (bccl)',
 'nishant rao',
 'anil chopra',
 'google capital & accel partners',
 'individual investors',
 'raj gala shah',
 'srinath batni',
 'mehul shah',
 'carpediem capital',
 'delta partners',
 'manish gupta',
 'pradeep guha',
 'harminder sahni',
 'nanoholdings',
 'aecal',
 'al nour international holdings',
 'curefit',
 'helion ventures',
 'dilip khandwelwal from sap labs india',
 'anil matai',
 'gaurav sharma',
 'mark mobius & 9 other angel investors',
 'sudhakar pennam',
 'anthill scale ventures',
 'mudit saxena',
 'bennett',
 'frontline strategy',
 'tuscan ventures',
 'ontario teachers',
 'boillot family trust',
 'surot chatterjee',
 'shunwei capital',
 'ambi parameswaran',
 'v. krishna prasad',
 'uday shankar',
 'anuj puri',
 'indian fintech fund',
 'micromax informatics ltd',
 'satish reddy',
 'people group (shaadi.com)',
 'steadview capital',
 'imj investment partners',
 'gaurav bhalotia',
 '3one4 capital advisors',
 'softbank ventures korea',
 'anish k',
 'va sastry',
 'mitsui & co & existing investors',
 'india nivesh growth fund',
 'carpediem capital & others',
 'general catalyst',
 'urrshila kerkar',
 'rainmatter',
 'kalyan krishnamurthy',
 'sashi reddi & other unnamed investors',
 'anuj gupta',
 'riqueza capital',
 'family pot investments llp',
 'elevate sports',
 'real time ventures.',
 'av thomas group',
 'blume ventures & other unnamed investors',
 '3 undisclosed investors',
 'rishi das',
 'undisclosed angel investors & hnis',
 'Anuj Srivastava',
 'fortisure ventures',
 'sandesh kirkire',
 'sierra ventures',
 'cashurdrive marketing pvt ltd',
 'pratithi investment trust',
 'rajasthan angel investor network',
 'subramanya sv',
 'quarizon consultancy services llp',
 'letsventure investors',
 'srinivasa rao paturi',
 'vividhity ventures',
 'vamm ventures',
 'kunal shah & sandeep tandon',
 'parvesh bareja ',
 'yogesh agarwal',
 'quikr',
 'unnamed investor',
 'Kalpesh Shethia',
 'sque capital',
 'rothenberg ventures',
 'rtp-hc',
 'karan bhagat',
 'edelweiss private equity',
 'devry inc',
 'hdfc life',
 'techstars ventures & others',
 'equity crest',
 'rata tata',
 'undisclosed private investors',
 'globallogic co-founder rajul garg',
 'blacksoil capital pvt. ltd.',
 'g ravishankar',
 'om chaudhry',
 'n squared management llc',
 'rajul garg',
 'krishna jhunjhunwaala',
 'existing investors',
 'ruchirans jaipuria',
 'insignia ventures partners',
 'ajay data & other hnis',
 'nsi infinium global pvt. ltd',
 'menterra social impact fund',
 'miten mehta',
 'small industries development bank of india (sidbi)',
 'kingsway fci fund',
 'zoya akhtar',
 'rwe',
 'nagendra prasad bhanuprakash',
 'jerry yang',
 'vishwadeep bajaj',
 'waheed alli',
 'temasek holdings',
 'line ventures corporation',
 'india quotient',
 'director at byramjee jeejeebhoy pvt. ltd were among the angels',
 'mangroves capital partners',
 "singtel's innov8",
 'sunergy investors',
 'ecl finance',
 'dheeraj jain & others',
 'aditya dev sood',
 'mariwala family',
 'ht media ltd',
 'digital garage',
 'beenext ventures',
 'krit sankalp',
 'and ramakant sharma',
 'jaarvis accelerator',
 'alibaba',
 'jupiter capital',
 'orchid india',
 'aarin capital partners',
 'deshe holdings',
 'green house ventures (ghv)',
 'srinivas tirupati',
 'vishnu bhat',
 'mercury fund',
 'likemind ventures',
 'pearl brook holdings',
 'amen dhyllon',
 'mumbai angel',
 'ankit gupta',
 'touchstone equities',
 'entrepreneurship (ciie)',
 'wipro consumer care',
 'kellygamma',
 'virendra patel',
 'harpreet singh grover',
 'yournest angel fund',
 'sanjeev mehra',
 'vikrant varshney',
 'mukul singhal',
 'ms dhoni',
 'r natarajan',
 'chetan bhagat',
 'edelweiss financial services',
 'sequoia capital india',
 'american express ventures',
 'keystone group',
 'pranav dedhia',
 'bizreach',
 'verlinvest sa',
 'medintel services pvt. ltd',
 'rajat malhotra',
 'svg media',
 'vinay bansal',
 'saurabh srivastava',
 'nitish singh',
 'rajesh magow',
 'pranay jivrajka',
 'r. satya narayanan',
 'wargburg pincus',
 'tekne capital management',
 'wellington',
 'vishwanathan',
 'sprout angels llp',
 'rugmini menon',
 '50k ventures',
 'xue manzi',
 'karsemven fund',
 'himanshu aggrawal',
 'aditya vij',
 'rairah corporation',
 'max ventures',
 'pravin khandelwal',
 'teachers insurance',
 'nazara games',
 'idg ventures india advisors',
 'kaushal agarwal',
 'bravia capital',
 'scale ventures',
 'nexus india capital advisors',
 'hr fund',
 'solidarity venture capital & others',
 'rahul kayan',
 'tania johny palathinkal',
 'ramkumar nishtal',
 'pv sahad',
 'techstars',
 'ankur warikoo',
 'rb investments',
 'mandhian family & others',
 'deepak jain',
 'axis bank',
 'oliphabs capital',
 'huang wei',
 'nb ventures',
 'hussam khoury',
 'saama capital',
 'havya sharma',
 'fidelity growth partners india',
 'exfinity',
 'one 97 communications',
 'aditya singh',
 'ankur singla',
 'chirag nikunj sheth & others',
 'rps ventures',
 'gagan goyal',
 'kddi ',
 'xchange investors nv',
 'kris gopalakrishnan',
 'scale minds',
 'bharti enterprises',
 'arun seth',
 'lip-bu tan',
 'prabhakar mr & others',
 'bill & melinda gates foundation',
 'ashish dhawan',
 'toos n daruvala',
 'villgro',
 'softbank vision fund',
 'zishaan hayath',
 'inara capital ',
 'alok divatia',
 'scale ventures funds',
 'shantanu mathur',
 'karan chellani',
 'balamurali krishna',
 'collaborative licensing ventures llp',
 'sohail hashemi',
 "the uk's development finance institution",
 'behram vakil',
 'sunjay kapoor',
 'montane ventures',
 'qprize from qualcomm ventures',
 'girish matrubootham',
 'undisclosed investor',
 'arvind uppal',
 'aseem sood',
 'shiva gunapu & others',
 'nexus venture partners',
 'mayfield india ii management ltd',
 'saket dhankar',
 'harsh vardhan hada',
 'aakrit vaish',
 'zodius technology fund',
 'kinzon capital',
 'deshpande foundation',
 'swan angel network',
 'equanimity ventures',
 'alibaba pictures',
 'vikas saxena',
 'angie mahtaney',
 'emergent ventures',
 'seek ltd & affiliates',
 'satish khanna',
 'empire angels',
 'ghv',
 'anand ladsariya',
 'itw digital',
 'falcon edge',
 'm&s partners pte. ltd',
 'gaurav luniya',
 'narayan ramachandran',
 'existing & new investors',
 'umang kumar',
 'devendra rane',
 'rohit bansal',
 'senovo',
 'udayan goyal',
 'ankit maheshwari',
 'alok bajpai',
 'pi ventures',
 'prof. ram kumar kakani & others',
 '  sandeep aggarwal',
 'pradeep k jaisingh',
 'anand chandrasekaran',
 'metaform ventures',
 'vijay kedia',
 'kashyap deorah',
 'weh ventures',
 'chiratae ventures',
 'atul goel',
 'pranay chulet',
 'venk krishna',
 'kae capital management',
 'nick haulkoury',
 'wipro ventures',
 'thinkuvate',
 'doreswamy nandkishore',
 'chandigarh angels funding',
 'ngp',
 'emery capital',
 'capital advisers',
 'koen bouwers',
 'askme',
 'rahul dev kumar',
 'sharad sharma & 14 others',
 'franklin templeton international services pvt. ltd',
 'axan partners',
 'kanchan ghoshal',
 'helion venture partner',
 "tata group's watch",
 'nimmagadda prasad',
 'traxcn labs & others',
 'mumbai angels network',
 'sandeep dama & others',
 'infoedge',
 'wrv capital',
 'social alpha',
 'foundation capital',
 'samridhi fund',
 'anand mahindra',
 'sanjay mehta',
 'puneet dalmia',
 'powerhouse ventures',
 'knoll ventures',
 'apoorva patni',
 'youwecan ventures',
 'procam international pvt. ltd',
 'praveer kumar',
 'astarc ventures',
 'alok sharma',
 'telephone corporation',
 'orios venture partner',
 'littlerock',
 'manpreet singh',
 'ritesh dwivedy',
 'axilor',
 'rohit chokhani',
 'times group brand capital',
 'goldman sachs investment partners',
 'play tech center',
 'chryscapital',
 'and jamshed jeejeebhoy',
 'bac acquisitions',
 'eduardo saverin & velos capital',
 'ramesh kavediya',
 'm & s partners',
 'sharad hegde',
 'rohit narang',
 'ola',
 'cocapital',
 'rajul garg & other undisclosed investors',
 'exfinity venture',
 'rajasthan angel innovators network',
 'suresh senapaty',
 'cyber carrier cl',
 'ishan manaktala',
 'goldman sachs group',
 'sanjay verma',
 'anil jaggia',
 'chandigarh angels network',
 'india internet fund',
 'ajay bhatia',
 'k ganesh',
 'ravi saxena',
 'rohan desai',
 "adam d'angelo",
 'innovations east',
 'international financial corporation',
 'gsf',
 'gokul rajaram',
 'sanjay mehta & others ( the ten minute million)',
 'vikram limaye',
 'unitus impact livelihoods fund',
 'qualgro',
 'citi ventures',
 'eight roads ventures india',
 'endeavor catalyst fund',
 'mohit joshi & others',
 'sands capital',
 'sc gg india mobility holdings llc',
 'global institutional investors',
 'vertex ventures',
 'matrix partner',
 'satoshi studios',
 '500 start-ups',
 'mike galgon',
 'fullerton financial holdings pte ltd & others',
 'alok mittal',
 'nyca partners',
 'nobel house',
 'mato peric & others',
 'amereus group',
 'qasar younis',
 'amit rambhia & others',
 'ram shriram',
 'adveq management',
 'oman india joint investment fund (oijif)',
 'brick eagle',
 'gree ventures',
 'vinod martin',
 'co. ltd (bccl)',
 '122 west ventures',
 'piyush shah',
 'caspian',
 'das capital',
 'sunil nikhar',
 'amit patni',
 'makemytrip innovation fund',
 'stanford angels & entrepreneurs',
 'r. natarajan',
 ' tiger global',
 'sunil kalra',
 'f-prime capital partners',
 'suvo sarkar',
 'bodhtree consulting limited',
 'shrishti sahu',
 'jamil khatri',
 'rockstart accelerator',
 'kumar shwetabh',
 'subramani somasundaram',
 'florintree',
 'kunal shah',
 'founder',
 'rainbow digital services pvt. ltd',
 'vipin arora',
 'hornbill orchid india fund',
 'vy capital',
 'bijoy george',
 '& other angel investors.',
 'vidyadhar sarfare',
 'rb international',
 'devendra reddy',
 'endiya partners',
 'fireside ventures & others',
 'saavn',
 'vikram chachra',
 'un disclosed investors',
 'kalaari capital partners',
 'rise india',
 'smile multimedia',
 'nimit panigrahi',
 'engie rde fund',
 "softbank's deepcore.",
 'swastika co ltd.',
 'asuka holdings',
 'bccl',
 'abhishekh goyal',
 'yogesh andlay',
 'shailesh mehta',
 'keith rodricks',
 'memg family office',
 'ravi adusumalli',
 'rajnish kumar',
 'palash jain',
 'hemant luthra',
 'omnivore partners',
 'subodh gupta',
 'ritesh vohra',
 'tenaya capital',
 'ward ferry management',
 'gic ventures',
 'corvus ventures',
 'swati gupta',
 'milestone',
 'ajay data',
 'naresh ravindranath',
 'vishal malik',
 'puneet dalmia & others',
 'smarak bhuyan',
 'sarthak',
 'alfa capital',
 "tv mohandas pai's family office",
 'anglian omega network',
 'lead angels',
 'venturesity',
 'rs shanbag',
 'accion venture labs',
 'rohto pharmaceutical',
 'qualgro.',
 'abhinav bindra',
 'chairman of career information portal careers360',
 'better capital angellist syndicate.',
 'intel capital',
 'verlinvest',
 'rattan chadha',
 'greenfield advisory',
 'east ventures & others',
 'gray matters capital',
 'new atlantic ventures',
 'radhakrishnan natarajan & others',
 'shreyans shah',
 'unknown high net-worth individuals',
 'softbank group',
 'kapil dev',
 'sushil kumar',
 'zeeshan hayat',
 'triton investment advisors',
 'suncoast investments',
 'saurabh arora',
 'mumbai angels',
 'prashant malik',
 'stellaris venture partners',
 'lemelson foundation',
 'clairvest group',
 'iron pillar',
 'rajan anandan',
 'idal health',
 'ligthbox ventures ii',
 'azmul haque',
 'simile ventures',
 'mohan kumar',
 'contrarian capital',
 'times of india group & existing investors',
 'r m picture company pvt. ltd.',
 'yeahmobi',
 'vineet taneja',
 'prakhar bumb',
 'lindwall family investments llc (lfi)',
 'kunal khattar',
 'shun yoshida & others',
 'sandeep aggarwal',
 'ankit bhati',
 'dino morea',
 'amit agrawal',
 'bertelsmann india investments',
 'evan lim',
 'blinc advisors',
 'abhijit avasthi',
 'idfc spice fund',
 'venkat vallabhneni',
 'spiral ventures',
 'iifl wealth',
 'snehal mantri',
 'jim schimdktke',
 'renaud laplanche',
 'ambiga dhiraj',
 'b capital',
 'Sudheshna Vuppala',
 'scadea solutions inc',
 'green visor capital lp ii',
 'xiaomi technologies',
 'silicon valley ventures',
 'rsi fund',
 'sandeep pangal',
 'subhash goyal',
 'timbru ventures',
 'naveen tewari',
 'jay srinivasan',
 'gbim technologies pvt ltd',
 'grace capital ventures',
 'ankit aditya',
 'draper associates',
 'nspira',
 'trifecta capital advisors llp',
 'v. balakrishnan',
 'samir shah',
 'salesforce ventures',
 'paytm (one97 communications)',
 'vissal mathew',
 'krishan gupta & others',
 'sscbs innovation',
 'sandiep shrivatsava',
 'radhakrishan damani',
 'bs nagesh',
 'rajeev arora',
 'harmony partners',
 'aegon nv',
 'shardul amarchand mangaldas',
 'multiples alternate asset management',
 'gaurav marya',
 'namrata kaul',
 'space matrix',
 'unternehmertum venture capital',
 'white unicorn ventures',
 'justin kan',
 'mirah hospitality',
 ' goldman sachs',
 'indian angel network',
 'raay global investments',
 'you & mr jones',
 'development finance institution belgian investment company',
 'p surendra pai',
 'li tao',
 'singularity ventures',
 'sujal shah',
 'id enablers pvt ltd',
 'amod malviya',
 'amit khanna (letsventure)',
 'clp holdings group',
 'gems advisory',
 'chandralekha construction pvt. ltd.',
 'inventus capital',
 'abhinav mathur',
 'payu & others',
 'whiteboard capital',
 'abcom investments',
 'michael & susan dell foundation',
 'singtel',
 'keyur joshi',
 'european investment fund',
 'qatar investment authority',
 'silicon valley-based accel',
 'aditya malik & others',
 'private equity firm multiples alternate asset management',
 'softbank group corp',
 'ashish lakhanpal',
 'goa',
 'mohan alexander',
 'capricorn investment',
 'rohan ajila',
 'michael patrick hickey',
 'paras arora',
 'jitendra gupta & others',
 'v balakrishnan',
 'unifi aif',
 'viraj tyagi & others',
 'flipkart logistics pvt. ltd',
 'hbm healthcare investments',
 'ashish agrawal',
 'cio angel network',
 'rajit nanda',
 'kiran mazumdar-shaw',
 'gems group',
 'edbi',
 'eagle10 ventures',
 'aspire systems',
 'bobby reddy',
 'kck global & others',
 'northern r capital',
 'devesh rai g',
 'zodius technology opportunities fund',
 'badal malick',
 'kris gopalakrishnan & others',
 'sutter hill ventures',
 'rn agarwal',
 'unicorn venture',
 'pratik seal',
 'augment ventures',
 "sean o'sullivan & others",
 'battery road digital holdings llc',
 'pradeep dhobale',
 'interglobe technology quotient',
 'undisclosed dubai based hnis',
 'accel partners & existing investors',
 'i2india pvt ltd',
 'arkas industries',
 'lothal angel ventures',
 'j.p. bhatt',
 'vishwadeep bajaj & others',
 'nishit sharma',
 'lionrock capital',
 'nikhil bagri',
 'pravin agarwala & others',
 'logtally',
 'vijay anand',
 'creation investments capital management',

In [89]:
fund['investor_clean'] = fund['investor_clean'].str.split(r',\s*|\s+\band\b\s+')

In [90]:
fund_test = fund.explode('investor_clean')

In [91]:
fund_test = fund_test.reset_index()

In [92]:
fund.info()

<class 'pandas.DataFrame'>
RangeIndex: 3044 entries, 1 to 3044
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date            3044 non-null   datetime64[us]
 1   startup         3044 non-null   str
 2   vertical        2873 non-null   str
 3   subvertical     2108 non-null   str
 4   city            2864 non-null   str
 5   investors       3044 non-null   str
 6   round           3040 non-null   str
 7   amount          3044 non-null   float64
 8   startup_clean   3044 non-null   str
 9   investor_clean  3044 non-null   object
dtypes: datetime64[us](1), float64(1), object(1), str(7)
memory usage: 565.6+ KB

In [93]:
# analyse the round column
temp_df = fund[fund['round'].isnull()]
temp_df.shape

(4, 10)

In [94]:
fund.loc[temp_df.index,'round'] = ['Funding Round / Venture Round','Private Equity','Series A','Private Equity / Series A Extension']

In [95]:
fund.info()

<class 'pandas.DataFrame'>
RangeIndex: 3044 entries, 1 to 3044
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date            3044 non-null   datetime64[us]
 1   startup         3044 non-null   str
 2   vertical        2873 non-null   str
 3   subvertical     2108 non-null   str
 4   city            2864 non-null   str
 5   investors       3044 non-null   str
 6   round           3044 non-null   str
 7   amount          3044 non-null   float64
 8   startup_clean   3044 non-null   str
 9   investor_clean  3044 non-null   object
dtypes: datetime64[us](1), float64(1), object(1), str(7)
memory usage: 565.3+ KB

In [96]:
fund = fund.assign(round_clean = fund['round'].str.lower().str.strip())

In [97]:
fund.head()

,date,startup,vertical,subvertical,city,investors,round,amount,startup_clean,investor_clean,round_clean
Sr No,,,,,,,,,,,
1,2020-01-09,byjus,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,1913.40,byjus,[tiger global management],private equity round
2,2020-01-13,shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,77.00,shuttl,[susquehanna growth equity],series c
3,2020-01-09,mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,175.64,mamaearth,[sequoia capital india],series b
4,2020-01-02,wealthbucket,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,28.70,wealthbucket,[vinod khatumal],pre-series a
5,2020-01-02,fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,17.22,fashor,[sprout venture partners],seed round

In [98]:
unwanted_char = r'[^a-z0-9\s-]'
fund[fund['round_clean'].str.contains(unwanted_char,regex=True)]

,date,startup,vertical,subvertical,city,investors,round,amount,startup_clean,investor_clean,round_clean
Sr No,,,,,,,,,,,
31,2019-11-19,furtados school of music,Education,Music Education,Tulangan,IAN Fund and DSG Consumer Partners,Funding Round / Venture Round,1913.40,furtados school of music,"[ian fund, dsg consumer partners]",funding round / venture round
107,2019-04-10,unacademy,Edtech,E-learning,Bengaluru,Kalyan Krishnamurthy,Seed/ Angel Funding,2.94,unacademy,[kalyan krishnamurthy],seed/ angel funding
127,2018-11-01,godesi,Food and Beverage,Regional Flavours,Bengaluru,Lead Angels Network,Seed/ Angel Funding,1.33,godesi,[lead angels network],seed/ angel funding
135,2018-11-14,cleansecar,Services,Car Wash,Bengaluru,Venture Catalysts,Seed/ Angel Funding,4.78,cleansecar,[venture catalysts],seed/ angel funding
137,2018-11-20,healthifyme,Health and Wellness,Wellness Coach,Bengaluru,"Sistema Asia Fund, VC Samsung NEXT, Chiratae V...",Series B (Extension),57.40,healthifyme,"[sistema asia fund, vc samsung next, chiratae ...",series b (extension)
...,...,...,...,...,...,...,...,...,...,...,...
2986,2015-02-26,freshworld,NaN,NaN,NaN,"Kris Gopalakrishnan, Nagaraja Prakasam",Seed\\nFunding,0.00,freshworld,"[kris gopalakrishnan, nagaraja prakasam]",seed\\nfunding
2988,2015-02-27,momoe,NaN,NaN,NaN,"IDG Ventures India, Jungle Ventures, India Quo...",Seed\\nFunding,11.48,momoe,"[idg ventures india, jungle ventures, india qu...",seed\\nfunding
2991,2015-01-02,violetstreet,NaN,NaN,NaN,"Venkat Vallabhneni, Sudhakar Reddy, Srinivasa ...",Seed\\nFunding,3.01,violetstreet,"[venkat vallabhneni, sudhakar reddy, srinivasa...",seed\\nfunding
2992,2015-01-05,lookup,NaN,NaN,NaN,"DeNA Co., Japan & Teruhide Sato (in Addition t...",Seed\\nFunding,3.64,lookup,"[dena co., japan & teruhide sato (in addition ...",seed\\nfunding
2998,2015-01-06,tookitaki,NaN,NaN,NaN,"Jungle Ventures, Redbright Partners, Blume Ven...",Private\\nEquity,9.57,tookitaki,"[jungle ventures, redbright partners, blume ve...",private\\nequity

In [99]:
# unit test
fund.loc[2991,'round_clean']

'seed\\\\nfunding'

In [100]:
fund['round_clean'] = fund['round_clean'].str.replace(r'\\\\+n',' ',regex=True)

In [101]:
unwanted_char = r'[^a-z0-9\s-/]'
fund[fund['round_clean'].str.contains(unwanted_char,regex=True)]

,date,startup,vertical,subvertical,city,investors,round,amount,startup_clean,investor_clean,round_clean
Sr No,,,,,,,,,,,
137,2018-11-20,healthifyme,Health and Wellness,Wellness Coach,Bengaluru,"Sistema Asia Fund, VC Samsung NEXT, Chiratae V...",Series B (Extension),57.4,healthifyme,"[sistema asia fund, vc samsung next, chiratae ...",series b (extension)

In [102]:
fund.info()

<class 'pandas.DataFrame'>
RangeIndex: 3044 entries, 1 to 3044
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date            3044 non-null   datetime64[us]
 1   startup         3044 non-null   str
 2   vertical        2873 non-null   str
 3   subvertical     2108 non-null   str
 4   city            2864 non-null   str
 5   investors       3044 non-null   str
 6   round           3044 non-null   str
 7   amount          3044 non-null   float64
 8   startup_clean   3044 non-null   str
 9   investor_clean  3044 non-null   object
 10  round_clean     3044 non-null   str
dtypes: datetime64[us](1), float64(1), object(1), str(8)
memory usage: 628.5+ KB

In [103]:
fund[fund['vertical'].isnull()]

,date,startup,vertical,subvertical,city,investors,round,amount,startup_clean,investor_clean,round_clean
Sr No,,,,,,,,,,,
2874,2015-03-02,trulymadly,NaN,NaN,NaN,"Helion Venture Partners, Kae Capital",Private Equity,52.62,trulymadly,"[helion venture partners, kae capital]",private equity
2875,2015-03-02,instalively,NaN,NaN,NaN,Group of Angel Investors,Seed Funding,1.15,instalively,[group of angel investors],seed funding
2876,2015-03-03,vserv,NaN,NaN,NaN,"Maverick Capital, IDG Ventures India",Private Equity,143.50,vserv,"[maverick capital, idg ventures india]",private equity
2877,2015-03-03,intruo,NaN,NaN,NaN,"Ashutosh Lawania, Alok Goel & others",Seed Funding,0.00,intruo,"[ashutosh lawania, alok goel & others]",seed funding
2878,2015-03-05,niffler,NaN,NaN,NaN,SAIF Partners,Seed Funding,9.57,niffler,[saif partners],seed funding
...,...,...,...,...,...,...,...,...,...,...,...
3040,2015-01-29,printvenue,NaN,NaN,NaN,Asia Pacific Internet Group,Private Equity,43.05,printvenue,[asia pacific internet group],private equity
3041,2015-01-29,graphene,NaN,NaN,NaN,KARSEMVEN Fund,Private Equity,7.89,graphene,[karsemven fund],private equity
3042,2015-01-30,mad street den,NaN,NaN,NaN,"Exfinity Fund, GrowX Ventures.",Private Equity,14.35,mad street den,"[exfinity fund, growx ventures.]",private equity
3043,2015-01-30,simplotel,NaN,NaN,NaN,MakeMyTrip,Private Equity,0.00,simplotel,[makemytrip],private equity
3044,2015-01-31,couponmachine,NaN,NaN,NaN,UK based Group of Angel Investors,Seed Funding,1.34,couponmachine,[uk based group of angel investors],seed funding

In [104]:
fund.sort_values(by=['startup_clean','date'],ascending=True).head(50)

,date,startup,vertical,subvertical,city,investors,round,amount,startup_clean,investor_clean,round_clean
Sr No,,,,,,,,,,,
2993,2015-01-05,#fame,NaN,NaN,NaN,TO THE NEW Ventures,Private Equity,95.67,#fame,[to the new ventures],private equity
1243,2016-11-25,121policy,Consumer Internet,Online Insurance Platform,Kolkata,Xelpmoc,Seed Funding,0.00,121policy,[xelpmoc],seed funding
202,2018-07-12,19th mile,IT,Artificial intelligence-based sales accelerati...,Gurugram,"Rishi Vasudev, Excelsior Investments, Ritesh V...",Seed/ Angel Funding,1.72,19th mile,"[rishi vasudev, excelsior investments, ritesh ...",seed/ angel funding
1008,2017-02-09,1crowd,Finance,Startup Crowd-funding platform,Mumbai,Ganesh Natarajan,Seed Funding,0.00,1crowd,[ganesh natarajan],seed funding
1794,2016-04-20,1mg,eCommerce,Online Pharmacy,Gurgaon,"Maverick Capital Ventures, Sequoia Capital, Om...",Private Equity,143.50,1mg,"[maverick capital ventures, sequoia capital, o...",private equity
1738,2016-05-31,1mg,eCommerce,Online Pharmacy,Gurgaon,HBM Healthcare Investments,Private Equity,0.00,1mg,[hbm healthcare investments],private equity
717,2017-07-27,1mg,eCommerce,Online Pharmacy,Gurgaon,"HBM Healthcare Investments, Maverick Capital V...",Private Equity,143.50,1mg,"[hbm healthcare investments, maverick capital ...",private equity
312,2018-04-27,1mg,Consumer Internet,Online Pharmacy Store,Gurugram,"Sequoia Capital, Maverick Capital Ltd and HBM ...",Private Equity,95.67,1mg,"[sequoia capital, maverick capital ltd, hbm he...",private equity
2845,2015-04-20,1mg (healthkartplus),Online Pharmacy & Drug DB,NaN,Gurgaon,"Deep Kalra, Sequoia Capital, Omidyar Network, ...",Private Equity,57.40,1mg (healthkartplus),"[deep kalra, sequoia capital, omidyar network,...",private equity
2965,2015-02-13,20dresses,NaN,NaN,NaN,"Srinivas Aluri, Srinivas Modukury, BS Nagesh",Seed\\nFunding,9.57,20dresses,"[srinivas aluri, srinivas modukury, bs nagesh]",seed funding
2596,2015-07-08,33coupons,Coupon Aggregator Platform,NaN,Kanpur,Not Disclosed,Seed Funding,0.19,33coupons,[not disclosed],seed funding
2013,2016-01-05,360ride,Consumer Internet,Ride Sharing platform,Bangalore,Undisclosed,Seed Funding,1.44,360ride,[undisclosed],seed funding
1308,2016-10-18,3dexter,Technology,3D Printing Solutions for Edu space,New Delhi,Newbie Promoters,Seed Funding,1.44,3dexter,[newbie promoters],seed funding
596,2017-09-12,3hcare,Consumer Internet,Healthcare services portal,New Delhi,Undisclosed Investor,Seed Funding,0.96,3hcare,[undisclosed investor],seed funding
155,2018-09-04,3hcare,Healthcare,Healthcare Service Provider,Delhi,Undisclosed,Seed / Angel Funding,9.57,3hcare,[undisclosed],seed / angel funding
39,2019-09-04,3rdflix,SaaS,Education Technology,Hyderabad,Exfinity Venture Partners,pre-series A,47.84,3rdflix,[exfinity venture partners],pre-series a
1010,2017-02-10,48east,ECommerce,Online Food Delivery Platform,Bangalore,Al Dhaheri family,Private Equity,4.78,48east,[al dhaheri family],private equity
789,2017-05-02,4tigo,Logistics,Truck Network company,Bangalore,"Accel Partners, Nandan Nilekani,",Private Equity,95.67,4tigo,"[accel partners, nandan nilekani, ]",private equity
203,2018-07-12,5th vital,Healthcare,Home diagnostics services provider,Bengaluru,Brand Capital and Others,Seed/ Angel Funding,4.78,5th vital,"[brand capital, others]",seed/ angel funding
2230,2015-11-11,6degree,Talent platform for Fashion professionals,NaN,Goa/Hyderabad,Centre For Incubation & Business Acceleration ...,Seed Funding,0.00,6degree,[centre for incubation & business acceleration...,seed funding
1582,2016-06-08,6degree,Technology,Tech-enabled Fashion Talent platform,Mumbai,Indian Angel Network,Seed Funding,1.91,6degree,[indian angel network],seed funding
40,2019-09-04,75f,IoT,Building automation system,Burnsville,Breakthrough Energy Ventures,Series A,172.21,75f,[breakthrough energy ventures],series a
1437,2016-08-11,91springboard,Consumer Internet,Co-Working Spaces Discovery & Booking platform,Mumbai,"Khattar Holdings, ThirtyThree Investments, Sou...",Private Equity,0.00,91springboard,"[khattar holdings, thirtythree investments, so...",private equity
614,2017-09-21,91springboard,Consumer Internet,Co-working spaces,New Delhi,"Sandway Investment Ltd, Pearl Brook Holdings, ...",Private Equity,0.00,91springboard,"[sandway investment ltd, pearl brook holdings,...",private equity
1105,2017-01-02,99games,Technology,Mobile Game Developer Studio,Udupi,Dream Incubator,Seed Funding,0.00,99games,[dream incubator],seed funding
1107,2017-01-26,99perhour,Consumer Internet,Hyper-local Handyman Service provider,Chennai,V Aanand R,Seed Funding,2.87,99perhour,[v aanand r],seed funding
463,2017-12-19,9stacks,Technology,Online Poker Platform,Delhi,"Swati Gupta, Purnima Khandelwal, Maheshwar Per...",Private Equity,14.35,9stacks,"[swati gupta, purnima khandelwal, maheshwar pe...",private equity
131,2018-11-08,a&r bon vivants,Food,Meat Retail Chain,Jaipur,"RB Investments, Singapore",Equity,9.57,a&r bon vivants,"[rb investments, singapore]",equity
473,2017-11-02,aadharapi,Technology,Aadhaar-based API provider,Pune,CIO Angel Network,Seed Funding,0.00,aadharapi,[cio angel network],seed funding
632,2017-09-28,aadyah,Technology,Defense Tech & Aerospace startup,Bangalore,Keiretsu Forum,Private Equity,9.57,aadyah,[keiretsu forum],private equity
2750,2015-06-30,aagaar,Hyperlocal grocery delivery,NaN,Gurgaon,Group of Investors,Seed Funding,0.00,aagaar,[group of investors],seed funding
1831,2016-03-04,aahaa,ECommerce,Office Products Super Store,Chennai,"YourNest Angel Fund,",Private Equity,9.57,aahaa,"[yournest angel fund, ]",private equity
575,2017-09-01,aahaa stores,eCommece,Online B2B store for office supplies,Chennai,YourNest Angel Fund,Private Equity,9.57,aahaa stores,[yournest angel fund],private equity
1989,2016-02-23,aarav uav,Technology,unmanned aerial vehicles creator,Kanpur,"StartupXseed Ventures, The Phoenix Fund and ot...",Seed Funding,0.00,aarav uav,"[startupxseed ventures, the phoenix fund, others]",seed funding
3035,2015-01-24,aasaanjobs,NaN,NaN,NaN,"Inventus Capital Partners, IDG Ventures",Seed Funding,14.35,aasaanjobs,"[inventus capital partners, idg ventures]",seed funding
1950,2016-02-15,aasaanjobs,Consumer Internet,Online Recruitment Marketplace,Mumbai,"Aspada Advisors, IDG Ventures,\\xc2\\xa0 Inven...",Private Equity,47.84,aasaanjobs,"[aspada advisors, idg ventures, inventus capital]",private equity
271,2018-05-23,aashiyaan,Finance,Housing Finance For Low-Income Families,Kolkata,"Insistor, Oikocredit",Seed/ Angel Funding,19.13,aashiyaan,"[insistor, oikocredit]",seed/ angel funding
139,2018-11-22,aavishkaar-intellecap group,Investment,SME Funding,Mumbai,Teachers Insurance and Annuity Association (TIAA),Equity Based Funding,296.58,aavishkaar-intellecap group,"[teachers insurance, annuity association (tiaa)]",equity based funding
1561,2016-07-21,aberuk,eCommerce,Online Marketplace for books,Bangalore,Swastika Company Pvt Ltd,Seed Funding,0.00,aberuk,[swastika company pvt ltd],seed funding
2294,2015-10-01,abhibus,us ticketing and fleet management platform,NaN,Hyderabad,Paytm (One97 communications),Private Equity,0.00,abhibus,[paytm (one97 communications)],private equity
736,2017-06-08,abi health,Technology,Unified Digital Health Platform,Bangalore,Norwest Venture Partners,Private Equity,14.35,abi health,[norwest venture partners],private equity
2236,2015-11-16,absentia,Virtual Reality Headset creator,NaN,Bangalore,"Astarc Ventures, 50K Ventures & others",Seed Funding,1.72,absentia,"[astarc ventures, 50k ventures & others]",seed funding
901,2017-04-18,absentia vr,Technology,Virtual Reality Startup,Bangalore,Exfinity Venture Partners,Private Equity,11.96,absentia vr,[exfinity venture partners],private equity
804,2017-05-08,ace turtle,Technology,Omni-Channel Platform,Bangalore,"Vertex Ventures, C31 Ventures",Private Equity,47.84,ace turtle,"[vertex ventures, c31 ventures]",private equity
617,2017-09-22,ace turtle,Technology,Omni-channel web commerce solutions provider,Bangalore,InnoVen Capital,Private Equity,0.00,ace turtle,[innoven capital],private equity
786,2017-05-01,ace2three,Consumer Internet,Online Rummy playing Website,Hyderabad,Clairvest Group,Private Equity,705.09,ace2three,[clairvest group],private equity
274,2018-05-27,acko,Consumer Internet,Online Insurance Platform,Mumbai,"Amazon, Ashish Dhawan, Catamaran Ventures, NR ...",Seed/ Angel Funding,114.80,acko,"[amazon, ashish dhawan, catamaran ventures, nr...",seed/ angel funding
2503,2015-08-10,actionable analytics,Machine Learning Platform,NaN,New Delhi/ Houston,"B M Gupta, Vinod Singhal",Seed Funding,0.00,actionable analytics,"[b m gupta, vinod singhal]",seed funding
1678,2016-05-04,active,Technology,Intelligent Tech platform for Finance vertical,Singapore,Kalaari Capital Accelerator Program,Seed Funding,4.78,active,[kalaari capital accelerator program],seed funding
1211,2016-11-14,active,Technology,Banking & Fintech Platform,Singapore,"Kalaari Capital, IDG Ventures India",Private Equity,28.70,active,"[kalaari capital, idg ventures india]",private equity

In [105]:
fund['city_clean'] = fund['city'].str.lower().str.strip()

In [106]:
fund['city_clean'].sort_values().head(50)

Sr No
2604    \\xc2\\xa0bangalore
2605      \\xc2\\xa0gurgaon
2608      \\xc2\\xa0gurgaon
2610      \\xc2\\xa0gurgaon
2612      \\xc2\\xa0gurgaon
2609       \\xc2\\xa0mumbai
2606    \\xc2\\xa0new delhi
2607    \\xc2\\xa0new delhi
2611    \\xc2\\xa0new delhi
2603        \\xc2\\xa0noida
1292                   agra
1369                   agra
179              ahemadabad
376              ahemadabad
356               ahemdabad
369               ahmedabad
396               ahmedabad
581               ahmedabad
679               ahmedabad
741               ahmedabad
864               ahmedabad
898               ahmedabad
937               ahmedabad
1104              ahmedabad
1106              ahmedabad
1241              ahmedabad
1294              ahmedabad
1330              ahmedabad
1388              ahmedabad
1403              ahmedabad
1450              ahmedabad
1515              ahmedabad
1623              ahmedabad
1649              ahmedabad
1650              ahmedabad
1861              ahmedabad
1864              ahmedabad
1887              ahmedabad
1960              ahmedabad
1971              ahmedabad
2010              ahmedabad
2018              ahmedabad
2082              ahmedabad
2328              ahmedabad
2360              ahmedabad
2523              ahmedabad
2547              ahmedabad
2557              ahmedabad
2581              ahmedabad
2600              ahmedabad
Name: city_clean, dtype: str

In [107]:
# unit test
fund.loc[2606,'city_clean']

'\\\\xc2\\\\xa0new delhi'

In [108]:
fund['city_clean'] = fund['city_clean'].str.replace('\\\\xc2\\\\xa0','').str.strip()

In [109]:
fund[fund['city_clean'].str.contains(r'[^a-z\s]',regex=True)]

,date,startup,vertical,subvertical,city,investors,round,amount,startup_clean,investor_clean,round_clean,city_clean
Sr No,,,,,,,,,,,,
26,2019-11-20,clumio,SaaS,Recovery software,"San Jose,","Altimeter Capital, Sutter Hill Ventures",Series C,1291.54,clumio,"[altimeter capital, sutter hill ventures]",series c,"san jose,"
89,2019-06-04,leegality,Services,Digital Documentation,Mumbai/Bengaluru,Mumbai Angels,Series A,32.53,leegality,[mumbai angels],series a,mumbai/bengaluru
114,2019-02-08,zilingo,Ecommerce,Fashion & Apparel,India/Singapore,"Sequoia Capital and Temasek Holdings, EDBI, Bu...",Series D,2162.14,zilingo,"[sequoia capital, temasek holdings, edbi, burd...",series d,india/singapore
118,2019-01-04,vyome therapeutics inc.,Health and Wellness,Specialty pharmaceutical,India/US,"Iron Pillar, Perceptive Advisors, Romulus Capi...",Series D,210.47,vyome therapeutics inc.,"[iron pillar, perceptive advisors, romulus cap...",series d,india/us
132,2018-11-12,blackbuck,Food Tech,POS For Online Ordering,"New York, Bengaluru",Tiger Global,Series A,9.57,blackbuck,[tiger global],series a,"new york, bengaluru"
141,2018-11-23,signzy,Financial Tech,Digital Onboarding Solution,Mumbai/Bengaluru,Stellaris Venture Partners and Kalaari Capital...,Series A,32.53,signzy,"[stellaris venture partners, kalaari capital, ...",series a,mumbai/bengaluru
142,2018-11-24,engineer,Software,AI Platform,India/US,"Lakestar and Jungle Ventures, Softbank\\xe2\\x...",Series A,282.23,engineer,"[lakestar, jungle ventures, softbank's deepcore.]",series a,india/us
244,2018-06-18,elucidata,IT,Data Analytics (SaaS),Delhi & Cambridge,Hyperplane Venture Capital and several angel i...,Seed/ Angel Funding,16.26,elucidata,"[hyperplane venture capital, several angel inv...",seed/ angel funding,delhi & cambridge
1351,2016-09-07,zilingo,eCommerce,Online Fashion Retailer,Bangalore/ Bangkok,"Venturra Capital, Sequoia India, Susquehanna I...",Private Equity,76.54,zilingo,"[venturra capital, sequoia india, susquehanna ...",private equity,bangalore/ bangkok
1741,2016-04-01,dil mil,Consumer Internet,Matchmaking Mobile App,SFO / Bangalore,"Nelstone Ventures, Transmedia Capital, Maiden ...",Private Equity,25.83,dil mil,"[nelstone ventures, transmedia capital, maiden...",private equity,sfo / bangalore
1825,2016-03-02,skedool,Consumer Internet,AI based Office Assistant Mobile App,Seattle / Bangalore,"Kludein LLC\\nPhanindra Sama, Narayan Ramachan...",Seed Funding,0.00,skedool,"[kludein llc, phanindra sama, narayan ramachan...",seed funding,seattle / bangalore
1859,2016-03-10,icertis,Technology,Contract Management Software Solutions platform,Pune/Seattle,"Ignition Partners, Greycroft Partners, Fidelit...",Private Equity,143.50,icertis,"[ignition partners, greycroft partners, fideli...",private equity,pune/seattle
1912,2016-02-03,mazkara,Consumer Internet,Beauty & Wellness Platform,Pune / Dubai,Dunamis Ventures Pte Ltd.,Seed Funding,9.57,mazkara,[dunamis ventures pte ltd.],seed funding,pune / dubai
1918,2016-02-05,zendrive,Technology,Safe Driving Data & Analytics platform,Bangalore / SFO,"Sherpa Capital, Nyca Partners and Thomvest Ven...",Private Equity,129.15,zendrive,"[sherpa capital, nyca partners, thomvest ventu...",private equity,bangalore / sfo
2070,2016-01-20,imbesharam,ECommerce,Adult Products Etailers,New Delhi / US,Undisclosed US Based Investors,Private Equity,38.27,imbesharam,[undisclosed us based investors],private equity,new delhi / us
2071,2016-01-20,moodoo,Consumer Internet,Social Meeting organizer App,Mumbai / UK,Sa\\xc3\\xafd Business School Seed Fund.,Seed Funding,0.38,moodoo,[saïd business school seed fund],seed funding,mumbai / uk
2149,2015-12-11,eureqa,Test Automation SAAS platform,NaN,Hyderabad/USA,"Sashi Reddi, Gabriel Investments",Seed Funding,5.74,eureqa,"[sashi reddi, gabriel investments]",seed funding,hyderabad/usa
2163,2015-12-15,streamoid,visual search and discovery platform,NaN,Bangalore / Palo Alto,Undisclosed,Seed Funding,9.57,streamoid,[undisclosed],seed funding,bangalore / palo alto
2174,2015-12-18,cbrex,International Hiring Platform,NaN,Mumbai / NY,"Prahlad Rao, Sundara Rajan, Vikram Chachra",Seed Funding,1.91,cbrex,"[prahlad rao, sundara rajan, vikram chachra]",seed funding,mumbai / ny
2207,2015-11-03,bidgely,Efficient Energy Management platform,NaN,USA/India,Constellation Technology Ventures (Exelon Corp...,Private Equity,158.81,bidgely,[constellation technology ventures (exelon cor...,private equity,usa/india
2224,2015-11-09,zilingo,Marketplace App for Bangkok,NaN,Bangalore/ Bangkok,"Sequoia India, BEENEXT Ventures, Kunal Shah & ...",Private Equity,18.18,zilingo,"[sequoia india, beenext ventures, kunal shah &...",private equity,bangalore/ bangkok
2230,2015-11-11,6degree,Talent platform for Fashion professionals,NaN,Goa/Hyderabad,Centre For Incubation & Business Acceleration ...,Seed Funding,0.00,6degree,[centre for incubation & business acceleration...,seed funding,goa/hyderabad
2244,2015-11-17,convegenius,Mobile Learning Solutions,NaN,Noida / Singapore,Enablers platform,Seed Funding,2.87,convegenius,[enablers platform],seed funding,noida / singapore
2256,2015-11-20,mindtickle,Sales & Productivity Software,NaN,Pune / US,New Enterprise Associates,Private Equity,119.59,mindtickle,[new enterprise associates],private equity,pune / us
2269,2015-11-24,crayon data,Big Data Analytics Platform,NaN,Chennai/ Singapore,Ratan Tata,Private Equity,0.00,crayon data,[ratan tata],private equity,chennai/ singapore
2315,2015-10-08,mobikon,Hotel Mobile CRM Software platform,NaN,Pune / Singapore,"Life.SREDA, Qualgro",Private Equity,0.00,mobikon,"[life.sreda, qualgro]",private equity,pune / singapore
2320,2015-10-09,cloud lending,End-to-End Lending platform,NaN,Bangalore / San Mateo,SF Capital Group,Private Equity,76.54,cloud lending,[sf capital group],private equity,bangalore / san mateo
2350,2015-10-21,agentdesks,Real Estate Mobile CRM,NaN,New York/ India,"Sierra Ventures, Cota Capital, Vegas Tech Fund",Seed Funding,28.22,agentdesks,"[sierra ventures, cota capital, vegas tech fund]",seed funding,new york/ india
2415,2015-09-14,ue life sciences,Early Cancer Detection Solutions,NaN,US/India,"Aarin Capital, Unitus Seed Fund",Private Equity,28.70,ue lifesciences,"[aarin capital, unitus seed fund]",private equity,us/india
2450,2015-09-23,silverpush,Cross-device retargeting platform,NaN,Gurgaon / SFO,M&S Partners,Private Equity,11.48,silverpush,[m&s partners],private equity,gurgaon / sfo
2467,2015-09-30,infoworks,Big Data Management Platform,NaN,Bangalore / USA,"Nexus Venture Partners, Knoll Ventures and others",Private Equity,47.84,infoworks,"[nexus venture partners, knoll ventures, others]",private equity,bangalore / usa
2503,2015-08-10,actionable analytics,Machine Learning Platform,NaN,New Delhi/ Houston,"B M Gupta, Vinod Singhal",Seed Funding,0.00,actionable analytics,"[b m gupta, vinod singhal]",seed funding,new delhi/ houston
2513,2015-08-11,infogain,Business and IT consulting,NaN,New Delhi / US,ChrysCapital,Private Equity,602.72,infogain,[chryscapital],private equity,new delhi / us
2594,2015-07-08,flytxt,Big Data & Analytics platform,NaN,Mumbai / Global,"Sunrise Capital GmBH, Big Data Investments B.V",Private Equity,105.24,flytxt,"[sunrise capital gmbh, big data investments b.v]",private equity,mumbai / global
2595,2015-07-08,axtria,Big Data & Analytics platform,NaN,India / US,"Helion Venture Partners,Amarpreet Sawhney, Des...",Private Equity,287.01,axtria,"[helion venture partners, amarpreet sawhney, d...",private equity,india / us
2676,2015-06-02,saama,Big Data & Analytics Services,NaN,Pune / US,Carrick Capital Partners,Private Equity,334.84,saama,[carrick capital partners],private equity,pune / us
2682,2015-06-03,arkin net,Data Center Software platform,NaN,Pune / US,Nexus Venture Partners,Private Equity,143.50,arkin net,[nexus venture partners],private equity,pune / us
2729,2015-06-22,banihal,Algorithmic Match Making Platform,NaN,New Delhi / California,Dr David Cheriton,Seed Funding,0.00,banihal,[dr david cheriton],seed funding,new delhi / california
2813,2015-04-04,keeptrax,Location Based App,NaN,Dallas / Hyderabad,Undisclosed,Seed Funding,9.57,keeptrax,[undisclosed],seed funding,dallas / hyderabad
2853,2015-04-23,headout,Last Minute Travel Deals mobile marketplace,NaN,Bangalore / SFO,"Version One Ventures, 500 Startups, Nexus Vent...",Seed Funding,17.22,headout,"[version one ventures, 500 startups, nexus ven...",seed funding,bangalore / sfo
2868,2015-04-29,icertis,Cloud Enterprise Software,NaN,Pune / US,"Greycroft Partners, Fidelity Growth Partners",Private Equity,57.40,icertis,"[greycroft partners, fidelity growth partners]",private equity,pune / us

In [110]:
fund.loc[26,'city_clean'] = 'san jose'

In [111]:
fund.loc[[89,141],'city_clean'] = 'mumbai'

In [112]:
fund['is_cross_border'] = fund['city_clean'].str.contains(r'[/,&]',regex=True,na=False)

In [113]:
fund.head()

,date,startup,vertical,subvertical,city,investors,round,amount,startup_clean,investor_clean,round_clean,city_clean,is_cross_border
Sr No,,,,,,,,,,,,,
1,2020-01-09,byjus,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,1913.40,byjus,[tiger global management],private equity round,bengaluru,False
2,2020-01-13,shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,77.00,shuttl,[susquehanna growth equity],series c,gurgaon,False
3,2020-01-09,mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,175.64,mamaearth,[sequoia capital india],series b,bengaluru,False
4,2020-01-02,wealthbucket,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,28.70,wealthbucket,[vinod khatumal],pre-series a,new delhi,False
5,2020-01-02,fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,17.22,fashor,[sprout venture partners],seed round,mumbai,False

In [114]:
unique_city = fund['city_clean'].dropna().unique().tolist()
auto_correct={}
for name in unique_city:
    matches = difflib.get_close_matches(name,unique_city,n=5,cutoff=0.85)
    
    if len(matches)>1:
        print(matches)

['new delhi', 'nw delhi']
['india/us', 'india / us']
['ahemadabad', 'ahemdabad']
['bhubneswar', 'bhubaneswar']
['kolkatta', 'kolkata']
['kolkata', 'kolkatta']
['ahemdabad', 'ahemadabad', 'ahmedabad']
['bhubaneswar', 'bhubneswar']
['ahmedabad', 'ahemdabad']
['nw delhi', 'new delhi']
['bangalore / sfo', 'bangalore / usa']
['usa/india', 'us/india']
['us/india', 'usa/india']
['bangalore / usa', 'bangalore / sfo']
['india / us', 'india/us']

In [115]:
# discrepencies ahemadabad ,ahemdabad,ahmedabad, bangalore,bengaluru
correction_city = {'nw delhi':'new delhi',
                   'ahemadabad':'ahmedabad',
                   'ahemdabad':'ahmedabad',
                   'bhubneswar': 'bhubaneswar',
                    'kolkatta': 'kolkata',
                    'bangalore': 'bengaluru',
                    'Bengaluru': 'bengaluru'}

In [116]:
fund['city_clean'] = fund['city_clean'].replace(correction_city)

In [117]:
fund.info()

<class 'pandas.DataFrame'>
RangeIndex: 3044 entries, 1 to 3044
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date             3044 non-null   datetime64[us]
 1   startup          3044 non-null   str
 2   vertical         2873 non-null   str
 3   subvertical      2108 non-null   str
 4   city             2864 non-null   str
 5   investors        3044 non-null   str
 6   round            3044 non-null   str
 7   amount           3044 non-null   float64
 8   startup_clean    3044 non-null   str
 9   investor_clean   3044 non-null   object
 10  round_clean      3044 non-null   str
 11  city_clean       2864 non-null   str
 12  is_cross_border  3044 non-null   bool
dtypes: bool(1), datetime64[us](1), float64(1), object(1), str(9)
memory usage: 677.2+ KB

In [118]:
fund['city_clean'] = fund['city_clean'].fillna('Unknown')
fund['vertical'] = fund['vertical'].fillna('Unknown')

In [119]:
fund.drop(columns=['city'],inplace=True)

In [120]:
fund.info()

<class 'pandas.DataFrame'>
RangeIndex: 3044 entries, 1 to 3044
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date             3044 non-null   datetime64[us]
 1   startup          3044 non-null   str
 2   vertical         3044 non-null   str
 3   subvertical      2108 non-null   str
 4   investors        3044 non-null   str
 5   round            3044 non-null   str
 6   amount           3044 non-null   float64
 7   startup_clean    3044 non-null   str
 8   investor_clean   3044 non-null   object
 9   round_clean      3044 non-null   str
 10  city_clean       3044 non-null   str
 11  is_cross_border  3044 non-null   bool
dtypes: bool(1), datetime64[us](1), float64(1), object(1), str(8)
memory usage: 633.0+ KB

In [121]:
fund['subvertical'] = fund['subvertical'].fillna('Unknown')

In [122]:
fund_investor = fund.explode('investor_clean').reset_index(drop=False)

In [123]:
fund_investor.head(15)

,Sr No,date,startup,vertical,subvertical,investors,round,amount,startup_clean,investor_clean,round_clean,city_clean,is_cross_border
0,1,2020-01-09,byjus,E-Tech,E-learning,Tiger Global Management,Private Equity Round,1913.40,byjus,tiger global management,private equity round,bengaluru,False
1,2,2020-01-13,shuttl,Transportation,App based shuttle service,Susquehanna Growth Equity,Series C,77.00,shuttl,susquehanna growth equity,series c,gurgaon,False
2,3,2020-01-09,mamaearth,E-commerce,Retailer of baby and toddler products,Sequoia Capital India,Series B,175.64,mamaearth,sequoia capital india,series b,bengaluru,False
3,4,2020-01-02,wealthbucket,FinTech,Online Investment,Vinod Khatumal,Pre-series A,28.70,wealthbucket,vinod khatumal,pre-series a,new delhi,False
4,5,2020-01-02,fashor,Fashion and Apparel,Embroiled Clothes For Women,Sprout Venture Partners,Seed Round,17.22,fashor,sprout venture partners,seed round,mumbai,False
5,6,2020-01-13,pando,Logistics,"Open-market, freight management platform",Chiratae Ventures,Series A,86.10,pando,chiratae ventures,series a,chennai,False
6,7,2020-01-10,zomato,Hospitality,Online Food Delivery Platform,Ant Financial,Private Equity Round,1435.05,zomato,ant financial,private equity round,gurgaon,False
7,8,2019-12-12,ecozen,Technology,Agritech,Sathguru Catalyzer Advisors,Series A,57.40,ecozen,sathguru catalyzer advisors,series a,pune,False
8,9,2019-12-06,cardekho,E-Commerce,Automobile,Ping An Global Voyager Fund,Series D,669.69,cardekho,ping an global voyager fund,series d,gurgaon,False
9,10,2019-12-03,dhruva space,Aerospace,Satellite Communication,"Mumbai Angels, Ravikanth Reddy",Seed,478.35,dhruva space,mumbai angels,seed,bengaluru,False
10,10,2019-12-03,dhruva space,Aerospace,Satellite Communication,"Mumbai Angels, Ravikanth Reddy",Seed,478.35,dhruva space,ravikanth reddy,seed,bengaluru,False
11,11,2019-12-13,rivigo,Technology,Logistics Services and Solutions,"SAIF Partners, Spring Canter Investment Ltd.",Series F,191.34,rivigo,saif partners,series f,gurgaon,False
12,11,2019-12-13,rivigo,Technology,Logistics Services and Solutions,"SAIF Partners, Spring Canter Investment Ltd.",Series F,191.34,rivigo,spring canter investment ltd.,series f,gurgaon,False
13,12,2019-12-17,healthians,B2B-focused foodtech startup,Food Solutions For Corporate,"Paytm, NPTK, Sabre Partners and Neoplux",Series C,114.80,healthians,paytm,series c,bengaluru,False
14,12,2019-12-17,healthians,B2B-focused foodtech startup,Food Solutions For Corporate,"Paytm, NPTK, Sabre Partners and Neoplux",Series C,114.80,healthians,nptk,series c,bengaluru,False

In [124]:
fund.to_csv('fund_cleaned.csv',index=False)
fund_investor.to_csv('fund_investor.csv',index=False)

In [125]:
fund['investor_clean'] = fund['investor_clean'].apply(lambda x: [item.strip() for item in x] if isinstance(x,list) else x)

In [126]:
temp_df = fund[fund['investor_clean'].apply(lambda x: '' in x if isinstance(x,list) else False)]

In [127]:
x = temp_df['investor_clean'].apply(lambda x:[item for item in x if item != ''] if isinstance(x,list) else x).values

In [128]:
fund.loc[temp_df.index,'investor_clean'] = x

In [129]:
temp_df = fund[fund['investor_clean'].apply(lambda x:any('&' in item for item in x) if isinstance(x,list) else False)]

In [130]:
temp_df.loc[29,'investor_clean']

['ackermans & van haaren',
 'healthquad',
 'rebright partners',
 'toppan printing']

In [131]:
x = temp_df['investor_clean'].apply(lambda x: [item.replace(" & ",', ') if '&' in item else item for item in x] if isinstance(x,list) else x).values

In [132]:
fund.loc[temp_df.index,'investor_clean'] = x

In [133]:
sorted(set(fund['investor_clean'].sum()))

['& other angel investors.',
 '021 capita',
 '100 co-founders lab',
 '122 west ventures',
 '1crowd',
 '1crowd (through crowd funding)',
 '1crowd (through crowdfunding)',
 '3 undisclosed hnis',
 '3 undisclosed investors',
 '3one4 capital',
 '3one4 capital advisors',
 '3one4 capital advisors llp',
 '500 start-ups',
 '500 startups',
 '500 startups, other hnis',
 '50k ventures',
 '50k ventures, others',
 '91maker.com',
 '91springboard',
 'Anuj Srivastava',
 'Dinesh Tadepalli',
 'JK Patel',
 'JKN Partners',
 'Kalpesh Shethia',
 'Mukesh Bansal',
 'Rajeev Mudumba',
 'Ramakant Sharma',
 'Sudheshna Vuppala',
 'Sushil Agarwal',
 'a dutch government fund',
 'a m sikander',
 'a91 partners',
 'aakrit vaish',
 'aamir khan',
 'aarin capital',
 'aarin capital partners',
 'aarin capital, others',
 'aarti group',
 'aaruha technology fund',
 'aavishkaar',
 'aavishkaar venture management',
 'aavya ventures',
 'ab kinnevik',
 'abaran deep',
 'abb technology ventures',
 'abcom investments',
 'abhai s. rao',
 'abhay singhal',
 'abhijit avasthi',
 'abhijit bhandari',
 'abhinav bindra',
 'abhinav gupta',
 'abhinav mathur',
 'abhinav patodia',
 'abhinav sinha',
 'abhishek acharya',
 'abhishek agarwal',
 'abhishek bhatewara',
 'abhishek goyal',
 'abhishek gupta',
 'abhishek jain',
 'abhishekh goyal',
 'abi-showatech (india) ltd',
 'abm knowledgeware',
 'abraaj group',
 'abstract ventures',
 'abu farhan azmi',
 'accel',
 'accel (formerly known as accel partners)',
 'accel india',
 'accel partner',
 'accel partners',
 'accel partners india',
 'accel partners rnt associates',
 'accel partners, existing investors',
 'accel partners, others',
 'accel partners, raghunandan gangappa',
 'accel us',
 'accion',
 'accion venture lab',
 'accion venture labs',
 'ackermans, van haaren',
 'actis',
 'acumen fund',
 'adag reliance private equity',
 "adam d'angelo",
 'adi saravanan',
 'adil allana',
 'aditya agarwal',
 'aditya aggarwal',
 'aditya dev sood',
 'aditya malik, others',
 'aditya singh',
 'aditya vazirani',
 'aditya verma',
 'aditya vij',
 'adroitent pvt. ltd.',
 'advantedge',
 'advantedge partners',
 'adveq management',
 'aecal',
 'aegon nv',
 'aequs group',
 'aet fund',
 'afsal salu',
 'agarwal movers group',
 'agnus capital',
 'ah! ventures',
 'aijaz saleem',
 'ain capital ventures',
 'aj ventures',
 'ajai chowdhary',
 'ajai chowdhry',
 'ajay bhatia',
 'ajay data',
 'ajay data, other hnis',
 'ajay data, undisclosed hnis',
 'ajay lakhotia',
 'ajay modani',
 'ajay nanavati',
 'ajay piramal',
 'ajay relan',
 'ajay sarupria',
 'ajeet khurana',
 'ajeet khurana jinesh shah',
 'ajeet khurana, others',
 'ajesh k murthy',
 'ajit surana',
 'ajith nair',
 'ajith sukumaran',
 'ajmera group of companies',
 'akash agarwal',
 'akash bhavsar',
 'akash garg',
 'akatsuki',
 'akusa holdings',
 'al dhaheri family',
 'al nour',
 'al nour international holdings',
 'alagu periyannan',
 'alcon edge capital',
 'alex chua',
 'alex kuruvilla',
 'alexander bruehl',
 'alfa capital',
 'alibaba',
 'alibaba group',
 'alibaba pictures',
 'allcargo logistics',
 'allen blue',
 'alok bajpai',
 'alok divatia',
 'alok goel',
 'alok goel, others',
 'alok mittal',
 'alok mittal, others',
 'alok rawat',
 'alok sharma',
 'alok srivastava',
 'aloke bajpai',
 'alpha capital',
 'alpha mundi',
 "alphabet's growth investment arm capital g",
 'alphard maritime group',
 'alteria capital',
 'altimeter capital',
 'alto partners',
 'amadeus capital',
 'amajit gupta',
 'amanpreet bajaj',
 'amar arsikere',
 'amarpreet sawhney',
 'amaya capital llp',
 'amazon',
 'amazon alexa fund, dentsu ventures',
 'amazon inc.',
 'amazon-patni jv',
 'ambarish gupta',
 'ambarish ray',
 'ambi parameswaran',
 'ambiga dhiraj',
 'ambit pragma',
 'ameera shah',
 'amen dhyllon',
 'amereus group',
 'american express',
 'american express ventures',
 'amicus capital',
 'amit agrawal',
 'amit banati',
 'amit banka',
 'amit burman',
 'amit choudhary',
 'amit dey',
 'amit gupta',
 'amit jindal',
 'amit khanna',
 'amit khanna (letsventure)',
 'amit kharbanda',
 'amit manocha',
 'amit nagar',
 'amit nanavati',
 'amit patni',
 'amit rambhia, others',
 'amit ranjan',
 'amit ranjan, others',
 'amit rathore',
 'amit sandill',
 'amit singal',
 'amit singhal',
 'amit sinha',
 'amit tyagi',
 'amitpal bhutani',
 'amiya pathak',
 'amod malviya',
 'amour infrastructure',
 'amrendra reddy',
 'amrish kumar',
 'amrish rau',
 'analec',
 'anand chandrasekaran',
 'anand chandrasekaran, others',
 'anand kumar',
 'anand ladsariya',
 'anand mahindra',
 'anand mittal',
 'anand rajaraman',
 'anand sankeshwar',
 'anand singh',
 'anand vijay',
 'ananda kallugadde',
 'anandbir singh',
 'ananth narayanan',
 'anbu pandian',
 'and ajai chowdhry',
 'and amit bhatiani',
 'and amrish rau from payu india',
 'and endiya partners.',
 'and former hero corporate president rohit chanana',
 'and gurpreet singh',
 'and jamshed jeejeebhoy',
 'and lendahand',
 'and mas financial services ltd',
 'and nandan nilekani',
 'and other tech investors from silicon valley',
 'and pravega ventures',
 'and ramakant sharma',
 'and sahil barua',
 'and sanjeev agrawal',
 'and sofina',
 'and tenaska',
 'andre hoffman',
 'aneesh reddy',
 'aneesh reddy, teruhide sato',
 'aneesh seth',
 'angellist',
 'angelprime',
 'angie mahtaney',
 'anglian omega network',
 'ani technologies pvt. ltd',
 'anicut capital',
 'anil advani',
 'anil chopra',
 'anil gelra',
 'anil jaggia',
 'anil jain',
 'anil jain, other hnis',
 'anil kapoor',
 'anil matai',
 'anil menon',
 'anindya ghose',
 'aniruddha malpani',
 'anirudh damani',
 'anirudh rastogi',
 'anirudh sheth',
 'anish k',
 'anisha mittal',
 'anita dongre',
 'anita gupta',
 'anita hassanandani',
 'anjali bansal',
 'anjani prasad',
 'ankit aditya',
 'ankit bhati',
 'ankit gupta',
 'ankit kesarwani',
 'ankit maheshwari',
 'ankit nagori',
 'ankit sharma',
 'ankur capital',
 'ankur gupta',
 'ankur singla',
 'ankur warikoo',
 'ankush gupta',
 'ankush mehta',
 'ankush nijhawa',
 'ankush nijhawan',
 'ankush saigal',
 'annuity association (tiaa)',
 'anoop goyal',
 'anoop hingorani',
 'anshoo gaur',
 'anshu bahadur',
 'anshu sharma',
 'anshul jindal',
 'anshuman das',
 'ant financial',
 'ant financial services (alipay)',
 'ant financials',
 'anthil ventures, others',
 'anthill scale ventures',
 'anthill ventures',
 'anubhav verma',
 'anuj agrawal',
 'anuj golecha',
 'anuj gupta',
 'anuj puri',
 'anuj sanghi',
 'anuj srivastava',
 'anupam mittal',
 'anupam mittal, other marquee investors',
 'anupam mittal, others',
 'anupam tyagi',
 'anurag chauhan',
 'anurag gupta',
 'anurag srivastava',
 'aparup sengupta',
 'apis partner',
 'apis partners',
 'apoletto',
 'apoletto managers',
 'apoletto managers.',
 'apoorv ranjan sharma',
 'apoorva patni',
 'appliyifi',
 'applyifi',
 'aprameya',
 'aprameya radhakrishna',
 'aprameya radhakrishnan',
 'apurva chamaria',
 'apurva salapuria',
 'apurva salarpuria',
 'aqeel ahmed',
 'aramex ventures llc',
 'arathi krishna',
 'aravind sanka',
 'arena ventures',
 'arihant patni',
 'arihant patni of patni family office',
 'arjun',
 'arjun handa',
 'arjun malhotra',
 'arjun mehta',
 'arjun sharmaa',
 'arkas industries',
 'armat group',
 'arpan nagdeve',
 'artesian venture partners',
 'artha india ventures',
 'artha venture',
 'arthavida ventures',
 'artiman ventures',
 'arts alliance',
 'arun chandra mohan',
 'arun duggal',
 'arun garg',
 'arun khanna',
 'arun malhotra',
 'arun patodia',
 'arun sarin',
 'arun seth',
 'arun tadanki',
 'arun venkatachalam',
 'aruna ganesh ram',
 'arvind jha',
 'arvind uppal',
 'ascent capital',
 'aseem sood',
 'ash bhardwaj',
 'asha jadeja motwani, others',
 'ashim mehra',
 'ashish agrawal',
 'ashish chand',
 'ashish dev kapur',
 'ashish dhawan',
 'ashish goenka',
 'ashish goenka, others',
 'ashish gupta',
 'ashish hemrajani',
 'ashish jhalani',
 'ashish kacholi',
 'ashish kashyap',
 'ashish lakhanpal',
 'ashish mahajan',
 'ashish tiwari',
 'ashish todi',
 'ashish toshniwal',
 'ashish tulsian',
 'ashneer grover',
 'ashok agarwal',
 'ashok goel (promoter)',
 'ashok kumar gajera',
 'ashutosh lawania',
 'ashvin chadha',
 'asia pacific internet group',
 'asian healthcare fund',
 'ask pravi',
 'askme',
 'asp consulting',
 'aspada',
 'aspada advisors',
 'aspada investment',
 'aspada investment advisors',
 'aspada investments',
 'aspada ventures',
 'aspire logistics llc',
 'aspire systems',
 'asset management (asia) ltd',
 'astarc ventures',
 'astarc ventures, others',
 'asuka',
 'asuka holdings',
 'atul agarwal',
 'atul goel',
 'atul gupta',
 'atul ingle',
 'atul jain',
 'atul jalan',
 'atul nishar',
 'atul phadnis',
 'atulya mittal',
 'augment ventures',
 'august capital partners',
 'auxano deals',
 'av thomas group',
 'avalon ventures',
 'avendus finance',
 'avendus finance pvt. ltd',
 'avg group',
 'avn business solutions',
 'avnish mehra',
 'avtar monga',
 'axan partners',
 'axan venture',
 'axiata digital',
 'axilor',
 'axilor partners',
 'axilor ventures',
 'axis bank',
 'axis capital',
 'axis capital partners',
 'axis capital, others',
 'axis capital.',
 'axon partners',
 'ayesha takia azmi',
 'ayushmann khurana',
 'azim premji',
 'azmul haque',
 'b capital',
 'b capital group',
 'b m gupta',
 'b s nagesh',
 'bac acquisitions',
 'badal malick',
 'baillie gifford',
 'balaji prabhakar',
 'balamurali krishna',
 'balamurugan mani',
 'balasubramanian krishnamurthy',
 'bamboo capital partners',
 'bank to the future',
 'barkawi holdings gmbh',
 'basab pradhan',
 'base of pyramid asia (bopa) pte ltd',
 'baskar subramanian',
 'batlivala, karani securities',
 'battery road digital holdings llc',
 'bay capital investments',
 'bc prabhakar',
 'bccl',
 'bedrock ventures',
 'beehive capital advisor',
 'beenext',
 'beenext ventures',
 'beenextan investment fund',
 'beenos',
 'beenos asia',
 'beerud sheth',
 'behram vakil',
 'bennett',
 'bennett coleman',
 'bennett coleman, co. ltd',
 'benori ventures llp',
 'berggruen holdings',
 'bertelsmann india',
 'bertelsmann india investments',
 'bertelsmann india investments norwest venture partners.',
 'bessemer venture',
 'bessemer venture partner',
 'bessemer venture partners',
 'bessemer ventures',
 'best foodworks',
 'betonindia technology pvt ltd',
 'better capital angellist syndicate.',
 'betty moore foundation',
 'bhairavi jani',
 'bhanu vikram parsotam',
 'bharanidharan viswanathan',
 'bharat gupta',
 'bharat innovation',
 'bharat kedia',
 'bharat sheth',
 'bharat vijay',
 'bharti enterprises',
 'bhavdeep reddy',
 'bhavesh manglani',
 'bhavesh p',
 'bhavin turakhia',
 'bhavish aggarwal',
 'bhupen shah',
 'bhupen shah, others',
 'bhupender singh',
 'big data investments b.v',
 'bijou kurien',
 'bijoy george',
 'bill, melinda gates foundation',
 'binny bansal',
 'bitchemy ventures',
 'bitkemy ventures',
 'biz stone',
 'bizreach',
 'blackjag partners',
 'blacksoil',
 'blacksoil capital pvt ltd',
 'blacksoil capital pvt. ltd',
 'blacksoil capital pvt. ltd.',
 'blackstone valley group',
 'blinc advisors',
 'blip initiatives',
 'blue cloud ventures',
 'blue fog capital',
 'blue orchard',
 'blueorchard finance ltd',
 'blume ventures',
 'blume ventures, ivycap ventures',
 'blume ventures, other unnamed investors',
 'blume ventures, others',
 'blume ventures, vaibhav domkundwar',
 'blume ventures.',
 'blume ventures. lenovo capital',
 'bobby reddy',
 'bodhtree consulting limited',
 'boillot family trust',
 'bold ventures',
 'boman irani',
 'bookmyshow',
 'bookmyshow)',
 'boost vc',
 'brahmax ventures',
 'brand capital',
 'bravia capital',
 'brd securities',
 'breakthrough energy ventures',
 'bren corporation',
 'brian acton',
 'brick eagle',
 'brigade innovations llp',
 'british',
 'broadbean capital services',
 'bs nagesh',
 'bunny bansal, other investors',
 'burda principal investments',
 'bvr mohan reddy',
 'bytedance',
 'c31 ventures',
 'c4d partners',
 'ca media lp',
 'calcutta angel network',
 'calcutta angels',
 'calcutta angels network',
 'calcutta angels network (can)',
 'cameron jones',
 'canaan partners',
 'cao yibin',
 'capier investments',
 'capillary technologies',
 'capital advisers',
 'capitalg',
 'capricorn investment',
 'capricorn investment group',
 'careernet consulting pvt. ltd',
 'carlyle group',
 'carnegie mellon university',
 'carpediem capital',
 'carpediem capital, others',
 'carrick capital partners',
 'cashurdrive marketing pvt ltd',
 'caspian',
 'catamaran ventures',
 'cataraman ventures',
 'cba capital',
 'ccavenue',
 'ccube angels',
 'cdc group',
 'cdc group plc',
 'centre for incubation, business acceleration (ciba)',
 'centre for innovation incubation',
 'cerracap',
 'chairman of career information portal careers360',
 'chan zuckerberg initiative',
 'chanakya hridaya',
 'chandigarh angel network (can)',
 'chandigarh angels',
 'chandigarh angels funding',
 'chandigarh angels network',
 'chandigarh angels network (can)',
 'chandrakant gogri',
 'chandralekha construction pvt. ltd.',
 'chandrashekar tallapragada',
 'chandru badrinarayanan',
 'chatsworth management',
 'chavi jafa',
 'cheetah mobile',
 'chennai angels',
 'cherry tin',
 'chetan bhagat',
 'chicago capital ventures',
 'chidambaram palaniappan',
 'chief operating office at idfc bank',
 'china lodging group',
 'china-based citic capital',
 'chip perry',
 'chirag nikunj sheth, others',
 'chiratae ventures',
 'chiratae ventures (formerly idg ventures)',
 'chryscapital',
 'cio angel network',
 'cio angel network (can)',
 'cipher-plexus capital advisors, indian hnis',
 'cisco investments',
 'cisco ventures',
 'cismat cargo services pvt. ltd.',
 'citi ventures',
 'citrus payments',
 'clairvest group',
 'claris capital',
 'clp holdings group',
 'clsa capital partners aria iv funds',
 'cmyk health boutique pvt ltd, other individual investors',
 'co pvt ltd',
 'co. ltd (bccl)',
 'coatue management',
 'cocapital',
 'cocreate ventures',
 'cogent e services',
 'coleman',
 'collaborative licensing ventures llp',
 'commonfloor',
 'company ltd',
 'company ltd (bccl)',
 'composite capital management',
 'concur technologies',
 'consortium of angel investors',
 'constellation technology ventures (exelon corporation)',
 'contrarian capital',
 'contrarian capital india partners',
 'contrarian vriddhi fund',
 'cooperative oikocredit',
 'corvus ventures',
 'costanoa',
 'cota capital',
 'cp bothra',
 'creation investments',
 'creation investments capital management',
 'credence family office',
 'credika',
 'cross border angels',
 'cross border angels, experts',
 'cross border angels, others',
 'crv',
 'csc upshot, angel investors',
 'ctrip.com international ltd',
 'curefit',
 'currae healthtech fund',
 'cyber carrier',
 'cyber carrier cl',
 'cyber carrier vc',
 'cyberagent ventures',
 'da-iict',
 'daffodil software',
 'dah beteiligungs gmbh',
 'dalip pathak',
 'daljit singh',
 'daman soni',
 'dangold investment corp',
 'darius pandole',
 'darrin capital',
 'darshak shah',
 'darshan upadhyay',
 'das capital',
 'daud ali',
 'deep kalra',
 'deep kalra, others',
 'deepak chokhani',
 'deepak ghaisas',
 'deepak gupta',
 'deepak gurnani',
 'deepak jain',
 'deepak kulkarni',
 'deepak nathani',
 'deepak natraj',
 'deepak shahdadpuri',
 'deepak sharma',
 'deepak singh',
 'deepinder goyal',
 'delhivery',
 'delta partners',
 'dena',
 'dena co.',
 'denlow investment trust',
 'deobrat singh',
 'deshe holdings',
 'deshpande foundation',
 'deutsche telekom strategic investments (dtsi)',
 'deutsche telekom strategic investments, others',
 'devdeep singh',
 'development finance institution belgian investment company',
 'devendra rane',
 'devendra reddy',
 'devesh rai g',
 'devesh sachdev',
 'devidas desai',
 'devry inc',
 'dewan housing finance corp',
 'dewang neralla',
 'dexter angel circle',
 'dg daiwa ventures',
 'dg incubation',
 'dg ventures india',
 'dheerag jain',
 'dheeraj jain',
 'dheeraj jain, other angel investors',
 'dheeraj jain, others',
 'dheeraj mehta, others',
 'dheeraj pandey',
 'dhi group inc',
 'dhiraj rajaram',
 'dhruv chitgopekar',
 'diageo india',
 'diaz nesamoney',
 'didi chuxing',
 'didi kuaidi',
 'dig investment ab',
 'digital currency group',
 'digital financial service lab',
 'digital garage',
 'digital garage inc',
 'dila capital',
 'dileep bhatt',
 'dileep nath',
 'dilip khandwelwal from sap labs india',
 'dinesh agarwal',
 'dinesh kundu, others',
 'dinesh mittal',
 'dinesh r. challa',
 'dino morea',
 'director at byramjee jeejeebhoy pvt. ltd were among the angels',
 'divyesh shah',
 'dmg information',
 'dmg information asia pacific',
 'dmi finance',
 'doreswamy nandkishore',
 'dr david cheriton',
 'dr devi shetty',
 'dr faraz naqvi',
 'dr mushtaq shah',
 'dr nandish domlur',
 'dr paresh doshi',
 'dr ramesh ayyala',
 'dr v ravinder',
 'dr. abhishek pandey',
 'dr. aniruddha malpani',
 'dr. aniruddha malpani manish gupta',
 'dr. apoorv ranjan sharma',
 'dr. goutam challagalla',
 'dr. pooja gandhi',
 'dr. pramath raj sinha',
 'dr. prasad kaipa',
 'dr. rameshwar kumar',
 'dr. ranjan pai',
 'dr. ritesh malik',
 'dr. sridhar ramaswamy',
 'dragoneer investment',
 'dragoneer investment group',
 'draper associates',
 'draper fisher jurvetson',
 'draphant consultants',
 'dream incubator',
 'dreamweaver investments',
 'dsg consumer partners',
 'dst global',
 'dst partners',
 'dtdc express ltd',
 'dunamis ventures pte ltd',
 'dunamis ventures pte ltd.',
 'dutch government fund',
 'e-city ventures atul goel',
 'e.on',
 'e.ventures',
 'eagle10 ventures',
 'earlsfield capital',
 'east ventures, others',
 'ebay',
 'ecl finance',
 'ecoenterprise fund',
 'econtext asia',
 'edbi',
 'edelweiss',
 'edelweiss financial services',
 'edelweiss private equity',
 'edfimc (electrifi)',
 'eduardo saverin',
 'eduardo saverin, velos capital',
 'eight innovate',
 'eight road ventures',
 'eight roads',
 'eight roads ventures',
 'eight roads ventures india',
 'electronic development fund',
 'elevar equity',
 'elevate sports',
 'elliot stechman',
 'emerald media',
 'emergent ventures',
 'emergent ventures india',
 'emerging india',
 'emery capital',
 'empire angels',
 'enablers platform',
 'endeavor catalyst fund',
 'endiya partners',
 'engie rde fund',
 'ennovent impact investment holding',
 'entrepreneurs india',
 'entrepreneurship (ciie)',
 'epsilon venture partners',
 'equanimity venture fund',
 'equanimity ventures',
 'equentia natural resource, other undisclosed investors',
 'equentia natural resources',
 'equity crest',
 'eros labs',
 'esvee technologies inc',
 'eureka forbes ltd',
 'european investment fund',
 'evan lim',
 'evc ventures',
 'excelsior investments',
 'exfinity',
 'exfinity fund',
 'exfinity venture',
 'exfinity venture partners',
 'exfinity venture partners, others',
 'exfinity ventures',
 'existing investors',
 'existing, new investors',
 'experian',
 'extreme venture partners  william bissell',
 'f-prime capital partners',
 'facebook fb start programme',
 'facebook fbstart',
 'factor[e] ventures',
 'faering capital',
 'fairfax',
 'fairfax holdings',
 'falcon edge',
 'falcon edge capital',
 'family office fund',
 'family pot investments llp',
 'fao ventures',
 'faraz khan',
 'farhaan shabbir',
 'farhan naqvi',
 'farm to fork',
 'farooq adam',
 'farooq adam mukadam',
 'farooq oomerbhoy',
 'farooq oomerbhoy, other angel investors',
 'fauzan rahim',
 'fenqile',
 'ff angel',
 'fidelity biosciences',
 'fidelity growth partners',
 'fidelity growth partners india',
 'fih mobile ltd',
 'fil capital management',
 'finc',
 'fintech',
 'fireside ventures',
 'fireside ventures, others',
 'firoze irani',
 'fj labs',
 'flipkart',
 'flipkart logistics pvt. ltd',
 'florida based angel investor',
 'florintree',
 'florintree advisors',
 'ford smart mobility llc',
 'fork media',
 'fortisure ventures',
 'forum synergies pe fund',
 'fosun international',
 'fosun rz capital',
 'foundation capital',
 'founder',
 'founder collective',
 'founders fund',
 'foxconn',
 'foxconn technology group',
 'foxconn technology group, others',
 'francesco cara',
 'franchise india',
 'franchise india brands',

In [134]:
fund.to_csv('fund_cleaned_final.csv',index=False)

In [135]:
fund_investor_final = fund.explode('investor_clean').reset_index(drop=False)

In [136]:
fund_investor_final.to_csv('fund_investor_final.csv',index=False)

In [137]:
fund.sort_values(by='date',ascending=False)

,date,startup,vertical,subvertical,investors,round,amount,startup_clean,investor_clean,round_clean,city_clean,is_cross_border
Sr No,,,,,,,,,,,,
6,2020-01-13,pando,Logistics,"Open-market, freight management platform",Chiratae Ventures,Series A,86.10,pando,[chiratae ventures],series a,chennai,False
2,2020-01-13,shuttl,Transportation,App based shuttle service,Susquehanna Growth Equity,Series C,77.00,shuttl,[susquehanna growth equity],series c,gurgaon,False
7,2020-01-10,zomato,Hospitality,Online Food Delivery Platform,Ant Financial,Private Equity Round,1435.05,zomato,[ant financial],private equity round,gurgaon,False
1,2020-01-09,byjus,E-Tech,E-learning,Tiger Global Management,Private Equity Round,1913.40,byjus,[tiger global management],private equity round,bengaluru,False
3,2020-01-09,mamaearth,E-commerce,Retailer of baby and toddler products,Sequoia Capital India,Series B,175.64,mamaearth,[sequoia capital india],series b,bengaluru,False
...,...,...,...,...,...,...,...,...,...,...,...,...
2994,2015-01-05,gympik,Unknown,Unknown,"Tom Clausen, Rohan Ajila, Haldyn Glass",Seed Funding,1.29,gympik,"[tom clausen, rohan ajila, haldyn glass]",seed funding,Unknown,False
2992,2015-01-05,lookup,Unknown,Unknown,"DeNA Co., Japan & Teruhide Sato (in Addition t...",Seed\\nFunding,3.64,lookup,"[dena co., japan, teruhide sato (in addition t...",seed funding,Unknown,False
2993,2015-01-05,#fame,Unknown,Unknown,TO THE NEW Ventures,Private Equity,95.67,#fame,[to the new ventures],private equity,Unknown,False
2990,2015-01-02,lenskart,Unknown,Unknown,"TPG Growth, TR Capital, IDG Ventures",Private Equity,20.57,lenskart,"[tpg growth, tr capital, idg ventures]",private equity,Unknown,False
2991,2015-01-02,violetstreet,Unknown,Unknown,"Venkat Vallabhneni, Sudhakar Reddy, Srinivasa ...",Seed\\nFunding,3.01,violetstreet,"[venkat vallabhneni, sudhakar reddy, srinivasa...",seed funding,Unknown,False

In [138]:
fund_investor.sort_values(by='date',ascending=False)

,Sr No,date,startup,vertical,subvertical,investors,round,amount,startup_clean,investor_clean,round_clean,city_clean,is_cross_border
1,2,2020-01-13,shuttl,Transportation,App based shuttle service,Susquehanna Growth Equity,Series C,77.00,shuttl,susquehanna growth equity,series c,gurgaon,False
5,6,2020-01-13,pando,Logistics,"Open-market, freight management platform",Chiratae Ventures,Series A,86.10,pando,chiratae ventures,series a,chennai,False
6,7,2020-01-10,zomato,Hospitality,Online Food Delivery Platform,Ant Financial,Private Equity Round,1435.05,zomato,ant financial,private equity round,gurgaon,False
0,1,2020-01-09,byjus,E-Tech,E-learning,Tiger Global Management,Private Equity Round,1913.40,byjus,tiger global management,private equity round,bengaluru,False
2,3,2020-01-09,mamaearth,E-commerce,Retailer of baby and toddler products,Sequoia Capital India,Series B,175.64,mamaearth,sequoia capital india,series b,bengaluru,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5950,2991,2015-01-02,violetstreet,Unknown,Unknown,"Venkat Vallabhneni, Sudhakar Reddy, Srinivasa ...",Seed\\nFunding,3.01,violetstreet,venkat vallabhneni,seed funding,Unknown,False
5947,2990,2015-01-02,lenskart,Unknown,Unknown,"TPG Growth, TR Capital, IDG Ventures",Private Equity,20.57,lenskart,tpg growth,private equity,Unknown,False
5948,2990,2015-01-02,lenskart,Unknown,Unknown,"TPG Growth, TR Capital, IDG Ventures",Private Equity,20.57,lenskart,tr capital,private equity,Unknown,False
5949,2990,2015-01-02,lenskart,Unknown,Unknown,"TPG Growth, TR Capital, IDG Ventures",Private Equity,20.57,lenskart,idg ventures,private equity,Unknown,False
5951,2991,2015-01-02,violetstreet,Unknown,Unknown,"Venkat Vallabhneni, Sudhakar Reddy, Srinivasa ...",Seed\\nFunding,3.01,violetstreet,sudhakar reddy,seed funding,Unknown,False

In [139]:
fund_investor_final = fund_investor_final.sort_values(by='date',ascending=False)

In [140]:
fund_investor_final[fund_investor_final['investor_clean'] == 'tiger global management']

,Sr No,date,startup,vertical,subvertical,investors,round,amount,startup_clean,investor_clean,round_clean,city_clean,is_cross_border
0,1,2020-01-09,byjus,E-Tech,E-learning,Tiger Global Management,Private Equity Round,1913.40,byjus,tiger global management,private equity round,bengaluru,False
85,56,2019-08-22,indwealth,FinTech,Wealth Management,Tiger Global Management,Venture Round,143.50,indwealth,tiger global management,venture round,gurgaon,False
104,69,2019-07-11,moglix,E-Commerce,Industrial Tools and Equipments,"Composite Capital Management, Sequoia Capital ...",Series D,574.02,moglix,tiger global management,series d,singapore,False
134,86,2019-06-10,okcredit,FinTech,Financial Services,Tiger Global Management,Series A,148.29,okcredit,tiger global management,series a,haryana,False
154,94,2019-05-02,zenoti,Saas,Beauty and Wellness Industry,Tiger Global Management,Series C,478.35,zenoti,tiger global management,series c,hyderabad,False
177,108,2019-04-11,clevertap,SaaS,Mobile analytics and marketing,"Sequoia India, Tiger Global Management, Accel ...",Series B,248.74,clevertap,tiger global management,series b,mumbai,False
1085,548,2017-10-13,chaayos,eCommerce,Online Chai ordering platform,Tiger Global Management,Private Equity,19.13,chaayos,tiger global management,private equity,gurgaon,False
4031,2037,2016-01-12,shopclues,ECommerce,ECommerce Marketplace,"GIC, Tiger Global Management, Nexus Venture Pa...",Private Equity,956.70,shopclues,tiger global management,private equity,gurgaon,False
4227,2141,2015-12-10,blackbuck,Online Freight Services Aggregator,Unknown,"Tiger Global Management, Yuri Milner, Apoletto...",Private Equity,239.18,blackbuck,tiger global management,private equity,bengaluru,False
4665,2363,2015-10-26,razorpay,Online Payment Gateway,Unknown,"Tiger Global Management, Matrix Partners",Private Equity,86.10,razorpay,tiger global management,private equity,jaipur,False
4576,2314,2015-10-08,cube26,Gesture based Mobile Development,Unknown,"Tiger Global Management, Flipkart",Private Equity,73.67,cube26,tiger global management,private equity,new delhi,False
4954,2508,2015-08-10,grey orange,Automated Storage & Warehousing Solution,Unknown,Tiger Global Management,Private Equity,287.01,grey orange,tiger global management,private equity,gurgaon,False
4888,2483,2015-08-05,zo rooms,Online budget hotel chain,Unknown,"Tiger Global Management, Orios Venture Partners",Private Equity,287.01,zo rooms,tiger global management,private equity,new delhi,False
5113,2593,2015-07-08,saavn,Music Streaming App,Unknown,"Tiger Global Management, Bertelsmann India, St...",Private Equity,956.70,saavn,tiger global management,private equity,mumbai,False
5134,2601,2015-07-08,lybrate,Healthcare Mobile App,Unknown,"Tiger Global Management, Ratan Tata, Nexus Ven...",Private Equity,97.58,lybrate,tiger global management,private equity,new delhi,False
5489,2786,2015-05-19,chaayos,Offline Tea Chain,Unknown,Tiger Global Management,Private Equity,9.57,chaayos,tiger global management,private equity,new delhi,False
5461,2768,2015-05-07,vedantu,Online Education Platform,Unknown,"Accel Partners, Tiger Global Management",Private Equity,47.84,vedantu,tiger global management,private equity,bengaluru,False
5449,2763,2015-05-06,delhivery,Ecommerce Logistics,Unknown,"Tiger Global Management, Multiples Alternate A...",Private Equity,813.20,delhivery,tiger global management,private equity,gurgaon,False
5587,2835,2015-04-14,localoye,Hyper-local Online Services,Unknown,"Tiger Global Management, Lightspeed Venture Pa...",Private Equity,47.84,localoye,tiger global management,private equity,mumbai,False
5751,2921,2015-03-26,roposo,Unknown,Unknown,"Tiger Global Management, Indian Quotient, Binn...",Private Equity,47.84,roposo,tiger global management,private equity,Unknown,False
5884,2989,2015-02-27,grofers,Unknown,Unknown,"Tiger Global Management, Sequoia Capital India",Private Equity,95.67,grofers,tiger global management,private equity,Unknown,False

In [141]:
fund_investor_final[fund_investor_final['investor_clean'].str.contains('tiger global management')].head()

,Sr No,date,startup,vertical,subvertical,investors,round,amount,startup_clean,investor_clean,round_clean,city_clean,is_cross_border
0,1,2020-01-09,byjus,E-Tech,E-learning,Tiger Global Management,Private Equity Round,1913.40,byjus,tiger global management,private equity round,bengaluru,False
85,56,2019-08-22,indwealth,FinTech,Wealth Management,Tiger Global Management,Venture Round,143.50,indwealth,tiger global management,venture round,gurgaon,False
104,69,2019-07-11,moglix,E-Commerce,Industrial Tools and Equipments,"Composite Capital Management, Sequoia Capital ...",Series D,574.02,moglix,tiger global management,series d,singapore,False
134,86,2019-06-10,okcredit,FinTech,Financial Services,Tiger Global Management,Series A,148.29,okcredit,tiger global management,series a,haryana,False
154,94,2019-05-02,zenoti,Saas,Beauty and Wellness Industry,Tiger Global Management,Series C,478.35,zenoti,tiger global management,series c,hyderabad,False

In [142]:
fund_investor_final[fund_investor_final['investor_clean'].str.contains('tiger global management')].groupby('startup_clean')['amount'].sum().sort_values(ascending=False).head()

startup_clean
byjus        1913.40
saavn         956.70
shopclues     956.70
delhivery     813.20
moglix        574.02
Name: amount, dtype: float64

In [143]:
fund_investor_final[fund_investor_final['investor_clean'].str.contains('tiger global management')].groupby('vertical')['amount'].sum().sort_values(ascending=False).head(10)

vertical
E-Tech                                      1913.40
ECommerce                                    956.70
Music Streaming App                          956.70
Ecommerce Logistics                          813.20
E-Commerce                                   574.02
Saas                                         478.35
Hyperlocal Deals Marketplace                 478.35
FinTech                                      291.79
Automated Storage & Warehousing Solution     287.01
Online budget hotel chain                    287.01
Name: amount, dtype: float64

In [144]:
fund_investor_final['year'] = fund_investor_final['date'].dt.year
fund_investor_final[fund_investor_final['investor_clean'].str.contains('tiger global management')].groupby('year')['amount'].sum()

year
2015    3567.56
2016     956.70
2017      19.13
2018     172.21
2019    1592.90
2020    1913.40
Name: amount, dtype: float64

In [145]:
fund_investor_final[fund_investor_final['investor_clean'].str.contains('tiger global management')].groupby('round_clean')['amount'].sum()

round_clean
private equity          4715.60
private equity round    1913.40
series a                 148.29
series b                 248.74
series c                 478.35
series d                 574.02
venture round            143.50
Name: amount, dtype: float64

In [148]:
fund_investor[fund_investor['investor_clean'].str.contains('tiger global management')].groupby('city_clean')['amount'].sum().sort_values(ascending=False)

city_clean
bengaluru    2678.77
gurgaon      2219.54
mumbai       1253.28
singapore     574.02
hyderabad     478.35
new delhi     467.83
chennai       172.21
haryana       148.29
Unknown       143.51
jaipur         86.10
Name: amount, dtype: float64